### ISSUE TITLE
n_jobs crashes kernal

### ISSUE THREAD

**Issue by denutza** [optuna/optuna#1045]
My CPU has 12 threads, any time I optimize with n_jobs >=2 the kernal crashes within 1-2 trials.
I'm tuning  with xgb.train and I have the nthread parameter set to 6.

Is there a conflict between setting both threads?

**Comment by hvy** [comment]
Are you able to provide some more specific information about your environment and code/stacktrace for reproduction?

I'm not familiar with how `nthread` affects the internals of the `DMatrix` unfortunately but I can share that `n_jobs>=2` in Optuna will invoke `joblib.Parallel` [inside the study](https://github.com/optuna/optuna/blob/master/optuna/study.py#L355). Depending on your situation, you might be able to experiment with how `joblib` is invoked, e.g. by changing the default `joblib` backend from multithreading to multiprocessing.

**Comment by denutza** [comment]
I really wouldn't know how to go about a lot of that.

But I should clarify, I didn't literally mean setting "n_jobs>=2".
I meant anywhere from "n_jobs=2" to "n_jobs=12" crashes the kernel. 

***Anything but n_jobs=-1

**Comment by hvy** [comment]
I see. I tried to reproduce this issue with https://github.com/optuna/optuna/blob/master/examples/xgboost_simple.py modifying `params` to contain `nthread` and then also by passing `nthread` to the `DMatrix`es but failed to do so. Maybe the example is too trivial, or it's my environment.

Are you able to work around this issue?  Again, for instance using multi-processing or if you are using a RDB running Optuna from multiple processes (distributed)? I believe you'll have to dig into both/either `DMatrix` and/or `joblib.Parallell` otherwise.

**Comment by hvy** [comment]
Let me close this issue as stale. Feel free to reopen as needed!
