### ISSUE TITLE
Align the order of arguments of `optuna.study.create_study` and `optuna.study.load_study`.

### ISSUE THREAD

**Issue by keisuke-umezawa** [optuna/optuna#1128]
## Motivation

Currently, `optuna.study.create_study` and `optuna.study.load_study` have different orders of arguments, although their roles are similar. I want to align the order of arguments.

- [create_study](https://github.com/optuna/optuna/blob/master/optuna/study.py#L761-L768)
- [load_study](https://github.com/optuna/optuna/blob/master/optuna/study.py#L844-L849)

## Description

I want to align the order of arguments of `optuna.study.create_study` and `optuna.study.load_study`. But we should discuss following points:

1. Which order will we choose?
2. As much as possible we should avoid disturbing users because of changing orders.

**Comment by hvy** [comment]
Thanks for bringing this up, it's definitely something that should be uprooted... The problem is that there doesn't seem to be a straight forward way to go through a deprecation process. Additionally, as both functions are likely already used by the majority of the users (at least `create_study`), it's better not to make any rushed changes before hearing the opinions from more users. Let me close this issue for now but allow reopening "as needed".
