### ISSUE TITLE
Which sampler is used by default for relative sampling?

### ISSUE THREAD

**Issue by DavidPfl** [optuna/optuna#1250]
From what I understand, when calling [`optuna.study.create_study`](https://optuna.readthedocs.io/en/stable/reference/study.html#optuna.study.create_study), the [`TPMESampler`](https://optuna.readthedocs.io/en/stable/reference/samplers.html#optuna.samplers.TPESampler) is used as the default sampler.

And as I understand from [`optuna.samplers.BaseSampler`](https://optuna.readthedocs.io/en/stable/reference/samplers.html#), during one trial, first a relative search space is defined, then [`sample_relative`](https://optuna.readthedocs.io/en/stable/reference/samplers.html#optuna.samplers.BaseSampler.sample_relative) is called and later, if the target parameter does not exist in the search space, [`sample_independent`](https://optuna.readthedocs.io/en/stable/reference/samplers.html#optuna.samplers.BaseSampler.sample_independent) is used to sample a value for the target parameter.

So my questions are:

1. Is the  [`TPMESampler`](https://optuna.readthedocs.io/en/stable/reference/samplers.html#optuna.samplers.TPESampler) also used as the sampler for [`sample_relative`](https://optuna.readthedocs.io/en/stable/reference/samplers.html#optuna.samplers.BaseSampler.sample_relative), because it is defined as the default sampler in [`optuna.study.create_study`](https://optuna.readthedocs.io/en/stable/reference/study.html#optuna.study.create_study)?
2. If no, then which sampler is used by default when [`sample_relative`](https://optuna.readthedocs.io/en/stable/reference/samplers.html#optuna.samplers.BaseSampler.sample_relative) is called in a trial?

If my questions are unclear or should be posted elsewhere, please let me know.

Best Regards

**Comment by HideakiImamura** [comment]
Thank you for your question! I will answer the questions as follows.

The `TPESampler` is also used as the default sampler for `sample_relative`. But, in the current Optuna implementation, the `TPESampler` does not adapt to `sample_relative`, that is, never samples anything in `sample_relative`. (Please refer to [here](https://github.com/optuna/optuna/blob/master/optuna/samplers/tpe/sampler.py#L164).) This is because of the limitation of the TPE algorithm itself (Please refer to the [original paper](https://papers.nips.cc/paper/4443-algorithms-for-hyper-parameter-optimization.pdf)). 

Thus, under the current implementation, we cannot sample values by capturing the dependencies between variables, by default. We have to use another sampler, such as `optuna/samplers/CmaEsSampler` or `optuna/integration/SkoptSampler`. 

However, we will implement the `TPESampler` with multi-dimensional inputs, which can capture the dependencies between variables, in the near future. (Please refer to the TPE algorithm used in [this paper](https://arxiv.org/abs/1807.01774).)

**Comment by HideakiImamura** [comment]
Thank you so much for asking a meaningful question. I'd like to close this issue. If there is anything else you want to ask, please open again.

**Comment by fostiropoulos** [comment]
@HideakiImamura what would be the plan for addressing this issue?

**Comment by HideakiImamura** [comment]
Thanks for your reply. Now, we support the relative sampling in TPESampler.
