### ISSUE TITLE
Stable-Baselines3 RL Example

### ISSUE THREAD

**Issue by araffin** [optuna/optuna#1314]
Hello,

I was wondering if you would be interested in adding an example with Optuna + Stable-Baselines3 for hyperparameter tuning in an reinforcement learning context?

It has been used successfully in both v2 and v3 in the zoo repo:
- https://github.com/DLR-RM/rl-baselines3-zoo
- https://github.com/araffin/rl-baselines-zoo

Stable Baselines:
- https://github.com/hill-a/stable-baselines (v2, tensorflow)
- https://github.com/DLR-RM/stable-baselines3 (v3, pytorch edition)

## Motivation

Hyperparameter tuning is key to RL success and Stable Baselines (SB and SB3) is one of the most popular RL library.

**Comment by hvy** [comment]
Hi @araffin. Thanks for your suggestion and for letting us know about very interesting use cases.

I'd like to know your thoughts on the following as there is probably room for some discussion.  Namely, whether this example should be located in this repository or in one of yours, and by whom it should be created. AFAIK, there are no experts on Stable-Baselines3 in the committer team here so it might be better to have it maintained by one of your references. Is that different from what you imagined?

**Comment by araffin** [comment]
>Namely, whether this example should be located in this repository or in one of yours

This is already included in our two repos in fact.
I can provide a simpler example if needed with a pull request to your repo. Our API is also fairly stable, so we should not have to update it too often.

**Comment by hvy** [comment]
Oh, I see. Could you point me to those examples? I'm sure other committers are interested in those as well. As you pointed out, the stability of the API is something we consider since if the example is to be added, we'll most likely run it in our daily CI jobs to make sure it's not breaking. I don't know how heavy of a task it is but as it's easier to discuss based on code, would you mind creating a pull request?

**Comment by araffin** [comment]
>Could you point me to those examples? 

https://github.com/DLR-RM/rl-baselines3-zoo/blob/master/utils/hyperparams_opt.py

I was writting the PR when I realized that optuna was also supporting python3.5 which is not the case for SB3 (it supports python 3.6+ to use f-strings).
A solution would be to use SB2 instead for python3.5 (which depends on tensorflow), they share the same api, so it should be a one line change.

**Comment by hvy** [comment]
I'm really sorry for the delayed response, noticing you already started working on an example. 

You are right about the supported Python version. Did you imagine something along conditioning imports based on the Python version used? That might be a reasonable approach to keep https://github.com/optuna/optuna/blob/master/setup.py simple. I suppose that it also depends on the user base of SB2 so would like to hear your opinion on that. FYI, we are considering dropping Py 3.5 in Optuna as well, https://github.com/optuna/optuna/issues/1067.

**Comment by araffin** [comment]
>FYI, we are considering dropping Py 3.5 in Optuna as well, #1067.

Good news =) Any date in mind?

I think the best option would be to wait for Optuna to drop python 3.5, this will make the PR much simpler ;)

**Comment by hvy** [comment]
That'd be one option. On the other hand, we are quite interested in taking a look at your examples. How about creating examples that only support Python 3.6 and up? We already have such examples and it's fine as well (we'll skip those conditionally based on Python versions from the CI).

The reason is that we don't have a fixed date yet for the drop. 🙁

**Comment by HideakiImamura** [comment]
PR is going!
