### ISSUE TITLE
Deprecated decorator's message does not appear

### ISSUE THREAD

**Issue by nzw0301** [optuna/optuna#1411]
## Expected behavior

When we run a method or class has [deprecated decorator](https://github.com/optuna/optuna/blob/879009b95b03988e5cd1f2e335f3bf1c6367aa87/optuna/_deprecated.py#L36) of optuna, we expect a warning message is shown. But the current implementation does not show any warning message.

## Environment

- Optuna version: [the lastest version](https://github.com/optuna/optuna/tree/879009b95b03988e5cd1f2e335f3bf1c6367aa87) & [additional commit](https://github.com/nzw0301/optuna/commit/0981f3f4eaed012b744a465f27d4534654fd19d7)
- Python version: 3.8.4
- OS: MacOSX 10.15.5

## Error messages, stack traces, or logs

```
# error messages, stack traces, or logs
```

## Steps to reproduce

1. `pip install git+https://github.com/nzw0301/optuna.git@deprecated-test`
2. Run the following examples: they do not show anything.

## Reproducible examples (optional)

By the [additional commit](https://github.com/nzw0301/optuna/commit/0981f3f4eaed012b744a465f27d4534654fd19d7), `IntLogUniformDistribution` and  `IntLogUniformDistribution.single` have deprecated decorators. But no warning messages appear when they are called:

```python
import optuna
from optuna.distributions import IntLogUniformDistribution

dist = IntLogUniformDistribution(1, 10)
dist.single()
```

Or

```python
import optuna
from optuna.distributions import IntLogUniformDistribution

optuna.logging.set_verbosity(optuna.logging.WARNING)

dist = IntLogUniformDistribution(1, 10)
dist.single()
```

## Additional context (optional)

Other optuna's codes such that it contains `DeprecatedWarning` such as [`optuna.structs.py`](https://github.com/optuna/optuna/blob/879009b95b03988e5cd1f2e335f3bf1c6367aa87/optuna/structs.py) show the warning message by default when we use them.

For example, if I run the following line,

```python
from optuna.structs import FrozenTrial
```

then the following warning message is printed:

```bash
[W 2020-06-24 01:11:56,553] `structs` is deprecated. Classes have moved to the following modules. `structs.StudyDirection`->`study.StudyDirection`, `structs.StudySummary`->`study.StudySummary`, `structs.FrozenTrial`->`trial.FrozenTrial`, `structs.TrialState`->`trial.TrialState`, `structs.TrialPruned`->`exceptions.TrialPruned`.
```

---

Thank you @HideakiImamura for investigating this issue.

**Comment by nzw0301** [comment]
To solve the issue, we will add `_logger = logging.get_logger(__name__)` to a top part of [`optuna._deprecated.py`](https://github.com/optuna/optuna/blob/879009b95b03988e5cd1f2e335f3bf1c6367aa87/optuna/_deprecated.py),
and add `_logger.warning(message)` after `warnings.warn(message, DeprecationWarning)` in [`optuna._deprecated.py`](https://github.com/optuna/optuna/blob/879009b95b03988e5cd1f2e335f3bf1c6367aa87/optuna/_deprecated.py) like other codes.

**Comment by harupy** [comment]
By default, `DeprecationWarning` is not emitted unless it's triggered in `__main__`. This explains why `FrozenTrial` emits a deprecation warning but `IntLogUniformDistribution` does not.

https://docs.python.org/3/library/warnings.html#default-warning-filter

Why do the tests for `deprecated` pass? It's because `pytest.warns` overrides the default Python warnings filters and make all the warnings visible

https://github.com/pytest-dev/pytest/blob/cc283cfe79b9ab97edd2d10fb05d217ff498b809/src/_pytest/recwarn.py#L184

**Comment by nzw0301** [comment]
Thank you for your clarification! Your points are very helpful! Indeed I should have mentioned https://github.com/optuna/optuna/pull/1387#issuecomment-647929395 related to the first point...

I suppose that the warning message will not be formatted when we use `FutureWarning` or `DeprecationWarning` in `warnings.warn(message, HERE)`. So `DeprecationWarning` is more user-friendy because they do not show anything by default.

Note that the current PR, #1412, just applies the same way of other codes.

**Comment by harupy** [comment]
Displaying a warning using a logger does not seem to be the right approach because it doesn't show a stack trace and makes it unclear where the warning is emitted.

**Comment by nzw0301** [comment]
I think your point is beyond this issue because such codes already exist in optuna's codebase. Could you create your point as another issue? Based on the discussion, I will update the solution of this PR.

**Comment by HideakiImamura** [comment]
Hi all. Thank you for all of your contributions. 

After the discussion with core team members, we have decided to use only `warnings.warn()` for the deprecation messages according to https://docs.python.org/3/howto/logging.html, because users can avoid this situation (reported in Issue #1411) by fixing their own code.
![image (1)](https://user-images.githubusercontent.com/38826298/85496863-fc342400-b617-11ea-8d06-6f8a78f9e9d6.png)

However, thanks to the investigation by @nzw0301, we have noticed the following TODOs.
- We should note how to use `warnings.warn()` and `logging.warn()` in https://github.com/optuna/optuna/wiki/Coding-Style-Conventions.
- We should refactor the current optuna code base such as `optuna/structs.py` to use only `warnings.warn()`.

**Comment by HideakiImamura** [comment]
For the second TODO, note that it was recently modified in the ongoing PR #1413, just for deprecation.

**Comment by nzw0301** [comment]
@HideakiImamura Thank you for sharing the conclusion by optuna's core developers. I suppose this issue is not bag, so let me close this issue.


Cheers,

**Comment by harupy** [comment]
@HideakiImamura Thanks for the clarification. Are you planning to replace `DeprecationWarning` (which turned out to be ignored by default) in the `deprecated` decorator with a different warning category class?

**Comment by HideakiImamura** [comment]
@harupy Thanks for the comment. We don't have any plan to change `DeprecationWarning` in the deprecation decorator.

**Comment by harupy** [comment]
@HideakiImamura Thanks for the reply. Got it!
