### ISSUE TITLE
Add option to abort hang trials

### ISSUE THREAD

**Issue by yorickreum** [optuna/optuna#1484]
Sometimes, single trials of my training take excessively long or hang up completely. Then, it were reasonable for optuna to abort these trials and continue with the next trial. This can be implemented by timeouts for the trials.

## Motivation / Problem

I let hyperparamter studies run over the night. From time to time, they hang up because of a single trial – this is really annoying and costs me days. The current option, specifying timeouts for the whole study, does not help at all at here.

**Comment by toshihikoyanase** [comment]
Hello @yorickreum. Thank you for your feature request.
The execution time of objective functions may depend on suggested hyperparameter value, and I think timeout for each trial is useful.

I talked with @sile and he suggested applying a timeout decorator to objective functions. I created a notebook to show this workaround. Please take a look at it.

It uses [`timeout-decorator`](https://pypi.org/project/timeout-decorator/) as follows:
```python
@timeout_decorator.timeout(5, timeout_exception=optuna.TrialPruned, use_signals=False)
def objective(trial):
    x = trial.suggest_float("x", 0, 1)
    time.sleep(10)
    return x

study = optuna.create_study()
study.optimize(objective, n_trials=3)
```

https://colab.research.google.com/drive/17AaLdO2vBtsfEhBuBwEeRrg21Iwbm8Jg?usp=sharing

**Comment by toshihikoyanase** [comment]
Let me close this issue since it has no recent activities. Please feel free to reopen it or create a new issue.

**Comment by maxmoebus** [comment]
Hi @toshihikoyanase,

thanks for sharing the notebook! The timeout decorator seems to prevent that parameter values get suggested. Even if trials finish, they will finish with an empty parameter dictionary and return values are identical.

In the example code below (adapted from your notebook so that trials finish before the timeout), some value for x will be suggested in the first trial, but no unique other value will be suggested and the trials return empty parameter dictionaries. Do you have any other suggestion or is there anything that I'm missing?

Thanks a lot!

Adapted code from linked notebook (https://colab.research.google.com/drive/17AaLdO2vBtsfEhBuBwEeRrg21Iwbm8Jg?usp=sharing):

import time
import timeout_decorator
import optuna

# The timeout decorator raises timeout_decorator.timeout_decorator.TimeoutError
from timeout_decorator.timeout_decorator import TimeoutError

@timeout_decorator.timeout(10, use_signals=False)
def objective(trial):
    x = trial.suggest_float("x", 0, 1)
    print(x)
    for i in range(1,5):
        time.sleep(1)
        print("{} seconds have passed".format(i))
        trial.report(i, step=i-1)
    return x

study = optuna.create_study()
study.optimize(objective, n_trials=3, catch=(TimeoutError,))

**Comment by Phasip** [comment]
Found this and tried, not sure why the use_signals argument is used, this causes timeout-decorator to use multithreading which seems to confuse optuna.
Using `use_signals=True` works fine for me.

**Comment by Phasip** [comment]
Not sure why `use_signals=False` was used in the examples above. timeout-decorator uses multiprocessing when `use_signals=False` which seems to confuse optuna.
Running with `use_signals=True` works fine for me

**Comment by GavrisAS** [comment]
It doesn't work on Windows ((

**Comment by pedroig** [comment]
@toshihikoyanase , I tried the approach suggested [here](https://github.com/optuna/optuna/issues/1484#issuecomment-654002403) but I believe I got [the same issue](https://github.com/optuna/optuna/issues/1484#issuecomment-1209284141) reported by @maxmoebus. However, from what I checked, the parameters from each trial are not persisted in the study after the optimization even though the metric value of each trial is correctly tracked and optimization happens with the correct pruning. Any ideas on how to solve this? I did exactly as suggested in your colab notebook and the issue also happens there and, if you run `study.best_params`, it returns an empty dictionary for example.

**Comment by yanboyang713** [comment]
> @toshihikoyanase , I tried the approach suggested [here](https://github.com/optuna/optuna/issues/1484#issuecomment-654002403) but I believe I got [the same issue](https://github.com/optuna/optuna/issues/1484#issuecomment-1209284141) reported by @maxmoebus. However, from what I checked, the parameters from each trial are not persisted in the study after the optimization even though the metric value of each trial is correctly tracked and optimization happens with the correct pruning. Any ideas on how to solve this? I did exactly as suggested in your colab notebook and the issue also happens there and, if you run `study.best_params`, it returns an empty dictionary for example.

Hello @pedroig, I have the same issue. How did you fix it?

**Comment by nzw0301** [comment]
@yanboyang713 Could you try https://github.com/optuna/optuna/issues/1484#issuecomment-1242892110?

**Comment by IdoShachar** [comment]
@nzw0301 I tried it and I want to summarize this issue.
The timeout-decorator package support the needed functionality but it has two **big** disadvantages:
1. if use_signals=True than you **can't** use multithreading (optimize n_jobs has to be 1) so we get bad runtime.
2. if use_signals=False you **can** use multithreading but the parameters of the trails got lost so you can't even get the best_params

So, is there any way to utilize more cpus and prune trials by timeout?

**Comment by nzw0301** [comment]
@IdoShachar how about manually specifying `timeout` argument at https://github.com/optuna/optuna/blob/8e2f5bde3c769dff9433b3b8f3c84928825d7498/optuna/study/_optimize.py#L99?

**Comment by april211** [comment]
IMHO, I think the trial-timeout property should be added to the corresponding `study` object instead of the `objective` function, so users can easily adjust trial timeout for different experiment parameter settings (which could be specified by python command args).

And I know there exists a property of the `Study` related to [the timeout behavior](https://optuna.readthedocs.io/en/v2.0.0/reference/generated/optuna.study.Study.html#optuna.study.Study.optimize), but that one is on the study level, not the trial level.

**Comment by Zoophish** [comment]
Hi all,

I am running into the same issue here. It seems like a fairly reasonable feature to have, since many hyperparameter combinations will often lead to a model that blocks the objective func for too long. This seems to be a Windows specific issue, because we can't use the signals workaround.

Because Optuna's design requires us to define hyperparameters inside the objective function, it means that the `trial` needs to be passed by reference, however multithreading will make a copy.

The way I work around this is to implement the timeout inside the objective function after collecting the hyperparameter suggestions. I then used the timeout decorator from [here](https://stackoverflow.com/questions/21827874/timeout-a-function-windows) and raise a pruning exeption if it timesout.
