### ISSUE TITLE
Distributed Parallel error: Trial has already finished and can not be updated.

### ISSUE THREAD

**Issue by Pythonatheart** [optuna/optuna#1531]
I am trying the distributed processing with Postgresql.
As per instructions, I have created a study 'optuna_exp' with storage in postgresql database 'Optuna'.
I then execute optimisation script in terminal with the code:
if __name__ == '__main__':
    study = optuna.load_study(study_name='optuna_exp', storage='postgresql+psycopg2://postgres:password@localhost:5432/Optuna')
study.optimize(objective, n_trials=5000)

I am launching 12 terminals and executing the optimization script (32 cores).

The study starts fine on each of the instances but after a while, some instance starts to fail and terminate:

RuntimeError: Trial#5329 has already finished and can not be updated.
RuntimeError: Trial#10154 has already finished and can not be updated.

This repeats randomly with sometimes more than half of the instances terminated due to the RuntimeError. 

## Expected behavior
All instances to complete without error.

## Environment
- Optuna version: 1.5
- Python version: 3.7
- OS: Windows Pro 64-bit
- (Optional) Other libraries and their versions: IDE PyCharm 2020.1.3 Pro.

**Comment by ytsmiling** [comment]
Thank you for reporting the bug. This bug seems to be serious.
Recently, some distribution-related bug was resolved (#1490), and I suspect this problem relates to the bug. If you are able to, could you try to install the latest master branch (check out the master branch and run pip install -e .)?

In case it's a different bug, are you able to give some more details on the reproduction, preferably in code?

**Comment by Pythonatheart** [comment]
Installation from master branch solved the issue. 
I was able to run 50 instances without any dropouts. 
Arigato gozaimasu!
