### ISSUE TITLE
Interrupted jobs and sqlite?

### ISSUE THREAD

**Issue by jeremysalwen** [optuna/optuna#1532]
I have noticed that when I interrupt my tuning when using an sqlite database, then when I continue tuning from the same database, it will launch fewer than n_jobs new runs.  From using study.trials_dataframe() I can see that there are old studies still in the dataframe stuck in the "RUNNING" state.  I am guessing that these two observations are related.

Is there some way I can remove/cancel all trials that are stuck in the "running" state when I restart tuning, so that n_jobs new trials will be launched?

**Comment by toshihikoyanase** [comment]
Hello @jeremysalwen,

> From using study.trials_dataframe() I can see that there are old studies still in the dataframe stuck in the "RUNNING" state.

This phenomenon is a known issue reported in #913. As mentioned in the thread, the method to remove `RUNNING` trials was not implemented due to some technical difficulties. 

> it will launch fewer than n_jobs new runs.

`n_jobs` option does not refer to the existing `RUNNING` trials, and it only changes the `n_jobs` argument of [`joblib.Parallel`](https://joblib.readthedocs.io/en/latest/generated/joblib.Parallel.html) as shown [here](https://github.com/optuna/optuna/blob/master/optuna/study.py#L317-L334). So, I believe that the remaining `RUNNING` trials are harmless and the decrease in the number of parallel jobs is not related to them.

**Comment by jeremysalwen** [comment]
Thanks @toshihikoyanase upon further investigation it looks like my workers are getting killed by https://github.com/optuna/optuna/issues/820
