### ISSUE TITLE
Different sampling behavior depending on Trial Pruned or Trial Failed due to Exception.

### ISSUE THREAD

**Issue by lukovnikov** [optuna/optuna#1552]
It seems the sampling behavior differs between the cases where the trial has been pruned or where the trial failed with an exception.

## Expected behavior

The sets of samples produced by the sampler should remain similar, independent of whether the trial was pruned or the trial failed due to an exception?

## Environment

- Optuna version: 1.5.0 (from pip install)
- Python version: 3.6
- OS: Windows
- (Optional) Other libraries and their versions: Pytorch

## Steps to reproduce
Running this
```python
    def obj(trial):
        x = trial.suggest_uniform("x", -5, 5)
        y = trial.suggest_uniform("y", -5, 5)
        if not(abs(x) > abs(y) or y < 0):
            raise optuna.TrialPruned()
        return (abs(x) + abs(y)) ** 2

    study = optuna.create_study(direction="minimize")
    study.optimize(obj, n_trials=200, catch=(Exception,))
```
and running this:
```python
    def obj(trial):
        x = trial.suggest_uniform("x", -5, 5)
        y = trial.suggest_uniform("y", -5, 5)
        if not(abs(x) > abs(y) or y < 0):
            raise Exception("invalid config")
        return (abs(x) + abs(y)) ** 2

    study = optuna.create_study(direction="minimize")
    study.optimize(obj, n_trials=200, catch=(Exception,))
```
gives very different sets of samples. 

The completed samples produced for the TrialPruned() version are: 
![afbeelding](https://user-images.githubusercontent.com/1732910/88421155-53304300-cde8-11ea-8175-6fded3c04887.png)
The completed samples produced for the Exception() version are:
![afbeelding](https://user-images.githubusercontent.com/1732910/88421188-680cd680-cde8-11ea-9cf8-7edec4efebb6.png)
over different runs.

In the case of a failure due to an exception, the sampler seems to retry other values in the neighbourhood of the failed sample.

Is this behavior expected? It might be bad in some cases, where a portion of the search space leads to memory errors (or other problems). If the sampler keeps resampling very closely, only few experiments will actually be properly run (even a 1000 trial run had only the first 10-20 runs complete, while the remaining all failed).

Is using `TrialPruned()` the correct way to exclude a portion of the search space without further influence on the search behavior (such as the sampler getting discouraged to sample closer to the pruned space)?

**Comment by ytsmiling** [comment]
Thank you for the detailed report. It depends on which samplers you use, but generally, optuna treats pruned trials and failed trials separately. In optuna, failed trials are treated as if there were no such trials. This is because the cause of the failure might be independent of the objective function, e.g., preemptions in cloud environment. On the other hand, Pruned trials are treated as one of the worst performing trials. So this behavior is expected. I think these behaviors should be properly documented, and let us add the documentation issue as our future task.

And I’m afraid to telling you that there are no official methods to perform optimization in constrained search spaces in the current optuna. There are increasing demand of the constrained optimization, and committers are willing to add the feature, but it will take time. But for now, it seems a good option to use the TrialPruned.

**Comment by ytsmiling** [comment]
I’d like to hear other commiters’ opinion.

**Comment by hvy** [comment]
> But for now, it seems a good option to use the TrialPruned.

I agree, given that the author is using the `TPESampler`. 

Note that this might not be the case if using e.g. the `CmaEsSampler` since this one will ignore pruned trials that don't have intermediate values (c.f. [`Trial.report`](https://optuna.readthedocs.io/en/latest/reference/generated/optuna.trial.Trial.html#optuna.trial.Trial.report)) (even when setting [`consider_pruned_trials`](https://optuna.readthedocs.io/en/latest/reference/generated/optuna.samplers.CmaEsSampler.html#optuna.samplers.CmaEsSampler) to `True`). One could maybe return very large dummy value in such cases. Note that one of the purposes of `TrialPruned` is to allow providing feedback to the sampler, not just whether a trial was pruned, but also how many steps it proceeded (assuming it's an iterative algorithm) and how the intermediate values (e.g. learning curves) behaved.

I think we have to document this on a per-sampler level. Part of the issue stems from the fact that each sampler may interpret the pruned trials very differently. An alternative would be to alter the samplers to behave more consistently but I'm not sure that's sensible.

**Comment by HideakiImamura** [comment]
Hi all. I totally agree with the idea that we should document how each sampler treats pruned trials and failed trials. So, I have created an issue, which is marked `contribution-welcome`. Please feel free to work on this issue.

Let me close this issue because the main problem is the lack of documents. If you have any comments, please feel free to reopen this issue. Thanks!

**Comment by fingoldo** [comment]
> In optuna, failed trials are treated as if there were no such trials. This is because the cause of the failure might be independent of the objective function, e.g., preemptions in cloud environment.

Is there any way to let Optuna memorize failed combinations and use them less frequently? Seems like Optuna does not support conditional categorical sampling, therefore, when I'm trying to marry it with Catboost, 90% of my combinations fail because of categrical parameters mismatch, and I don't want to spend such big % of compute budget on apriory bad combinations.
