### ISSUE TITLE
Follow-up tasks for the new tutorial introduced by #1543

### ISSUE THREAD

**Issue by toshihikoyanase** [optuna/optuna#1578]
#1543 introduced Sphinx Gallery to make the tutorial executable. I found some possible follow-up tasks during the review. Let me share them.

- Make the notebooks executable in Google Colab.
- Some notebooks such as 002_configurations and 003_rdb do not contain executable cells. We may need to change the scenario of the tutorial.
- Some code blocks are not rendered in the notebooks. The raw rst markups are shown instead.
- The color and style of some cells are different from the others.

c.f., https://github.com/optuna/optuna/pull/1543#pullrequestreview-458862080

**Comment by crcrpar** [comment]
FYI: Configuration for Sphinx Gallery is as follows:
https://github.com/optuna/optuna/blob/a5a55a6354b3c60dd7e3a08adcbc3818e90599f0/docs/source/conf.py#L177-L187

---

>     * Some notebooks such as 002_configurations and 003_rdb do not contain executable cells. We may need to change the scenario of the tutorial.

Note that this could add other dependencies to 'document' depending on how the new scenario looks like.


---

>     * Some code blocks are not rendered in the notebooks. The raw rst markups are shown instead.

I can totally accept this as Sphinx Gallery in my opinion put their efforts on generating html from .py scripts and jupyter notebook files are extras. I feel like the fix for this is so demanding and one of PyTorch tutorials doesn't handle it. See https://colab.research.google.com/github/pytorch/tutorials/blob/gh-pages/_downloads/3c2b25b8a9f72db7780a6bf9b5fc9f62/tensor_tutorial.ipynb.

---

>     * Make the notebooks executable in Google Colab.

__tl;dr__ What we need to do here is to gather the generated notebooks and commit them to someplace in this repository. Note that the place doesn't need to be in main branch.


Some details:

Notebooks are first generated by sphinx gallery and stored in 'gallery_dirs' like
```bash
~/.ghq/github.com/optuna/optuna/docs followup-1*
optuna-dev ❯ ls -g source/tutorial | grep ipynb
-rw-r--r--  1 staff   6638 Jul 31 16:24 001_first.ipynb
-rw-r--r--  1 staff   6894 Jul 31 16:24 002_configurations.ipynb
-rw-r--r--  1 staff   3896 Jul 28 18:12 003_rdb.ipynb
-rw-r--r--  1 staff   3036 Jul 28 18:12 004_distributed.ipynb
-rw-r--r--  1 staff   3669 Jul 28 18:12 005_cli.ipynb
-rw-r--r--  1 staff   4429 Jul 28 18:12 006_attributes.ipynb
-rw-r--r--  1 staff   5545 Jul 31 16:24 007_pruning.ipynb
-rw-r--r--  1 staff   7019 Jul 28 18:12 008_sampler.ipynb
```
ICYMI, `docs/source/tutorial` is ignored per https://github.com/optuna/optuna/blob/a5a55a6354b3c60dd7e3a08adcbc3818e90599f0/.gitignore#L113.

Then these notebooks are copied (I guess this from the behavior, not pretty sure) to `build/html/_downloads/<some hash>/*.ipynb` like
```bash
~/.ghq/github.com/optuna/optuna/docs followup-1*
optuna-dev ❯ tree build/html/_downloads
build/html/_downloads
├── 033fc4e5ae5b8ef3bc15b7fb9372a65c
│   └── 001_first.py
├── 099d480324a42e306c8c275bc90eb7bc
│   └── 002_configurations.ipynb
├── 197b14d1beb1d4aa5a181eb27999300b
│   └── 004_distributed.py
├── 1b9fe3058ce64bb498dad4caf3b5e978
│   └── 006_attributes.py
├── 2171bb67b75889d09d066e1321b57eec
│   └── 006_attributes.ipynb
├── 3722fa3f31cef0a438d4a50f76cad669
│   └── 008_sampler.py
├── 46c276624e2aec532ec843f1d5f7edb1
│   └── 002_configurations.py
├── 4fd2dc34794eb5da17368e5eaef7c5c7
│   └── tutorial_python.zip
├── 69a11d5e5d60c63193fd68e9f5cb5b31
│   └── 008_sampler.ipynb
├── 7b74a8376c930484be716b8824f2a98b
│   └── 005_cli.py
├── 7fc21c0b5a6f32d1b742af95b66c5bd7
│   └── 003_rdb.py
├── 8502e0dd1a327d8a35aa3b47e48af3fe
│   └── 005_cli.ipynb
├── a8a228769d4d2fdfa1373b017a4e42b9
│   └── tutorial_jupyter.zip
├── b8f35f4f09fb64e704bb05bf30a6809c
│   └── 001_first.ipynb
├── c0978163eb9d3c569d3ee593dd826b23
│   └── 003_rdb.ipynb
├── da9e878408501221a46674f9157779d3
│   └── 007_pruning.py
├── f1a0fa42ad361425822682a83b02a7e3
│   └── 004_distributed.ipynb
└── f9308c538a683971818b88623548ab4a
    └── 007_pruning.ipynb
```

**Comment by toshihikoyanase** [comment]
@crcrpar Thank you for your detailed explanation. The tasks may be more complicated than I thought.

>> Some code blocks are not rendered in the notebooks. The raw rst markups are shown instead.

>I can totally accept this as Sphinx Gallery in my opinion put their efforts on generating html from .py scripts and jupyter notebook files are extras. I feel like the fix for this is so demanding and one of PyTorch tutorials doesn't handle it. See https://colab.research.google.com/github/pytorch/tutorials/blob/gh-pages/_downloads/3c2b25b8a9f72db7780a6bf9b5fc9f62/tensor_tutorial.ipynb.

Sounds interesting! I'm not familiar with the renderer, but I think the jupyter notebook can render Markdown and the feature can be realized if we add a code-block converter from rst to Markdown.

On the other hand, the rendering issue may become less important if we can make all code blocks executable. So, we may need to consider the priority of the tasks.
