### ISSUE TITLE
LightGBMTunerCV should return the best booster

### ISSUE THREAD

**Issue by antonkulaga** [optuna/optuna#1609]
I cannot receive the best booster from LightGBMTunerCV, this option is available in latest LightGBM ( see https://lightgbm.readthedocs.io/en/latest/pythonapi/lightgbm.cv.html , in particular, return_cvbooster parameter)

**Comment by toshihikoyanase** [comment]
@antonkulaga Thank you for your feature request.

Your request is reasonable, and many users will want it.
The interface can be as follows:

```python
tuner = lgb.LightGBMTunerCV(
    params, dtrain, verbose_eval=100, early_stopping_rounds=100, folds=KFold(n_splits=3),
    return_cvbooster=True,  # `LightGBMTunerCV.__init__` should accept this argument.
)

tuner.run()
cvbooster = tuner.get_best_booster()  # `LightGBMTunerCV` should support this method.
```

We need to wait for LightGBM 3.0.0 to use `return_cvbooster`, but I think we can start the implement of the feature. Let me add `contribution-welcome` label to this issue since the change seems to be simple and good for developers who are familiar with LightGBM.

**Comment by toshihikoyanase** [comment]
I removed `contribution-welcome` label since #1702 is working on this issue.

**Comment by toshihikoyanase** [comment]
#1702 resolved this issue, and let me close it.
@nyanhi I appreciate your great work.
