### ISSUE TITLE
Conditional CategoricalDistribution

### ISSUE THREAD

**Issue by FelixNeutatz** [optuna/optuna#1671]
Dear all,

I am a big fan of Optuna. Thank you for this great system!

However, during my first tries, I run into the following problem:
```
import optuna
from optuna.samplers.random import RandomSampler

def objective(trial):

    dataset = trial.suggest_categorical('dataset', ['sparse_data', 'dense_data'])

    classifiers = ['classifier that can handle sparse and dense']
    if dataset == 'dense_data':
        classifiers.append('classifier that can only handle dense')

    classifier = trial.suggest_categorical('dataset', classifiers)

    return 0

study = optuna.create_study(direction='maximize', sampler=RandomSampler(seed=42))
study.optimize(objective, n_trials=4)
```
Of course, it is well-reported that this will lead to an exception because a [dynamic value space for categories is not supported](https://github.com/optuna/optuna/issues/372):
```
Traceback (most recent call last):
  File "/home/felix/FastFeatures/new_project/fastsklearnfeature/test/optuna/dynamic_categories.py", line 18, in <module>
    study.optimize(objective, n_trials=4)
  File "/home/felix/anaconda3/envs/new_project/lib/python3.7/site-packages/optuna/study.py", line 339, in optimize
    func, n_trials, timeout, catch, callbacks, gc_after_trial, None
  File "/home/felix/anaconda3/envs/new_project/lib/python3.7/site-packages/optuna/study.py", line 682, in _optimize_sequential
    self._run_trial_and_callbacks(func, catch, callbacks, gc_after_trial)
  File "/home/felix/anaconda3/envs/new_project/lib/python3.7/site-packages/optuna/study.py", line 713, in _run_trial_and_callbacks
    trial = self._run_trial(func, catch, gc_after_trial)
  File "/home/felix/anaconda3/envs/new_project/lib/python3.7/site-packages/optuna/study.py", line 734, in _run_trial
    result = func(trial)
  File "/home/felix/FastFeatures/new_project/fastsklearnfeature/test/optuna/dynamic_categories.py", line 12, in objective
    classifier = trial.suggest_categorical('dataset', classifiers)
  File "/home/felix/anaconda3/envs/new_project/lib/python3.7/site-packages/optuna/trial/_trial.py", line 468, in suggest_categorical
    return self._suggest(name, CategoricalDistribution(choices=choices))
  File "/home/felix/anaconda3/envs/new_project/lib/python3.7/site-packages/optuna/trial/_trial.py", line 652, in _suggest
    return self._set_new_param_or_get_existing(name, param_value, distribution)
  File "/home/felix/anaconda3/envs/new_project/lib/python3.7/site-packages/optuna/trial/_trial.py", line 659, in _set_new_param_or_get_existing
    self._trial_id, name, param_value_in_internal_repr, distribution
  File "/home/felix/anaconda3/envs/new_project/lib/python3.7/site-packages/optuna/storages/in_memory.py", line 257, in set_trial_param
    self._studies[study_id].param_distribution[param_name], distribution
  File "/home/felix/anaconda3/envs/new_project/lib/python3.7/site-packages/optuna/distributions.py", line 512, in check_distribution_compatibility
    CategoricalDistribution.__name__ + " does not support dynamic value space."
ValueError: CategoricalDistribution does not support dynamic value space.
```

Now, my question: Is there any way around it to make it work or any hack to accomplish the same?

Best regards,
Felix

**Comment by toshihikoyanase** [comment]
@FelixNeutatz Thank you for your question. As you mentioned, `CategoricalDistribution` can handle only a fixed set of choices. So, I think we need to change the name of hyperparameter (i.e., `"x"` of `trial.suggest_categorical("x", choices))` when we use the different set of choices.

In your case, is it feasible to prepare two classifier lists that correspond to the sparse datasets and the dense datasets?

The following is just an example:
```python
import optuna
from optuna.samplers.random import RandomSampler

def objective(trial):

    dense_classifiers = ["dense svm", ...]
    sparse_classifiers = ["sparse svm", ...]
    dataset = trial.suggest_categorical('dataset', ['sparse_data', 'dense_data'])

    classifiers = ['classifier that can handle sparse and dense']
    if dataset == 'dense_data':
        classifier = trial.suggest_categorical("dense_classifiers", dense_classifiers)
    else:
        classifier = trial.suggest_categorial("sparse_classifiers", sparse_classifiers)

    ...

    return 0

study = optuna.create_study(direction='maximize', sampler=RandomSampler(seed=42))
study.optimize(objective, n_trials=4)
```

**Comment by FelixNeutatz** [comment]
Dear @toshihikoyanase,

thank you, for your answer. Yes, this simple trick should work :)

Best regards,
Felix

**Comment by Lawrence-Krukrubo** [comment]
Was having the very same problem. Thanks for the solution @toshihikoyanase it's helped me too.

**Comment by crownwang301** [comment]
I think i have the roughly same question, unfortunatelly, i am a beginner and i competely learn Optuna by myself.
Below is my code, i do not know how to rorrect. Please help me.
I am using Pytorch, RNN, 2 Classcification.

Part 1: Code 

!pip install optuna
import matplotlib.pyplot as plt
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import random_split
from torch.nn import functional as F
import torchvision
from torchvision import datasets, transforms
import torchvision.transforms as transforms
import optuna
import os

DEVICE = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
CLASSES = 2
DIR = os.getcwd()
EPOCHS = 10

import torch
from torch import nn 
from torch.utils.data import DataLoader, TensorDataset
MHC_Pep = torch.FloatTensor(MHC_P)        
labels = torch.LongTensor(labels) 
train_dataset = TensorDataset(MHC_Pep,labels)
m = len(train_dataset)
transform = torchvision.transforms.Compose([torchvision.transforms.ToTensor()])
train_dataset.transform=transform

import torch
from torch import nn 
class RNN(nn.Module):
  def __init__(self, input_size, hidden_size, num_layers, num_classes):
    super(RNN, self).__init__()
    self.num_layers = num_layers
    self.hidden_size = hidden_size
    self.rnn = nn.RNN(input_size,hidden_size,num_layers,batch_first = True)
    self.fc = nn.Linear(hidden_size, num_classes) 

  
  def forward(self, x):
    h0 = torch.zeros(self.num_layers, x.size(0), self.hidden_size).to(device)
    out, _ = self.rnn(x, h0)   #x is input
    out = out[:,-1,:] 
    out = self.fc(out)
    return out


def get_data(train_dataset, batch_size):
  train_data, val_data = random_split(train_dataset, [int(m-m*0.2), int(m*0.2)]) 
  train_loader = torch.utils.data.DataLoader(train_data, batch_size= batch_size,shuffle=True)
  valid_loader = torch.utils.data.DataLoader(val_data, batch_size= batch_size)
  return train_loader, valid_loader


def objective(trial):
  model = RNN(input_size=24, hidden_size=2, num_layers=2, num_classes=2).to(DEVICE)
  optimizer_name = trial.suggest_categorical('optimizer',['RMSprop','SGD'])
  momentum    = trial.suggest_float('momentum',0.0,1.0)
  lr       = trial.suggest_float('lr',1e-5,1e-1,log=True)
  optimizer    =  getattr(optim, optimizer_name)(model.parameters(),lr=lr, momentum=momentum)


  optimizer_name = trial.suggest_categorical('optimizer',['Adam','Adadelta','Adagrad'])
  lr       = trial.suggest_float('lr',1e-5,1e-1,log=True)
  optimizer    =  getattr(optim, optimizer_name)(model.parameters(),lr=lr)
  batch_size   = trial.suggest_int('batch_size',64,256,steo=64)

  criterion=nn.CrossEntropyLoss()

  train_loader, valid_loader = get_data(train_dataset, batch_size)

  for epoch in range(EPOCHS):
    model.train()
    
    for batch_idx,(MHC_Pep,labels) in enumerate(train_loader):
      MHC_Pep,labels = MHC_Pep.to(DEVICE),labels.to(DEVICE)

      optimizer.zero_grad()

      output = model(MHC_Pep)

      loss = criterion(output, labels)

      loss.backward()

      optimizer.step()

    #Validation of the model.

    model.eval()
    correct = 0
    with torch.no_grad():
      for batch_idx,(MHC_Pep,labels) in enumerate(valid_loader):
        MHC_Pep,labels = MHC_Pep.to(DEVICE),labels.to(DEVICE)
        output = model(MHC_Pep)
        pred = output.argmax(dim=1, keepdim=True)

        correct += pred.eq(labels.view_as(pred)).sum().item()

    accuracy = correct/ len(valid_loader.dataset)

    trial.report(accuracy, epoch)

    if trial.should_prune():
      raise optuna.exceptions.TrialPrund()

  return accuracy

Part2:   
study = optuna.create_study(direction = 'maximize')
study.optimize(objective, n_trials= 20)

trial = study.best_trial
print('Accuracy: {}'.format(trial.value))
print('Best hyperparameters:{}'.format(trial.params))


I think the problem because of  the function " objective", "trial.suggest_categorical". But i do not know excatelly which part.




Part 3 :  Value Error

[I 2022-05-06 09:44:30,475] A new study created in memory with name: no-name-e710890d-1307-46ed-bb89-43036a46df6b
[W 2022-05-06 09:44:30,496] Trial 0 failed because of the following error: ValueError('CategoricalDistribution does not support dynamic value space.')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/optuna/study/_optimize.py", line 213, in _run_trial
    value_or_values = func(trial)
  File "<ipython-input-18-bed17b4e01de>", line 19, in objective
    optimizer_name = trial.suggest_categorical('optimizer',['Adam','Adadelta','Adagrad'])
  File "/usr/local/lib/python3.7/dist-packages/optuna/trial/_trial.py", line 505, in suggest_categorical
    return self._suggest(name, CategoricalDistribution(choices=choices))
  File "/usr/local/lib/python3.7/dist-packages/optuna/trial/_trial.py", line 708, in _suggest
    distributions.check_distribution_compatibility(trial.distributions[name], distribution)
  File "/usr/local/lib/python3.7/dist-packages/optuna/distributions.py", line 531, in check_distribution_compatibility
    CategoricalDistribution.__name__ + " does not support dynamic value space."
ValueError: CategoricalDistribution does not support dynamic value space.
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[<ipython-input-19-8a7cd3cae88f>](https://localhost:8080/#) in <module>()
      1 study = optuna.create_study(direction = 'maximize')
----> 2 study.optimize(objective, n_trials= 20)
      3 
      4 trial = study.best_trial
      5 print('Accuracy: {}'.format(trial.value))


ValueError: CategoricalDistribution does not support dynamic value space.



Please help me, i got serious depress. Because if i can not finish this project, i can not graduate my Ph.D.
I can pay for person who solve this problem.

**Comment by crownwang301** [comment]
perfect!!!!!!! you are my hero!!!!!!!
Unfortunatelly, i have another problem.

Pert 1 : IndexError
[I 2022-05-06 13:02:43,502] A new study created in memory with name:
no-name-022ced11-adf8-47b7-a8af-680500243f22
[W 2022-05-06 13:02:43,553] Trial 0 failed because of the following error:
IndexError('Target 20000 is out of bounds.')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/optuna/study/_optimize.py",
line 213, in _run_trial
    value_or_values = func(trial)
  File "<ipython-input-50-f1cf6bf87490>", line 48, in objective
    loss = criterion(output, labels)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py",
line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/loss.py",
line 1165, in forward
    label_smoothing=self.label_smoothing)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/functional.py",
line 2996, in cross_entropy
    return torch._C._nn.cross_entropy_loss(input, target, weight,
_Reduction.get_enum(reduction), ignore_index, label_smoothing)
IndexError: Target 20000 is out of bounds.


Part2: I am using RNN+Pytorch+Optuna.   2 classification(0 or 1).
MHC_Pep = torch.FloatTensor(MHC_P)       # This is my features.
 torch.Size([121950, 43, 24])
labels = torch.LongTensor(labels)                #This is my labels.
 torch.Size([121950])
train_dataset = TensorDataset(MHC_Pep,labels)

criterion=nn.CrossEntropyLoss()

I think the problem roughly around this part, but i am so stupid, i do not
know how to solve this problem.

Thank you and have a nice weekend.

Best regards,
Zhengguan Wang(a Chinese depressed Ph.D. student in Germany)

Naoto Mizuno ***@***.***> 于2022年5月6日周五 13:06写道：
