### ISSUE TITLE
Should generics be used for `suggest_categorical` return type?

### ISSUE THREAD

**Issue by harupy** [optuna/optuna#1753]
## Note to the questioner

The return type of `suggest_categorical` is a union of `[None, bool, int, float, str]`, but I think it should be inferred from a given choices in a generic way.

```python
import optuna

def objective(trial: optuna.Trial):
    x = trial.suggest_categorical("x", [-1, 0, 1])  # integer choices
    reveal_type(x)  # should be int but [None, bool, int, float, str]
    return 0
```

[Stack Overflow]: https://stackoverflow.com/questions/tagged/optuna
[optuna/optuna chat]: https://gitter.im/optuna/optuna

**Comment by MarioIshac** [comment]
Currently `suggest_categorical` is declared like this:

```
def suggest_categorical(
    self, name: str, choices: Sequence[CategoricalChoiceType]
) -> CategoricalChoiceType:
```

with `CategoricalChoiceType = Union[None, bool, int, float, str]`


Note that selecting from heterogeneous items is supported, for example looking in `test_samplers.py` I see this:

```
CategoricalDistribution((1, "a"))
```

Assigning `CategoricalChoiceTypeTypeVar` to `TypeVar("CategoricalChoiceType", None, bool, int, float, str)` would break scenarios like the above test case. Ideally we could do `TypeVar("CategoricalChoiceType", Union[None, bool, int, float, str], None, bool, int, float, str)` so we fallback to the `Union` if selecting from heterogeneous items and otherwise choose their homogeneous type, but the bounds of a `TypeVar` cannot be parametrized like that, and I think we would have to use `object` instead.

We may be able to support your example and heterogeneous collection at the same time using `@overload` from `typing`.
