### ISSUE TITLE
Dask / Optuna Integration

### ISSUE THREAD

**Issue by mrocklin** [optuna/optuna#1766]
Hello Optuna maintainers, 

I work on Dask and I would like to improve integration between Optuna and Dask.  I did a brief investigation a couple of days ago (see https://github.com/dask/dask/issues/6571) and now have some questions.  Hopefully this is a good place to post questions:

## Nice design

First, (not actually a question) Optuna's distribution system seems really simple.  Thank you for the thoughtful design.  

## Storage

Second, I'm curious about the storage backend.  It looks like I can call `optuna.Study.optimize` with the same function in many places and if all of those places point to the same storage then everything will work smoothly.  Great.  If the user has a redis or relational database that is globally accessible then I think that there is no more work to do, other than maybe some documentation or examples.

However, I think that for many data science users setting up a relational database that is visible from every node in a cluster might be difficult.  I think that it would be useful to create an equivalent of the local in-memory storage that worked across a Dask cluster.   We can do this on the Dask side easily, but I have a couple of questions  that might influence the design.

1.  How fast should this be?  Is a 5ms response time fast enough, or should this be closer to 500us?
2.  I think that this will receive one query and one insert per trial.  Is that correct?  Those queries are for the full history of hyperparameters and scores so far?

### Testing

Also, I'm curious about registering external storages with Optuna. If I make a Dask storage for Optuna I would like to also use the test suite in `tests/storages_tests/test_storages.py`.  We have a few options here:

1.  We make a new dask-optuna package and copy-paste Optuna's test suite into that package
2.  We convert Optuna's test suite into a `unittest.TestSuite` class that we can then import in the dask-optuna package (this is nicer because `dask-optuna` tracks changes in `optuna`).
3.  We build the Dask storage within the Optuna codebase and add the Dask storage to the list of storages to test if Dask is installed

Some of these changes affect the optuna codebase.  Generally, the question here is if you want Dask modules inside github.com/optuna/optuna

## Joblib

I tried wrapping `study.optimize` in a `joblib.parallel_backend("dask")` context manager and was surprised that Dask did not take over from the joblib threading backend.  I'm not yet sure why.  If anyone has any thoughts here I welcome them.

## Is there anything else?

Other than Storage, is there anything else that we should consider?

I do not have practical experience with Optuna.  Is this useful?

Thank you for your time

**Comment by ytsmiling** [comment]
Optuna-dask integration sounds really nice. And I'm looking forward to trying it.

Though I'm not a core-committer of optuna, let me leave some comments on storage issues. (I hope core-committers will answer other questions and also provide complementary information for my answer.)

> 1. How fast should this be?

To my understanding, a core target of optuna is (was) heavy objectives (e.g., deep learning), and there are no strong requirements for the latency. At least, I think that there is no consensus on latency requirements among committers. However, applications of optuna is expanding, and there are certain demands for fast optimization, and faster is definitely better.

> 2.I think that this will receive one query and one insert per trial. Is that correct? Those queries are for the full history of hyperparameters and scores so far?

Unfortunately, things are a bit more complicated, and storage and workers need to communicate more frequently. This is mostly due to a pruning feature and a dashboard feature.
**Read operations:**
A trial read history once or more. The first read is performed at the very beginning of the trial's life span. The information will be used to suggest the next parameters. The optional second read is performed at the beginning of a pruning phase. The second read is necessary to use the latest states of other running/completed trials to determine whether the trial should be pruned or not.
**Write operations:**
Trials insert intermediate results to storages every time users call the `report` method. This will let users check the progress of long-running trials. I forgot why but trials also write other attributes to storage immediately (e.g., trial.set_system_attr). I at least remember that my past attempt to stop the write-through behavior was unsuccessful. (But I personally think that disabling some of the features in dask-optuna is a good option.)

**Comment by mrocklin** [comment]
> Unfortunately, things are a bit more complicated, and storage and workers need to communicate more frequently. 

This is fine.  The Dask scheduler and comms are built to handle many small messages, but this means that I'll probably want to be careful about which read/write operations need to finish before they return, and which can be sent off asynchronously.  I see that there are some notes in `storages/_base.py`.  I think that we'll just have to pay attention to those.

**Comment by jrbourbeau** [comment]
Thanks for raising this issue @mrocklin! I'm also interested in improving Optuna + Dask integration

> I tried wrapping study.optimize in a joblib.parallel_backend("dask") context manager and was surprised that Dask did not take over from the joblib threading backend

There are separate code paths for `n_jobs == 1` (default) and `n_jobs != 1`

https://github.com/optuna/optuna/blob/aa505125de8515518fe19ba227edf7a1d3f8ebda/optuna/study.py#L299-L303

Using `n_jobs != 1` will go down the code path that uses `joblib` (snippet below)

<details>
<summary>Example snippet with joblib:</summary>

```python

# First run:
# $ optuna create-study --study-name "distributed-example" --storage "sqlite:///example.db"
# in the command line

import optuna
import joblib
from dask.distributed import Client

def objective(trial):
    x = trial.suggest_uniform('x', -10, 10)
    return (x - 2) ** 2

if __name__ == "__main__":
    with Client(n_workers=4, processes=False) as client:
        with joblib.parallel_backend("dask"):
            study = optuna.load_study(study_name='distributed-example', storage='sqlite:///example.db')
            study.optimize(objective, n_trials=100, n_jobs=-1)
```

</details>

**Comment by toshihikoyanase** [comment]
@mrocklin Dask / Optuna integration sounds great! I'm excited to see this issue and https://github.com/dask/dask/issues/6571.

@jrbourbeau Thank you for sharing your solution. 

Sorry if I missed the point, but I'm still wondering why we cannot switch the `joblib` backend with `n_jobs!=1`. https://github.com/optuna/optuna/pull/692#issuecomment-554568441 suggested that we can do it and I think I could reproduce it with this [notebook](https://colab.research.google.com/drive/1WQ8CZfPxk6b48hPMAO_BqBq4bg6Lsms8?usp=sharing). I found that it failed if we set `processes=True` to the argument of `Client.__init__` and I guess the current implementation has a problem of pickling.

<details>
<summary>An example with `n_jobs=-1`</summary>

```python
from distributed import Client
import joblib
import optuna

def objective(trial):
    return trial.suggest_uniform("x", 0, 1)

if __name__ == "__main__":
    study = optuna.create_study(storage='sqlite:///example1.db')

   with Client(n_workers=2, processes=False) as client:
        with joblib.parallel_backend("dask"):
            study.optimize(objective, n_trials=20, n_jobs=-1)

    print(study.trials)
```
</details>

**Comment by mrocklin** [comment]
@toshihikoyanase when I try your example with `processes=True` I get the following traceback:

```python-traceback
Traceback (most recent call last):
  File "/home/mrocklin/miniconda/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 693, in _finalize_fairy
    fairy._reset(pool)
  File "/home/mrocklin/miniconda/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 880, in _reset
    pool._dialect.do_rollback(self)
  File "/home/mrocklin/miniconda/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 540, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140687307011904 and this is thread id 140687178475264.
```

I think that what happens here is that we deserialize the sqlite object in one thread, and then use it in another thread.  Dask uses one dedicated thread for communication, and other threads for computation.  Sometimes this can cause trouble if libraries are not thread-safe.

SQLite is not so good at multi-threaded behavior.  I would expect more robust databases like PostgreSQL or MySQL to perform better.  However, sqlalchemy may also have issues.  I am not sure.

**Comment by jrbourbeau** [comment]
>  I think that it would be useful to create an equivalent of the local in-memory storage that worked across a Dask cluster

I agree that users may find an dask-compatible in-memory storage class useful. I'm working on implementing a store class as outlined over in https://github.com/dask/dask/issues/6571#issuecomment-684979667

**Comment by toshihikoyanase** [comment]
Sorry for the delayed response.

@mrocklin 

> Dask uses one dedicated thread for communication, and other threads for computation. Sometimes this can cause trouble if libraries are not thread-safe.

> sqlalchemy may also have issues.

Thank you for your kind explanation. Now I understand the issue and your motivation for the new storage better.

@jrbourbeau 

> I'm working on implementing a store class as outlined over in dask/dask#6571 (comment)

That's great 👍 
 I'm looking forward to your implementation.

**Comment by jrbourbeau** [comment]
I've put together a [`dask-optuna` package](https://github.com/jrbourbeau/dask-optuna) which has a Dask-compatible `DaskStorage` class that implements Optuna's `BaseStorage` API (roughly as outlined in https://github.com/dask/dask/issues/6571#issuecomment-684979667). The `DaskStorage` class works well with Optuna's existing Joblib internals, so it can be used directly with Optuna's API.

For example:

```python
import optuna
import joblib
from dask.distributed import Client
import dask_optuna

def objective(trial):
    x = trial.suggest_uniform("x", -10, 10)
    return (x - 2) ** 2

with Client() as client:
    print(f"Dask dashboard is available at {client.dashboard_link}")
    dask_storage = dask_optuna.DaskStorage("sqlite:///example.db")
    study = optuna.create_study(storage=dask_storage)
    with joblib.parallel_backend("dask"):
        study.optimize(objective, n_trials=200, n_jobs=-1)
    print(f"best_params = {study.best_params}")
```

I hope this is useful for current Optuna + Dask users and any feedback is very welcome! Here are some relevant links for Dask-Optuna:

GitHub repo: https://github.com/jrbourbeau/dask-optuna
Documentation: https://jrbourbeau.github.io/dask-optuna

cc @toshihikoyanase  @ytsmiling  and anyone else who may be interested

**Comment by hvy** [comment]
Thanks you for the interesting discussion and sorry for joining it late. I tried to catch up going through the threads and running some examples using `dask-optuna`.

With `dask-optuna`, is my understanding correct that the client/scheduler does of some sort of locking/coordination on top of the existing storages in Optuna? Although it adds a layer of complexity, it seems like a quick way to support distributed optimization with the in-memory storage. I was also a bit curious how a user would use `dask-optuna` on say a cluster, rather than on the local machine. Would he/she still have to setup a database as with regular Optuna, or is this made easier with `dask-optuna`? My experience with `dask` is very limited so I am sorry if I’d be missing on some very basic points. 

Given that, `dask-optuna` looks like a reasonable first approach. The logic is clearly isolated and instead introducing `dask` into `optuna` directly seems non-trivial given e.g. how users must manage the `Client`.  Thanks @jrbourbeau for the quick implementation and I'm looking forward to this integration.

**Comment by hvy** [comment]
Just a note on the dependency of `joblib`. There are some ongoing discussions whether `joblib` should be kept within Optuna or maybe moved out. In the latter case, `joblib` would no longer be a dependency and users would be free to parallelize the trials in user code, but no longer by relying on `n_jobs` in `Study.optimize`. I guess this discussion is relevant to `dask-optuna`, and we might want to keep `joblib` for this purpose?

**Comment by jrbourbeau** [comment]
Thanks for the feedback @hvy! 

> With dask-optuna, is my understanding correct that the client/scheduler does of some sort of locking/coordination on top of the existing storages in Optuna?

That's correct! `dask-optuna` creates a single Optuna storage class on the Dask scheduler process. The Dask client and scheduler then coordinate with each other to dispatch method calls on the `dask-optuna` storage class to the underlying Optuna storage class on the scheduler:

```python
# Creates an Optuna InMemoryStorage instance on the Dask scheduler
storage = dask_optuna.DaskStorage()

# Sends a message to the scheduler to call `create_new_study(...)` on the underlying InMemoryStorage
storage.create_new_study(...)
```

>  Would he/she still have to setup a database as with regular Optuna, or is this made easier with dask-optuna?

A database still needs to be created, but setup is generally easier with `dask-optuna` because the database only needs to be available on the scheduler process. Without `dask-optuna` users need to setup a database that is accessible to the scheduler _and_ to all the Dask workers in the cluster. This is doable, but can be difficult when the scheduler and workers don't have access to the same filesystem.

As an example, this script (https://github.com/jrbourbeau/dask-optuna/blob/master/examples/xgboost-coiled.py) creates a remote Dask cluster on AWS using [Coiled](https://coiled.io/) and then uses Optuna + `dask-optuna` to do an optimization. If that example used just Optuna's built in SQLite DB storage, instead of using `dask-optuna` to wrap the SQLite storage, then one would get error along the lines of `"Can't find SQLite database sqlite:///..."` on the Dask workers because the database wouldn't be globally available. 

> There are some ongoing discussions whether joblib should be kept within Optuna or maybe moved out

Thanks for pointing that out, that's good to know! Is there an issue or public forum where this is being discussed? Searching through the issue tracker, I didn't see such an issue but I very well could have missed something

From the `dask-optuna` side, whether `joblib` stays in Optuna or is moved out shouldn't matter. Previously, there was a `dask_optuna.optimize` function (it was removed [here](https://github.com/jrbourbeau/dask-optuna/pull/11)) which handled submitting Optuna trials to the Dask cluster independent of `joblib`. We can add that function back to `dask-optuna` if needed, so I wouldn't worry about keeping `joblib` in Optuna on behalf of `dask-optuna`

**Comment by mrocklin** [comment]
>> Would he/she still have to setup a database as with regular Optuna, or is this made easier with dask-optuna?

> A database still needs to be created, but setup is generally easier with dask-optuna because the database only needs to be available on the scheduler process

To clarify, the `DaskStorage` consumes a normal optuna `Storage`, but provides distributed workers fast access to that storage.  This could be a storage backed by a database, or it could be an in-memory storage.

Users without a database should be able to use dask-optuna without any additional setup.  Taking an example from @jrbourbeau 's comment above, 

```python
# Creates an Optuna InMemoryStorage instance on the Dask scheduler
storage = dask_optuna.DaskStorage()
```

**Comment by mrocklin** [comment]
> From the dask-optuna side, whether joblib stays in Optuna or is moved out shouldn't matter. Previously, there was a dask_optuna.optimize function (it was removed here) which handled submitting Optuna trials to the Dask cluster independent of joblib. We can add that function back to dask-optuna if needed, so I wouldn't worry about keeping joblib in Optuna on behalf of dask-optuna

+1  

I wouldn't keep joblib in optuna because of Dask-Optuna.  I estimate that replacing the joblib functionality with raw Dask would take only a few hours.

**Comment by hvy** [comment]
Thanks for elaborating on the mechanism behind `dask-optuna` works and the input that we can discuss the `joblib` dependency orthogonally to this. I agree. It's also good to know that you've already implemented a `dask_optuna.optimize`. The logic was by the way quite similar to what I was expecting, running a single trial per job. 

>> There are some ongoing discussions whether joblib should be kept within Optuna or maybe moved out

> Thanks for pointing that out, that's good to know! Is there an issue or public forum where this is being discussed? Searching through the issue tracker, I didn't see such an issue but I very well could have missed something

There are no issues or public forums addressing this, but some related ones include https://github.com/optuna/optuna/issues/1232 and https://github.com/optuna/optuna/issues/1480. 

Just to recap on the history to the best of my knowledge, the `n_jobs` argument was introduced to allow multi-threading with `ThreadPool` in https://github.com/optuna/optuna/pull/13. Then, `joblib` replaced `ThreadPool` in https://github.com/optuna/optuna/pull/692. Since then, `n_jobs` became sort of an experimental feature as the feature set was expanded to different backends (such as multi-processing) but with limited support ([multi-processing does not work with in-memory storage](https://github.com/optuna/optuna/blob/master/optuna/study.py#L355-L364)). If #1232 is accepted, `joblib` could perhaps be removed. For now at least, I believe the interface can be kept simple, without `dask_optuna.optimize`.

**Comment by jrbourbeau** [comment]
The Optuna + Dask integration over in https://github.com/jrbourbeau/dask-optuna has been working well for a couple of months now. Based on engagement with [this tweet](https://twitter.com/__jrbourbeau__/status/1304472397878374401) and on the `dask-optuna` repository, there seems to be interest in using Dask and Optuna together. Would the Optuna developers be open to including `dask-optuna`'s functionality directly in Optuna?

This would involve adding the [`DaskStorage` storage class](https://github.com/jrbourbeau/dask-optuna/blob/9cc8e55cb37d211feedb2244f82bff11f33a5ca2/dask_optuna/storage.py#L292), including `DaskStorage` in the test suite, and documenting how to use `DaskStorage`. I'm happy to open a PR which does this and to help maintain the Optuna + Dask integration moving forward, but first wanted to check in to see if this is something the Optuna community is interested in.

**Comment by pseudotensor** [comment]
Amazing work, thank you @jrbourbeau .  Do you expect any limitations?  It seems to work on single node case, will test multinode soon.

**Comment by jrbourbeau** [comment]
Thanks @pseudotensor! You should be able to use any Optuna storage class within `DaskStorage` and it's multi-node safe

**Comment by hvy** [comment]
Great to hear that it's been working well. And, thanks @jrbourbeau for your kind suggestion.

Including the `DaskStorage` (perhaps along with optional dependencies) in Optuna is definitely one way. That'd make it easy for existing Optuna users to try it out which would be great. A slight concern that I currently see with that is that that we don't have a lot of experience with Dask or `dask-optuna`. What kinds of advantages do you see in placing this in the `optuna` repository over the `dask` organization? I imagine that this feature would be opted-in by users somewhat familiar with Dask (since users will interact with other APIs of Dask when using this storage), I'm wondering if the `dask` organization isn't more straight forward.
In any case, looking forward to make it more collaborative. I hope we can start promoting it soon to have it mature. I'm just a bit worried that including this in Optuna right now might be rushed. Let me know what you think.

**Comment by jrbourbeau** [comment]
> we don't have a lot of experience with Dask or dask-optuna

That’s a totally understandable reason to not include Dask-Optuna’s functionality right away. I’m certainly not trying to add more of a maintenance burden for Optuna developers. I’m happy to be around to help maintain Optuna’s Dask integration, but understand if you’d like more Optuna developers to be familiar with Dask before including it directly

> What kinds of advantages do you see in placing this in the optuna repository over the dask organization?

A few of things that come to mind are:

1. Visibility. Optuna users are more likely to discover that Optuna integrates with Dask if they see it in the Optuna documentation and can try it out easily.
2. Having Optuna and its Dask integration live in the same repository makes co-development a bit easier. When, for example, a change that would break `DaskStorage` is introduced, it’s known about immediately through a test failure. 
3. `DaskStorage` allows Optuna to support [users who want to run trials in parallel across multiple processes](https://github.com/optuna/optuna/issues/1480), instead of across multiple threads. Though multiprocess support [might be coming to Optuna anyways](https://github.com/optuna/optuna/issues/1170), so this may only be a temporary advantage of adding `DaskStorage`.

These types of advantages have come up with other Dask subprojects. For example, XGBoost and LightGBM are absorbing the functionality of `dask-xgboost` and `dask-lightgbm` (see https://github.com/dask/community/issues/104 for a related discussion). 

A few other possible options that come to mind are to:

1. Add Dask support on an experimental basis using the [`experimental` decorator](https://github.com/optuna/optuna/blob/9b0081a212cba04e97a28ca510e5e72559b01a0d/optuna/_experimental.py#L34). This could be a nice way to ease into including Dask support. 
2. Add information on using Optuna and Dask (still using a separate `dask-optuna` package) to Optuna's documentation. This would improve visibility of scaling Optuna with Dask
3. Don't do anything. We can always integrate things together later if there's more interest in the future.

**Comment by pseudotensor** [comment]
I agree with @jrbourbeau .  Basically, it's ok to have a separate package at first, but once stability is reached and isolation can be obtained, then it's good to become part of Optuna.  optuna-dask is a new project, but if it's contained and small perhaps it's already ready for integration.  A PR at least would be interesting.

E.g. xgboost does not need dask to run, but if dask is installed they check packages to see (doing import test is bad idea since would import dask in global space where one might not want it, and they fixed that recently).  If one has dask, some other classes will work that are dask specific.

I actually don't like how xgboost has separate API for dask, which has led to divergences in capabilities.  I think it's better to have API uniform and ignorant of dask and dask just becomes an option as part of normal API.

@jrbourbeau  Good to hear lightgbm is also integrating the dask-lightgbm like xgboost did.

**Comment by hvy** [comment]
Thanks @jrbourbeau for clarifying and @pseudotensor for your inputs!

I was going through my previous comment thinking it sounded rather skeptical. I just discussed this with some of the other developers and we’re quite happy to work towards placing this in the optuna repository. I agree with your benefits and we haven’t been able to support multiprocessing with the `InMemoryStorage` for quite a while so that alone is actually quite a big driver (for us to maintain with backup from Dask). I also guess that this will be a good opportunity for the Optuna developers to get more familiar with dask. Would you like to work on a first PR based on dask-optuna?

As for how, a `optuna.integration.DaskStorage` (optuna/integration/dask.py) with the experimental decorator might be a good start. I’m thinking if we could in a follow up introduce a `class DaskStudy(Study)` that overrides `Study.optimize` with the implementation that you previously provided. I think this’ll make for a better user experience, hiding away (not relying on) joblib. This `DaskStudy` would take a regular storage and wrap it in `DaskStorage` internally. 

> I actually don't like how xgboost has separate API for dask, which has led to divergences in capabilities. I think it's better to have API uniform and ignorant of dask and dask just becomes an option as part of normal API.

This is a very valid point. For the time being, however, I think introducing Dask with optional dependencies with a separated API is safer, taking into account existing users who rely on the current behavior of `n_jobs` with `joblib`. If you have concrete ideas for how to design the APIs, I’d be very interested.

**Comment by jrbourbeau** [comment]
Great! Glad to hear there's interest from the group

> Would you like to work on a first PR based on dask-optuna?

Yeah, I'm happy to engage in development here. I'll start with adding a `optuna.integration.DaskStorage` and then we can work toward adding a `DaskStudy` as you suggested.

**Comment by mrocklin** [comment]
If we're going to implement a DaskStudy then I would encourage us to use
native Dask UIs in that class, rather than Joblib, which can sometimes
cause trouble.

**Comment by jrbourbeau** [comment]
+1 this would be similar to the `dask_optuna.optimize` function we had before

**Comment by hvy** [comment]
+1, sounds good to me.

**Comment by HideakiImamura** [comment]
@mrocklin @jrbourbeau [Just FYI] Optuna does not use `joblib` internally from #2269, so it is reasonable to use native Dask UIs when we implement `DaskStudy.optimize`.

**Comment by jrbourbeau** [comment]
Noting that the PR for this issue (https://github.com/optuna/optuna/pull/2023) was recently re-opened and updated
