### ISSUE TITLE
Add new hyperparameter with default value.

### ISSUE THREAD

**Issue by PhilipMay** [optuna/optuna#1855]
## Motivation
If I start a model hyperparameter search with optuna I optimize lets say 4 different hyperparameters. But some other hyperparameters are fixed in my code. Lets say number of epochs is fixed at 5. Now after many trials I want to add
number of epochs to my searchspace. 

When I add `number of epochs` to optuna the "old" and stored trials are set to `NaN` in the optuna DB. It would be good to set all of them to 5 since the "old" trials always had it at 5 (hard coded).

## Description
Insetad of saying `epochs = trial.suggest_int('epochs', 3, 10)` I would like to say `epochs = trial.suggest_int('epochs', 3, 10, default_init=5)` or something like that. So optuna adds a new col. to the stored trials and initializes it with `default_init=5` instead of `NaN`.

What do you think? I often have this situation where I would like to add one more hyperparameter and already have many trials...

**Comment by hvy** [comment]
I assume that you are talking about the constructed study dataframe. As for the RDB storage, there are no real columns introduced per parameter. Each suggested parameter is stored as a row, and this data is then aggregated when constructing the dataframe. Since you mention that this is quite common however, I believe we can discuss the API as well. I for instance wonder how this would propagate to conditional parameters where parameters were intentionally skipped by the users. These skipped parameters don't affect the objective value but would be treated as if they were suggested.

If you can separate the calls to `Study.optimize`, I believe you could do something like the following using `Study.add_trial` https://colab.research.google.com/drive/1UYp_LDlyv_i5FG8FCha9bJfyux8jWiIN#scrollTo=Do8dOHBYXcE_ Although it is quite verbose and low level, it might address the problem.

**Comment by PhilipMay** [comment]
Yes - thanks for the code. You basicaly just create a new study and copy the old trials into that study with the new infos about params and distribution. That is a workaround that fits my needs. Although I would be happy if you could think about a way to integrate it into the Optuna API.

Thanks, Philip

**Comment by hvy** [comment]
Nice to hear it worked. As for introducing new APIs, it sounds like a quite significant change to the core interface for limited use cases. I'd be good if we could get more feedback on this feature request before proceeding, maybe references to other frameworks would help as well.

**Comment by hvy** [comment]
Let me close this ticket for now since it has been stale for a while. Let's discuss this feature further if more users have additional arguments for going forward with it.

**Comment by Divide-By-0** [comment]
It would be great to set default hyperparameters, with the behavior as such: at the start of an empty study it runs a trial with those hyperparams which I know are pretty good, and then searches knowing theres a pretty decent local minimum there. Would that even help the Optuna algorithm?

**Comment by nzw0301** [comment]
How about https://optuna.readthedocs.io/en/stable/reference/samplers/generated/optuna.samplers.PartialFixedSampler.html?
