### ISSUE TITLE
Reason behinds LightGBMTuner optimized parameters

### ISSUE THREAD

**Issue by natthawute** [optuna/optuna#1872]
Hi,

From the [API Document](https://optuna.readthedocs.io/en/stable/reference/generated/optuna.integration.lightgbm.LightGBMTuner.html#optuna.integration.lightgbm.LightGBMTuner), it seems that LightGBMTuner optimizes only 7 parameters (lambda_l1, lambda_l2, num_leaves, feature_fraction, bagging_fraction, bagging_freq and min_child_samples).

I have the following questions.
1. Is there any reason why these 7 parameters were selected? or why other parameters were not selected? 
2. How did Optuna choose a range of parameter to optimized? Was it based on a paper? Or Optuna recommend that range when performing optimization?
3. Is the LightGBMTuner meant to replace the naive approach (write objective function)? or just a way to quickly get the result? If I want the best performance possible, which approach is recommended?

Best Regards,

**Comment by toshihikoyanase** [comment]
Hi @natthawute ,
Thank you for your questions.

Regarding the first and second questions, I've heard that the parameters and their ranges were selected based on the experiment in the [blog post](https://medium.com/optuna/lightgbm-tuner-new-optuna-integration-for-hyperparameter-optimization-8b7095e99258) written by @smly.

About the third question, I think that depends on the problems. As can be seen in the blog post, `LightGBMTuner` shows better performance in some problems including Kaggle BNP Paribas and OpenML Bank than Optuna's default sampler, but it also shows worse performance in Kaggle springleaf and OpenML Mozilla4.
I think we can try `LightGBMTuner` first because it can be used ad a drop-in replacement for the LightGBM 's train function, and we can write our own objective functions if we need further performance improvement.

**Comment by natthawute** [comment]
Hi @toshihikoyanase ,
Thank you for your response.
I have some follow up questions.

1. Is there anyway to use customized objective functions with step wise algorithm? From what I understand, if I write my own objective functions and call `study.optimize` Optuna will use the old algorithm right?
2. When using LightGBMTuner, In what situation would I want to set `optuna_callbacks`.  I'm new to this and still don't understand what it does.

Regards,

**Comment by toshihikoyanase** [comment]
> 1. Is there anyway to use customized objective functions with step wise algorithm?

Currently, Optuna does not provide customizable stepwise algorithms. We discussed such a feature in #1632, so please join the conversation if you are interested.

> 2. When using LightGBMTuner, In what situation would I want to set `optuna_callbacks`.

`optuna_callbacks` was originally introduced to send optimization results to MLFlow in #1158. For further details, please take a look at the PR.

**Comment by natthawute** [comment]
Thank you very much for your kind responses. :)
