### ISSUE TITLE
Proposal to add optuna example for materials science

### ISSUE THREAD

**Issue by resnant** [optuna/optuna#1877]
## Motivation
I am working on ML application in materials science and recently published a paper which utilize Optuna as a black-box problem solver:
Automated crystal structure analysis based on blackbox optimisation
https://www.nature.com/articles/s41524-020-0330-9

I think it is interesting if a non-ML example is added to Optuna example because it will demonstrate the capability of Optuna for various problems.

## Description
If you are interested in this proposal, I will prepare an example notebook (.ipynb) based on our existing code and send a pull request.
Our repo is here:
https://github.com/quantumbeam/BBO-Rietveld
https://github.com/quantumbeam/BBO-Rietveld/blob/master/1_Y2O3.ipynb

Probably, I should add some comments to make it easy to understand for non-specialists.

## Appendix
Commentary articles on this paper (Japanese)
https://academist-cf.com/journal/?p=13774

**Comment by HideakiImamura** [comment]
Thanks for the interesting proposal! The example notebook looks very impressive to me. I'm so excited to connect this example with Optuna. My first impression is that it would be a good idea to put a link to GitHub of the material science project in `optuna/example/README.md` under "External projects using Optuna". The reason is that the review to merge this material science example into Optuna is too costly and it is difficult for Optuna core-dev members to maintain the material science project. What do you think?

**Comment by resnant** [comment]
Thank you for your positive response and giving us an opportunity to connect our example to Optuna. 
I agree with your suggestion:

> it would be a good idea to put a link to GitHub of the material science project in optuna/example/README.md under "External projects using Optuna".

I will edit the README and send a pull request.
