### ISSUE TITLE
Disabling the logging handler continue to print certain messages

### ISSUE THREAD

**Issue by nsinenian** [optuna/optuna#2001]
Calling `optuna.logging.disable_default_handler()` or otherwise setting the verbosity level (either, or both) suppresses most log output messages, except for pruning messages, which are still printed to screen:

"Engine run is terminating due to exception: Trial was pruned at 1 epoch.."

## Expected behavior

I expect that disabling the logging handler for optuna would also suppress messages with respect to pruning.

## Environment

- Optuna version: 2.2.0
- Python version: 3.8.1
- OS: macOS Catalina (10.15.6)
- (Optional) Other libraries and their versions: PyTorch (1.6.0)

## Steps to reproduce

1. Define an objective function `objective`
2. Run a trial with a pruner

## Reproducible examples (optional)

```
optuna.logging.disable_default_handler()
study = optuna.create_study(direction="maximize",pruner=optuna.pruners.optuna.pruners.SuccessiveHalvingPruner())
study.optimize(objective,n_trials=trials,timeout=timeout)
```

**Comment by HideakiImamura** [comment]
Hi @nsinenian! Thanks for the question.

At the first glance, the message "Engine run is terminating due to exception: Trial was pruned at 1 epoch.." seems not be generated by Optuna. I think "Engine run is terminating due to exception: " is generated from another library, such as PyTorch or lightning. Could you give me some self-contained reproducible examples?
