### ISSUE TITLE
Multiple objectives

### ISSUE THREAD

**Issue by ochipara** [optuna/optuna#2047]
Hi,

I am looking to use different objective functions to evaluate a model. Is there a way to track multiple objectives and select one of them as the target for optimization (which I may change later)?

Thanks,
-- Octav

**Comment by hvy** [comment]
Optuna supports multi objective optimization (creates a set of Pareto optimal parameter configurations, [docs](https://optuna.readthedocs.io/en/stable/reference/multi_objective/generated/optuna.multi_objective.study.create_study.html#optuna.multi_objective.study.create_study)) but my understanding is that this is not what you're looking for.

If you want to do some tracking on your own, you could perhaps for instance use [`Trial.set_user_attr`](https://optuna.readthedocs.io/en/stable/reference/generated/optuna.trial.Trial.html#optuna.trial.Trial.set_user_attr) to store (almost) arbitrary key-value pairs per trial. I'm not sure this addressed your needs, so if you could elaborate a bit on your use case, that'd also help. Worth clarifying is that unless you're using Optuna's multi objective optimization, a trial will be associated with a single objective value once it's completed, and you cannot really change this value after that. This is the value that the samplers will observe in order to suggest the next set of parameters.

**Comment by hvy** [comment]
Discussion on Gitter https://gitter.im/optuna/optuna?at=5fbf019d29cc4d73482ffe50
