### ISSUE TITLE
Get "object" of the best model

### ISSUE THREAD

**Issue by michael135** [optuna/optuna#2085]
I'm using a Optuna for a lightgbm tuning.

When tuning is finished, I'm getting the parameters of the best model.

Is it possible to obtain the "model object" of the best model?

**Comment by toshihikoyanase** [comment]
Hi @michael135 
If you use [`LightGBMTuner`](https://optuna.readthedocs.io/en/stable/reference/generated/optuna.integration.lightgbm.LightGBMTuner.html), you can use [`LightGBMTuner.get_best_booster`](https://optuna.readthedocs.io/en/stable/reference/generated/optuna.integration.lightgbm.LightGBMTuner.html#optuna.integration.lightgbm.LightGBMTuner.get_best_booster) method to get the best model. Otherwise, you need to persist trained models by yourself (c.f., [How to save machine learning models trained in objective functions?](https://optuna.readthedocs.io/en/stable/faq.html#how-to-save-machine-learning-models-trained-in-objective-functions)).

**Comment by michael135** [comment]
Thank you @toshihikoyanase! 
Got it.

I follow this example,
https://medium.com/optuna/lightgbm-tuner-new-optuna-integration-for-hyperparameter-optimization-8b7095e99258

If I understand correctly in above example `LightGBMTuner` is not used ?
Is there any example example of `LightGBMTuner` usage?
What is an advatage of using `LightGBMTuner` instead of "regular Optuna"?


At (https://optuna.readthedocs.io/en/stable/faq.html#how-to-save-machine-learning-models-trained-in-objective-functions) it's nice example! But if I do 10K trials, somehow I'm not excited to save 10K models, which can take a few Gb.
