### ISSUE TITLE
study.best_trial gives confusing errors with early pruning

### ISSUE THREAD

**Issue by KerekesDavid** [optuna/optuna#2101]
Calling `best_trial` either gives the error `ValueError: Record does not exist.` or `ValueError: No trials are completed yet.` if called when only pruned trials exist in a study. The error changes depending on whether the study was initialized with a db or in memory.

## Expected behavior

For my use-case the most intuitive behavior would be for best_trial to also take pruned trials into account.

I'm running trials one-by-one on a distributed environment and trying to report the best trial as each one finishes. I spent a few hours debugging why there are seemingly no trials logged in the database before I realized what was happening. 

Edited just to clarify: the `ValueError: No trials are completed yet.` is at least pointing the user in the right direction, the `ValueError: Record does not exist.` was what led me on a wild goose chase.

If this is not desirable for other use-cases, I think best_trial should either return a `None` value, or at least an easy to catch, consistent error. The first option would allow for the pythonic  `if study.best_trial: print(study.best_trial)` handling of the edge case.

## Environment

- Optuna version: 2.3.0
- Python version: 3.8.6
- OS: Ubuntu 20.10

## Error messages, stack traces, or logs

```
Traceback (most recent call last):
  File "optuna_debug.py", line 11, in <module>
    print(study.best_trial)
  File "/home/david/envs/optuna/lib/python3.8/site-packages/optuna/study.py", line 72, in best_trial
    return copy.deepcopy(self._storage.get_best_trial(self._study_id))
  File "/home/david/envs/optuna/lib/python3.8/site-packages/optuna/storages/_cached_storage.py", line 264, in get_best_trial
    return self._backend.get_best_trial(study_id)
  File "/home/david/envs/optuna/lib/python3.8/site-packages/optuna/storages/_rdb/storage.py", line 1035, in get_best_trial
    trial = models.TrialModel.find_min_value_trial(study_id, session)
  File "/home/david/envs/optuna/lib/python3.8/site-packages/optuna/storages/_rdb/models.py", line 216, in find_min_value_trial
    raise ValueError(NOT_FOUND_MSG)
ValueError: Record does not exist.
```

```
Traceback (most recent call last):
  File "optuna_debug.py", line 11, in <module>
    print(study.best_trial)
  File "/home/david/envs/optuna/lib/python3.8/site-packages/optuna/study.py", line 72, in best_trial
    return copy.deepcopy(self._storage.get_best_trial(self._study_id))
  File "/home/david/envs/optuna/lib/python3.8/site-packages/optuna/storages/_in_memory.py", line 275, in get_best_trial
    raise ValueError("No trials are completed yet.")
ValueError: No trials are completed yet.
```

## Steps to reproduce

1. Create a new study
2. Prune a trial
3. Try to access study.best_trial

## Reproducible examples (optional)

```python
import optuna

def objective(trial):
    trial.report(1.0, step=1)
    raise optuna.TrialPruned()

study = optuna.create_study()
study.optimize(objective, n_trials=1)

print(study.best_trial)
```

```python
import optuna

def objective(trial):
    trial.report(1.0, step=1)
    raise optuna.TrialPruned()

study = optuna.create_study(storage='sqlite:///./optuna.db')
study.optimize(objective, n_trials=1)

print(study.best_trial)
```

**Comment by hvy** [comment]
Thanks for the report, it indeed sounds like a bug that errors are inconsistent. We should alight to the latter error. The former is a lower level error and should not be propagated here. This should be rather straight forward. 

As for raising `None` or including pruned trials,  I'd like to get some more feedback since it's a breaking change, but it sounds like a valid discussion. I understand that raising errors here might cause some headaches. There is no simple way to check given a study object whether it contains finished studies or not.

**Comment by hvy** [comment]
Do you want to tackle the alignment of the errors? I might be able to help you get started if you're interested. Otherwise, we could label this part as contribution welcome.

**Comment by KerekesDavid** [comment]
I'd gladly help out with this. I'll figure out where it's the easiest to unify the two kinds of errors, probably we should throw the right error from RDBStorage onward. I'll also add a blurb about what error to expect in the documentation.

**Comment by rikkigouda** [comment]
@hvy @KerekesDavid Any update on this issue?

**Comment by hvy** [comment]
Not as far as I know. Are you blocked by this behavior, or do you happen to be interested in working on a fix? Cc. @KerekesDavid

**Comment by rikkigouda** [comment]
> Not as far as I know. Are you blocked by this behavior, or do you happen to be interested in working on a fix? Cc. @KerekesDavid 

Hi @hvy. We ended up identifying the issue as the underlying sqlite architecture.

If the program is interrupted to exit, the database is not fully saved for some reason. (Perhaps because it's stored as a db file)

We have since switched to MySQL and the data is loading correctly upon resuming a study. Our assumption is that it works because of the transactional nature of the database server.

Thoughts?

**Comment by hvy** [comment]
Good to hear that you found a workaround.

> If the program is interrupted to exit, the database is not fully saved for some reason. (Perhaps because it's stored as a db file)

Yes perhaps. Just curious but could you elaborate a bit on how the database is actually saved (what data is present/missing). And also, if you happen to have reproducible code, although I'd image it's quite difficult to reproduce without a decent amount of repeitions.

**Comment by rikkigouda** [comment]
So.. I've been working on enabling a distributed run of our optimisation code. The optimisation bit to put it simply, runs a study.

So the idea is to spin up a lot of VMs and run the optimisation across different machines. Once all the jobs are done, then load the study to look at the best trial and plot the importance of hparams etc.

Now when we do this in sqlite, if the program is interrupted (by pressing Ctrl+C), the database comes back empty. Seems like we should do a graceful stop of the study instead of killing it, but I have not tried that with sqlite.

Empty as in there are no records in the trials table, thus no best trial is found when validating the study database.

As I mentioned, we have since moved to MySql connections to avoid this behaviour.

Let me know if I can help with anything. And thanks for following back up!

**Comment by nzw0301** [comment]
@kjyv  How about using `study.get_trials` instead of try-catch of `ValueError` of accessing `study.best_value`?

```python
import optuna

def o(t):
    return None
    

s = optuna.create_study()
s.optimize(o, n_trials=20)

if len(s.get_trials(states=[optuna.trial.TrialState.COMPLETE])) == 0:
    print("You don't have complite trials at all")
else:
    print("Enjoy")
```

**Comment by kjyv** [comment]
Thanks that looks much nicer! I didn't see that method
