### ISSUE TITLE
What happens when I add/remove parameters dynamically during an Optuna study?

### ISSUE THREAD

**Issue by jorijnsmit** [optuna/optuna#2141]
Cross-posted from https://stackoverflow.com/questions/65362133/what-happens-when-i-add-remove-parameters-dynamically-during-an-optuna-study:
> Optuna's FAQ has a [clear answer](https://optuna.readthedocs.io/en/stable/faq.html#id10) when it comes to dynamically adjusting the range of parameter during a study: it poses no problem since each sampler is defined individually.
>
> But what about adding and/or removing parameters? Is Optuna able to handle such adjustments?
>
> One thing I noticed when doing this is that in the results dataframe these parameters get `nan` entries for other trials. Would there be any benefit to being able to set these `nan`s to their (default) value that they had when not being sampled? Is the study still sound with all these unknown values?

I believe an underlying question is: is there dependence between the `trial.suggest_` functions?

**Comment by HideakiImamura** [comment]
Thanks for the question. Optuna internally supports two types of sampling: `optuna.samplers.BaseSampler.sample_independet` and `optuna.samplers.BaseSampler.sample_relative`. 

The former `optuna.samplers.BaseSampler.sample_independet` is a method that samples independently on each parameter, and is not affected by the addition or removal of parameters. The added parameters are taken into account from the timing when they are added.

The latter `optuna.samplers.BaseSampler.sample_relative` is a method that samples by considering the correlation of parameters and is affected by the addition or removal of parameters. Optuna's default search space for correlation is the product set of the domains of the parameters that exist from the beginning of the hyperparameter tuning to the present. Developers who implement samplers can implement their own search space calculation method `optuna.samplers.BaseSampler.infer_relative_search_space`. This may allow correlations to be considered for hyperparameters that have been added or removed, but this depends on the sampling algorithm, so there is no API for normal users to modify.

**Comment by HideakiImamura** [comment]
Let me close this issue. @jorijnsmit please re-open this if you want.

**Comment by jorijnsmit** [comment]
My question was answered, thank you @HideakiImamura 🙏

**Comment by vldud-off** [comment]
@HideakiImamura Are you able to give a little clarification? If I need a reliable way to work with different samplers, what should I do? For example, I have a binary parameter that appears according to some condition:
`
if condition:
        some_param = trial.suggest_int("some_param", 0, 1)
`
Should I use something like that to be sure that any relative sampler will work correctly:
`
if condition:
      some_param = trial.suggest_int("some_param", 0, 1)
else:
      some_param = trial.suggest_int("some_param", 0, 0)   
`

**Comment by sliedes** [comment]
I think a common case for this would be when some hyperparameter has been previously fixed (or otherwise determinable from the previous parameters, so you can say that you know that parameter for all the previous runs), and you'd want to start optimizing for that parameter too without throwing away the previous trials.

If I understand correctly, it should at least always be safe to start a new study and .add_trial the old trials, augmenting them with the constant/calculated value for the new hyperparameter?

**Comment by jomalla123** [comment]
> I think a common case for this would be when some hyperparameter has been previously fixed (or otherwise determinable from the previous parameters, so you can say that you know that parameter for all the previous runs), and you'd want to start optimizing for that parameter too without throwing away the previous trials.


This issues is related to #1855 and there hvy provided a nice example on how create a new study based on old study with less hyperparameters: https://github.com/optuna/optuna/issues/1855#issuecomment-698112445

Still, I think it would be nice to have an API that makes that a bit easier.

**Comment by jamesobaldwin** [comment]
I am coming up against a similar problem, though with a slight twist. I have hyperparameters whose existence depends on the value of another hyperparameter, but I need my hyperparameters to be defined for a single base model due to working through a third party interface (clearML). So I do not have the option to define these hyperparameters for later trials, since the entire study is done based off a single base model that is cloned 'number of trials' times, and each clone gets a different selection of hyperparameters. However, it's not clear to me how to handle the situation where, for instance, if hp1 = 1 I might have the hyperparams a1,m1, but if hp1=2 then I would have hyperparameters a1,m1,a2,m2, and so on, with all a's and m's needing their own sampling of integer ranges. I am also asking this question in the clearML community, but wanted to get as much input as possible.

**Comment by nabenabe0928** [comment]
@jamesobaldwin 

Hey, thank you for posting your issue here, but I didn't get your problem from your description well.
It would be helpful if you could provide some codes or links where your problem is described well.
