### ISSUE TITLE
Optuna.visualization.plot_slice shows only one row, add parameters nrows,ncols

### ISSUE THREAD

**Issue by bhishanpdl** [optuna/optuna#2162]
When we run the command `optuna.visualization.plot_slice(study)` it returns plotly figure with one long row with multiple subfigures.

We can change the height and width as follows:

```python
fig = optuna.visualization.plot_slice(study)
fig['layout']['height'] = 800
fig.show()
```

But, We can not specify the number of rows and number of columns.

I would request adding this feature so the output figure looks easy to understand.

We can just add `nrow` parameter, which will choose automatically the `ncol` parameter and plot `nrow` rows and `ncol` columns.

**Comment by crcrpar** [comment]
The request sounds pretty reasonable to me and required change would be small and straightforward.

---

memo

`plot_slice` function internally calls `_get_slice_plot` which calls `make_subplots` with `rows` being 1 as follows.


https://github.com/optuna/optuna/blob/392088c25d661b997c4143fd18ccdb7480ffa825/optuna/visualization/_slice.py#L121

**Comment by hvy** [comment]
I believe that the `params` parameter was provided to partially account for that. You can create multiple figures, one per row. But I agree that an argument would improve the experience. If we'd like to support the same feature in `optuna.visualization.matplotlib.plot_slice`, I think changes are quite similar since it is using `pyplot.subplots`.

**Comment by FlorinAndrei** [comment]
Any progress?
