### ISSUE TITLE
`nan` handling in `trial.report` and multi-objective study.

### ISSUE THREAD

**Issue by ytsmiling** [optuna/optuna#2169]
## Expected behavior

* ``trial.report()`` accepts ``nan``
* Return value of multi-objective study accepts ``nan``
* Multi-objective study mark trials as ``FAILED`` when one or more return values are ``nan``.

## Bugs

1. ``trial.report`` fails when the value is ``nan`` when combined with MySQL backend.
2. Multi-objective trial also fails on ``report`` with ``nan`` value when combined with MySQL backend.
3. Multi-objective study internally depends on `trial.report` and thus error occurs when one or more return value is ``nan``.
4. With in-memory db, multi-objective study registers trials with ``nan`` return value as ``COMPLETED`` trial.

## Notes

I think whether ``trial.report`` should accept ``nan`` or not requires discussion.

## Environment

- Optuna version: 2.3.0
- Python version: 3.8
- OS: macOS Catalina
- PyMySQL version: 0.10.1

## Error messages, stack traces, or logs

(When called `trial.report` with ``nan`` value w/ MySQL backend.)
```
ProgrammingError: (pymysql.err.ProgrammingError) nan can not be used with MySQL
[SQL: INSERT INTO trial_values (trial_id, step, value) VALUES (%(trial_id)s, %(step)s, %(value)s)]
[parameters: {'trial_id': 34849, 'step': 1, 'value': nan}]
(Background on this error at: http://sqlalche.me/e/13/f405)
```

## Steps to reproduce

1. ``trial.report(float(np.nan), 1)``

## Additional context (optional)

Single-objective study accepts nan as the return value and marks it as `failed`. This is achieved in the following.
https://github.com/optuna/optuna/blob/4b4891dee27fb3fac2cb21a532e5a6ba2dd5b6aa/optuna/_optimize.py#L305

With in-memory db, `trial.report` accepts ``nan``.

**Comment by hvy** [comment]
I think these are manifestations of a somewhat unaddressed problem of handling `nan`s in Optuna and the report possibilities for multi objective (MO) optimization. For instance, the current MO submodule will be deprecated in the next v2.4 and the new multi objective features incorporated as a first class citizen to the main module. Trying to report will [raise an early error](https://github.com/optuna/optuna/blob/master/optuna/trial/_trial.py#L569-L572). I'm not sure to what extent we should "fix" the deprecated submodule. You might have comments on this.

On a related note regarding the expected behavior about allowing `nan`. Is it important to allow `nan`? In my understanding, `nan` should rarely if at all be expected and allowing `nan` has the negative side effect that all samplers/pruners/etc. that depend on trial values and intermediate values will have to account for the possibility of observing such values.

**Comment by ytsmiling** [comment]
> I'm not sure to what extent we should "fix" the deprecated submodule.

I think it's totally fine if we address the problem only in the main module. The current problem is that the whole optuna process stops instead of handling the trial as `FAILED`. This should not be expected behavior. This problem occurs only with database backends, and it'll be better if we add the `nan`-handling tests to the DB-tests,

> Is it important to allow nan?

I think it depends, but I feel it should be consistent between `trial.repot`/return-value and single-objective/multi-objective. I feel it's better if optuna provides some explicit interface to mark the trial as `unobservable` if we don't allow `nan`.

**Comment by hvy** [comment]
> I think it's totally fine if we address the problem only in the main module.

We can then scope this discussion to `Trial.report`. The `RDBStorage` failure when reporting `nan` values stems from the fact the [database column is not nullable](https://github.com/optuna/optuna/blob/master/optuna/storages/_rdb/models.py#L453). In order to allow reporting `nan` values, we would could relax this constraint. Again, I'm not sure whether allowing `nan` values is the correct approach. But I agree that it's something that should've been covered by unit tests.

> I think it depends, but I feel it should be consistent between trial.repot/return-value and single-objective/multi-objective

I also suggest behavior to  be consistent. In that case, if we say would allow `nan` values across all values, then we'd possibly break existing samplers. The problem on the other hand if we'd try to prohibit `nan` values might be that it's not necessarily straight forward how we'd automatically fail a trial on report (of `nan`). Perhaps introduce and raise a custom error type and catch it where we're calling the objective function. I think it's possible, though.

> provides some explicit interface to mark the trial as unobservable if we don't allow nan.

Do you mean introducing a new trial state? Sorry I couldn't quite understand what you meant.

**Comment by ytsmiling** [comment]
I found my PR comment was confusing. I should have written `trial.report handles nan gracefully` instead of `trial.report accepts nan`. Sorry about that. I'd like to clarify that I think exiting the trial on `trial.report` with `nan` will be the most promising approach to address the problem.

>  Perhaps introduce and raise a custom error type and catch it where we're calling the objective function.

I think this is a reasonable approach. 

> Do you mean introducing a new trial state.

I think this also comes from the misunderstanding. I think it's okay to leave everything as is if optuna does not abort the whole study when `nan` is passed.

**Comment by bwegge** [comment]
Hi, I am experiencing the same issue with single objective studies and the SQLite backend. I use pruning with the TFKerasPruningCallback, where in some rare cases a nan loss is reported, which then causes the whole program to crash. I also think it is preferrable to handle such reports of nan values more gracefully by letting the program continue in that case, and marking the trial e.g. as FAILED (or another designated status).

**Comment by LucaMarconato** [comment]
I have also just encountered this problem. Any recommended workaround?

**Comment by lsc64** [comment]
> I have also just encountered this problem. Any recommended workaround?

My workaround is to replace all nan-values before handing them to optuna.
```Python
    def training_step(self, batch, batch_idx) -> torch.Tensor:
       [...]
       loss = self.loss_fn(y_pred,y)
       loss = torch.nan_to_num(loss, nan=torch.finfo(loss.dtype).max) # this will probably crash for non-float types
       self.log('train_loss', loss)
       return loss
```
You can set a different replacement value, see [torch.nan_to_num](https://pytorch.org/docs/stable/generated/torch.nan_to_num.html#). In my example I replace nan by the maximum representable float value, so the maximum error. Maybe 0 or something else makes more sense in your case.

**Comment by LucaMarconato** [comment]
Working! Thanks a lot :)
I'm not using the latest version of PyTorch, so I used this `loss[torch.isnan(loss)] = torch.finfo(loss.dtype).max`

**Comment by keisuke-umezawa** [comment]
@HideakiImamura Can we close this PR?

**Comment by contramundum53** [comment]
This issue has already been solved.
