### ISSUE TITLE
Performance drop after 1000+ trial

### ISSUE THREAD

**Issue by aero-108** [optuna/optuna#2172]
On ```sampler = optuna.samplers.TPESampler(n_startup_trials=10000)```
during first ~1000 trials performance nearly 70it/sec.
After >1000 performance drops to 8-9it/sec.
But why if all trials up to 10000 are just randoms?
Any suggestions how to fix it ?

**Comment by hvy** [comment]
The results may vary depend on what storage you're using with your study. But is it not a linear scaling rather than a sudden drop after 1000 trials? The bottleneck then is the operation in the TPE sampler that goes through all trial previous trials (in a Python for loop) to construct the data required for suggestion. The size of this data is also used to determine whether the sampler should fall back to random sampling or not. Actually, we don't need to collect the data but merely count the number of trials in order to determine whether it should fall back to random sampling or not, so I guess there's room for optimization.

Some relevant benchmarks with v2.3.0 using the in memory storage.

```bash
python -m cProfile -s totime examples/quadratic_simple.py
```

First few lines of the output from the above command.

```
   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
     6000   21.721    0.004   30.570    0.005 sampler.py:742(_get_observation_pairs)
 18009000    2.626    0.000    2.626    0.000 _frozen.py:378(params)
  4501500    2.062    0.000    2.721    0.000 distributions.py:438(to_internal_repr)
     3000    1.908    0.001    1.959    0.001 study.py:574(_pop_waiting_trial_id)
  9018000    1.770    0.000    1.770    0.000 _frozen.py:388(distributions)
 18181687    1.338    0.000    1.338    0.000 {method 'append' of 'list' objects}
     1698    0.735    0.000    0.735    0.000 {method 'read' of '_io.FileIO' objects}
  4501521    0.659    0.000    0.659    0.000 {method 'index' of 'tuple' objects}
     6000    0.570    0.000   31.945    0.005 _trial.py:672(_suggest)
309000/9000    0.396    0.000    1.009    0.000 copy.py:132(deepcopy)
  4501500    0.336    0.000    0.336    0.000 distributions.py:35(to_internal_repr)
  203/201    0.318    0.002    0.322    0.002 {built-in method _imp.create_dynamic}
     1584    0.204    0.000    0.204    0.000 {built-in method marshal.loads}
48410/18410    0.144    0.000    0.975    0.000 copy.py:268(_reconstruct)
51000/9000    0.126    0.000    0.860    0.000 copy.py:236(_deepcopy_dict)
      222    0.118    0.001    0.118    0.001 {built-in method posix.listdir}
     9000    0.118    0.000    0.120    0.000 _in_memory.py:381(get_all_trials)
```
