### ISSUE TITLE
Using Optuna after each batch/epoch

### ISSUE THREAD

**Issue by tide90** [optuna/optuna#2182]
I am new to Optuna. I did not find a way to use optuna for looking for the best results after each epoch or even after each batch for several epochs.
So let's say I run everytime 5 epochs, but want to use the best score while tuning with optuna. Also it woul dbe nice if optuna can look also after each batch. I want to use tf.keras.

**Comment by hvy** [comment]
I'm not an expert on tk.keras so I might be missing your point. Do you want to compare intermediate results between different trials? I.e. something along  [plot_intermediate_values](https://optuna.readthedocs.io/en/stable/reference/visualization/generated/optuna.visualization.plot_intermediate_values.html#optuna.visualization.plot_intermediate_values). Perhaps, early stop trials that are unpromising. In that case, you might want to take a look at the [pruners](https://optuna.readthedocs.io/en/stable/reference/pruners.html#) and in particular [TFKerasPruningCallback](https://optuna.readthedocs.io/en/stable/reference/generated/optuna.integration.TFKerasPruningCallback.html). If you could elaborate a bit or provide some (pseudo) code, that might help.

**Comment by tide90** [comment]
Hey, 

I do not want to use early stopping. I want to train eg 5 epoch and take the best resultsof the epoch. Or the best results after the best batch...

Optuna seems just take the results at the end of the last epoch.

**Comment by HideakiImamura** [comment]
In hyperparameter optimization, we determine a set of hyperparameters for each of the 100 trials, for example, and calculate the value of the objective function. In particular, in hyperparameter optimization for deep learning, we divide the computation of the objective function into, say, 100 epochs, compute the objective function sequentially in each epoch, and return the final computed value after 100 epochs. It is important to note that the hyperparameters do not change over these 100 epochs, since the calculations are done within the same trial. Therefore, there is no need for Optuna to report the intermediate value for each epoch if you do not want to use early termination.

If you want to output the optimal hyperparameters for each epoch after the optimization of 100 trials is completed, the situation is different. Is this your use case? In that case, you should report the intermediate value for each epoch of each trial, and after the optimization is finished, you can do the following.
```python
import optuna
import numpy as np

def objective(trial):
    ...
    for i in range(n_epochs):
        intermediate_value = ...
        trial.report(i, intermediate_value)
    ...

study = optuna.create_study(direction="minimize")
study.optimize(objective, n_trials=100)

trials = study.trials
best_params_for_each_epochs = []
for i in range(n_epochs):
    j = np.min([trial.intermediate_values[i] for trial in trials])
    best_params_for_each_epochs.append(trials[j].params)

# best_params_for_each_epochs[i] is a dictionary of the best hyperparameter in the `i` epoch.

**Comment by tide90** [comment]
@HideakiImamura I don'nt knwo why so complicated  to understand. My goal is to find the best parameters. In Deep Learning the epoch is an important issue as in NLP eg you get only for the first few epochs good results and for epoch 3 eg you get lower results. So for a given set of parameters I want to train all models in each trial for eg 5 epochs, but want to store the best epoch/batch. In finetuning eg BERT models you you just need to train sometimes even less than 1 epoch and just for a couple of batches so eg just half of 1 epoch. That is why I am interested to get the best batch too. 

But your above code example should help with that! Thanks
