### ISSUE TITLE
ValueError: CategoricalDistribution does not support dynamic value space.

### ISSUE THREAD

**Issue by nothingeasy** [optuna/optuna#2199]
trail.suggest_categorical("batch_size", [64, 128])  does not work and raise error;
trail.suggest_categorical("batch_size", [64, 128,256,512])  work;
I think I do not need to talk more about it , the question is so clear and everyone can reproduce it.
How can i use different value(no step case) i want  ?

**Comment by hvy** [comment]
I believe the problem is that you're trying to change the possible choices in different trials. Is my understanding correct? If that's the case, it's unfortunately not supported. The reason is quite well explained in https://github.com/optuna/optuna/issues/372#issuecomment-480690635. (Documentation could be improved for e.g. `Trial.suggest_categorical` to mention this)

**Comment by nothingeasy** [comment]
Thanks a lot ！ 
Maybe I make some mistake . I reload the study and it cause choices changed!

**Comment by redfave** [comment]
I extended a choice list to one value more, so I just patched the sqlite database to get rid of the exception and continue my trial with an additional choice to sample.

Open the database in any client (or `sqlite3` in the cli).:
```
UPDATE trial_params
SET distribution_json = '{"name": "CategoricalDistribution", "attributes": {"choices": [1, 2, 3]}}'
WHERE param_name = 'k_hops'
AND distribution_json = '{"name": "CategoricalDistribution", "attributes": {"choices": [1, 2]}}';
```

As I just appended an additional value, so the column `param_value` don't need an update (As far as I see, it holds the index of the choice made).
But if you delete a value or add one in the middle, you need to adjust the indices properly.
