### ISSUE TITLE
Typo in xgboost_simple.py ? dart instead of  gblinear

### ISSUE THREAD

**Issue by sharov-am** [optuna/optuna#2215]
Hi.

Is it a typo in file https://github.com/optuna/optuna/blob/master/examples/xgboost_simple.py
that 
 `  if param["booster"] == "gbtree" or param["booster"] == "dart":
   ...
`
 and
` if param["booster"] == "dart":
....
`
"dart" is mentioned two times. Probably in first check should be  "gblinear" instead of "dart" ?

**Comment by nzw0301** [comment]
Hi @sharov-am, Probably not. `dart` booster has the same hyper-parameters as `gbtree` because `dart` inherits `gbtree` booster. This is set in the first `if` block. In addition, `dart` has its own hyper-parameters set by the second `if` block.

Reference: https://xgboost.readthedocs.io/en/latest/tutorials/dart.html#parameters
