### ISSUE TITLE
Relax style check requirements for examples and tutorials

### ISSUE THREAD

**Issue by crcrpar** [optuna/optuna#2240]
Currently we apply the bunch of rules to tutorials and examples likewise optuna source code.
However, since .py files under tutorial directory are actually jupyter notebooks-ish (at least I think so during editing them), thus it's a little bit demanding for tutorial to conform to Optuna style guide like two empty spaces between blocks, and this is the case for examples personally.

**Comment by nzw0301** [comment]
Related to this, the check has been failed due to mypy for the last few PRs. The latest mypy version has been updated to `v0.8.0` from `v0.7.9.`. According to [the release note](https://mypy-lang.blogspot.com/2021/01/mypy-0800-released.html), mypy starts to check files under directory without `__init__.py`; `examples/multi_objective/` in this case.
> When you run `mypy` as `mypy <directory>`, look for source files recursively also inside directories without a `__init__.py` (PR 9614)

**Comment by HideakiImamura** [comment]
Thanks for raising an issue. IMO, this proposal is reasonable. I'd like to have other committers' opinions. @g-votte @toshihikoyanase @hvy Do you have any opinions?

**Comment by jeromepatel** [comment]
@HideakiImamura I would like to work on this issue. Currently, checks are applied to the whole directory, so should we modify that to exclude `examples` and `tutorials` for all the style-checks? I think in that case `mypy . -type d \( -path tutorials -o -path examples \) -prune `  (same for other checks)  this can work. I would like to know your views on this. If you can guide me on this it would be helpful.
