### ISSUE TITLE
CategoricalDistribution does not support dynamic value space.

### ISSUE THREAD

**Issue by z7ye** [optuna/optuna#2328]
optuna does not support dynamic value space for CategoricalDistribution. I dont see why  adding or removing choices in the CategoricalDistribution is a problem. Would it possible to add this feature please?

**Comment by toshihikoyanase** [comment]
Thank you for your feature request. We can see some similar requests such as https://github.com/optuna/optuna/issues/372 and https://github.com/optuna/optuna/issues/2199. As mentioned in https://github.com/optuna/optuna/issues/372#issuecomment-480690635, we need design discussions of APIs and it may be difficult to resolve this issue soon.

Please keep this issue open as a tracker.

**Comment by psaks** [comment]
Any update on this? 

I encountered the same problem when trying to migrate from hyperopt to Optuna, where the following line resulted in the same issue unfortunately.

`params['max_features'] = hp.choice('max_features', ['auto', 1, hp.uniform('max_feature_fraction', 0, 1)]) `

Cheers,
Philip

**Comment by iganichev** [comment]
I am wondering if there have been updates on this issue. I run long (several weeks) studies and need to expand categorical spaces a fair bit. Because I need to create a new study every time, I loose old results and progress there.

If it is hard to design good APIs to make it seamless. Maybe there can be a stopgap function like
```
migrate_study(old_study_storage, new_study_storage, categorical_space_mapping)
```
where users can specify how to map old values for some categorical parameter to new values. This call would read the study from storage and write a new version updating the categories.

**Comment by OldPatrick** [comment]
Any updates on this?
