### ISSUE TITLE
Hypervolume computation results are incorrect

### ISSUE THREAD

**Issue by y0z** [optuna/optuna#2421]
Hypervolume must be monotonically increasing according to the addition of a nondominated point.
However, Optuna's hypervolume computation module sometimes returns a decreased value.

## Reproducible examples and Expected behavior

Please refer to the following colab.
https://colab.research.google.com/drive/1rZMYwNjQOxVNN8huDztsyl6BNAVMWdW9?usp=sharing

For the purposes of comparison, I also compute hypervolumes in the colab by using pygmo that is a widely used framework for multiobjective optimization and seems to be a reliable implementation.

**Comment by y0z** [comment]
Although I'm not familiar with the detail of the hypervolume computation algorithm, updating `self._reference_point` after L37 before L38 might be a bug similar to #1812.

https://github.com/optuna/optuna/blob/30161b238b33b32300aedfc8364ef511b5849543/optuna/multi_objective/_hypervolume/wfg.py#L37-L38

https://github.com/optuna/optuna/blob/30161b238b33b32300aedfc8364ef511b5849543/optuna/multi_objective/_hypervolume/utils.py#L43

**Comment by himkt** [comment]
Hello @y0z, I'm really sorry for the delayed response.
In the current implementation, I found passing `ndarray` of integer to `WFG.compute` causes a computation error.

https://github.com/optuna/optuna/blob/30161b238b33b32300aedfc8364ef511b5849543/optuna/multi_objective/_hypervolume/utils.py#L43
If `reference_point` is ndarray of integer, `solution[1]` would be casted to integer, which returns an incorrect result.

I confirmed that passing `[130.0, 50.0]` instead of `[130, 50]` to `optuna_hv.compute` calculated a results same as `pygmo_hv`.

<img src="https://user-images.githubusercontent.com/5164000/113573817-d5e6ee80-9655-11eb-8904-1703a022ae96.jpg" width="50%">

I'll make a PR to add a type conversion for `WFG.compute` to avoid this problem.

**Comment by y0z** [comment]
It makes sense! Great job.
Thank you :)

Please close this issue after merging your PR.

**Comment by HideakiImamura** [comment]
Hi @y0z! The problem seems to be resolved in #2584. Could you check the correctness if you have time?
