### ISSUE TITLE
multi-GPU training on a single node using joblib

### ISSUE THREAD

**Issue by ironv** [optuna/optuna#2465]
I am running grid search on a VM with 4GPUs and 24CPUs.  The attached [code](https://github.com/optuna/optuna/files/6118882/mlp-pl-optuna-joblib.py.txt)  which uses joblib and multiprocessing (created using an example posted earlier on this board) works fine.   Here's the issue -- I had to set num_workers=0 to get it to work.  As one can see, the entire dataset is being loaded to each of the GPUs and then the training runs in parallel.

If I set num_workers = any positive number, I get `AssertionError: daemonic processes are not allowed to have children`.  I realize that if I could write to a real database (not sqlite), I could runs these in parallel in multiple terminal.  But that is not an option for me given my VM is locked down.

In my real example, I have a very sparse dataset with 120k rows and 50k columns.  I can load each of them into GPUs (using Tensors and csr_matrix like schema) and create each batch on the fly and train in parallel (I have the code for that).  The issue is the GPU is being used both to construct the batches and train the NN, and 20+ CPUs are idle!!!!

Is there a way to use the CPUs for the dataloading?

Unrelated question -- is there a way to limit the number of digits in `suggest_float`?  I would prefer not to have a dropout specified to 10th decimal place.  Line 143 in the attached code.

**Comment by nzw0301** [comment]
I think that the issue is related to a combination of `multiprocess.Parallel` and PyTorch's dataloader. [This section](https://pytorch.org/docs/stable/data.html#single-and-multi-process-data-loading) might be useful-- `num_workers` should be `0` with multi-process.

> Unrelated question -- is there a way to limit the number of digits in suggest_float? I would prefer not to have a dropout specified to 10th decimal place. Line 143 in the attached code.

How about using [`suggest_categorical`](https://optuna.readthedocs.io/en/stable/reference/generated/optuna.trial.Trial.html#optuna.trial.Trial.suggest_categorical)?
