### ISSUE TITLE
Is it possible to skip the next parameter sampling (my trial runs forever with this ...)

### ISSUE THREAD

**Issue by simpsus** [optuna/optuna#2478]
I have a number of hyperparamters to tune and many configurations provide a fast trial (~5 minutes), some a slower (~5 hours) and some not even the first step is completed in the 10 hours I let it run so far.
Terminating the study and restarting makes it chose the same parameters (which makes sense). I would like to include a command / switch saying ==> Skip the next choice of commands and then run normal again.

Is that possible?

**Comment by nzw0301** [comment]
Hi @simpsus, In my understanding, you would like to skip some time-consuming trials during `study.optimize`. If so, how about using `timeout` argument of [`study.optimize`](https://optuna.readthedocs.io/en/stable/reference/generated/optuna.study.Study.html#optuna.study.Study.optimize)?

**Comment by simpsus** [comment]
Hi @nzw0301 thx for your answer!
I did not know this parameter existed. Thx for pointing this out.
I am afraid it will not scratch my itch.

I do not want to terminate the whole study, but this trial and continue with the next trial. 
I tested manually terminating the study and restarting (the trial number increases) but in my observation the parameters for the next trial are the same as the ones which did not terminate.

Come to think of it, what I would _really_ like to have is a TimoutPruner that prunes a trial if it exceeds a duration. Or a timeout argument for the median pruner.

**Comment by nzw0301** [comment]
Hi, @simpsus.  Indeed, `timeout` in `optimize` was not appropriate for such a case :(

Fortunately, I think we can define our own pruner as in [this tutorial](https://optuna.readthedocs.io/en/stable/tutorial/20_recipes/006_user_defined_pruner.html).

**Comment by nzw0301** [comment]
Like this?

```python
import time
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.linear_model import SGDClassifier

import optuna
from optuna.pruners import BasePruner
from optuna.trial._state import TrialState


class TimePruner(BasePruner):
    def __init__(self, warmup_steps, warmup_trials, max_sec_per_trial=60):
        self._warmup_steps = warmup_steps
        self._warmup_trials = warmup_trials
        self._max_sec_per_trial = max_sec_per_trial

    def prune(self, study: "optuna.study.Study", trial: "optuna.trial.FrozenTrial") -> bool:

        step = trial.last_step
        
        if not step:
            self.start_time = time.time()

        if step:  # trial.last_step == None when no scores have been reported yet                

            # Get scores from other trials in the study reported at the same step
            completed_trials = study.get_trials(deepcopy=False, states=(TrialState.COMPLETE,))
            other_scores = [
                t.intermediate_values[step]
                for t in completed_trials
                if step in t.intermediate_values
            ]
                
            if step >= self._warmup_steps and len(other_scores) > self._warmup_trials:
                if time.time() - self.start_time > self._max_sec_per_trial:
                    print(f"This trial takes more than {self._max_sec_per_trial} seconds.")
                    return True

        return False

def objective(trial):
    iris = load_iris()
    classes = np.unique(iris.target)
    X_train, X_valid, y_train, y_valid = train_test_split(
        iris.data, iris.target, train_size=100, test_size=50, random_state=0
    )

    loss = trial.suggest_categorical("loss", ["hinge", "log", "perceptron"])
    alpha = trial.suggest_float("alpha", 0.00001, 0.001, log=True)
    clf = SGDClassifier(loss=loss, alpha=alpha, random_state=0)
    score = 0

    for step in range(5):
        time.sleep(trial.number)
        
        clf.partial_fit(X_train, y_train, classes=classes)
        score = clf.score(X_valid, y_valid)
        
        trial.report(score, step)

        if trial.should_prune():
            raise optuna.TrialPruned()

    return score


pruner = TimePruner(warmup_steps=1, warmup_trials=1, max_sec_per_trial=2)
study = optuna.create_study(direction="maximize", pruner=pruner)
study.optimize(objective, n_trials=11)
```

Output:
```
I 2021-03-16 20:24:19,240] A new study created in memory with name: no-name-71d6a968-e061-4031-a19e-ff47e1d15e49
[I 2021-03-16 20:24:19,258] Trial 0 finished with value: 0.76 and parameters: {'loss': 'perceptron', 'alpha': 0.0002599135020892823}. Best is trial 0 with value: 0.76.
[I 2021-03-16 20:24:24,284] Trial 1 finished with value: 0.72 and parameters: {'loss': 'log', 'alpha': 7.28551742336147e-05}. Best is trial 0 with value: 0.76.
[I 2021-03-16 20:24:28,298] Trial 2 pruned. 
This trial takes more than 2 seconds.
[I 2021-03-16 20:24:34,315] Trial 3 pruned. 
This trial takes more than 2 seconds.
...
```

**Comment by simpsus** [comment]
Thank you very much! I will try out this pruner and close the issue for now!
One observation from the code: The pruner has to have a chance to prune. so in between steps. Usually, the long times are in the `fit` method of the classifier. Then it is paramount that this pruner is included via the integration...

**Comment by david-thrower** [comment]
I have a related addition to this. If I missed something in the documentation that I should have caught, sorry to take your time.

I have a task that is coming a vast and extremely disjointed hyperparameter space (the trial specific range of valid values for parameter b is a function of what value was chosen for parameter a, specifically, the most common being, that a must be less than b, otherwise, you are telling the traial to create a negative number of tensors .... a contradiction). If you try randomized permutations of values in the minimum to maximum values containing some valid combinationsof interest, 25% to 75% of the random permission will be invalid. I want to be able in these cases to direct the tuner to "skip this one" when an invalid suggestion is made, ideally, without needing to set the parameter for 'MaxFailedTrials'  as "infinity" and just accept that 25 - 75 percent of the random permutations of the parameter value ranges of interest will be invalid and will throw an error. This would also have the side effect of obfuscating any **unforseen** errors that would indicate aborting the study and debugging it because I effectively silenced all errors to avoid the **foreseen** errors from making the study fail out ... Additionally, in cases like mine, it may be good if the turner's  API can be extended to include an argument that expects a function, where said function screens suggestions suggestion based on user defined logic and can "raise a non-error order to skip the trial" , after the trail suggestions are generated, but before the worker, training function instance, .... are provisioned to execute it. If each trial will set up a worker that imports Jax, TensorFlow, etc ... this can be a lot of overhead only to find a < b, and this needs to throw an error, especially if this us expected to occur hundreds of times.

**Comment by david-thrower** [comment]
Simpsus, I found a similar example in the documentation shortly after posting this, and thought I deleted the comment after finding it. 

Sorry I had missed this and took up your time. I just added a pruner class to prune all trials not meeting validity criteria 
that hopefully will fix this issue. I need to set a flie lock and update file name parsing before I can tell if thos worked, as each trial writes an HTML file with a network diagram of the model architecture... Now the issue I am faced with is upstream from here: I'm led to beleive KFP counts pruned trials as errors, and the only way to make it complete is to set the error limit to a high number (and hope that I'm not as a side effect, ignoring an unforseen error that I need to detect immediately and abort the run. It's understandable that I will run into issues like this doing something this complex ... it's all part of tbe process. I'm not sure how MLflow handles prined trials, but I can look that route too ... I'm sure we'll figure out a viable path in the next few days somehow. At least I don't have to write a new tuner like I thought I would...
