### ISSUE TITLE
AWS S3 location for RDB sqlite

### ISSUE THREAD

**Issue by turian** [optuna/optuna#2518]
Optionally the RDB sqlite could be an AWS S3 location.

## Motivation

When running on AWS, it would be great if optionally the RDB sqlite could be an AWS S3 location. This is particularly useful for spot instances that get torn down without notice.

## Description

If the URL is "s3+sqlite:///bucketname/file.db", the SQLite database is read and written to AWS S3.

## Alternatives (optional)

Do it by hand:
* Read sqlite from AWS S3.
* Write a callback that at the end of every trial, the local sqlite is copied the AWS.

**Comment by toshihikoyanase** [comment]
Sounds interesting!

I found a python library, [sqlalchemy-s3sqlite](https://github.com/cariaso/sqlalchemy-s3sqlite), which enables users to manipulate SQLite database on S3 via SQLalchemy.

Since Optuna's RDBStorage is built using SQLalchemy, I guess we can persist Optuna's results on S3 as follows (I haven't tried yet, though):

```python
import os

import optuna
from sqlalchemy.dialects import registry

registry.register("s3sqlite", "sqlalchemy-s3sqlite.dialect", "S3SQLiteDialect") 
os.environ["S3SQLite_bucket"] = "bucket name"

study = optuna.create_study(storage="s3sqlite:///sample.db")
study.optimize(objective, n_trials=10)
```

What do you think of this approach?

**Comment by turian** [comment]
For me that sounds great!

**Comment by turian** [comment]
Would it be possible to add this natively to optuna?

**Comment by turian** [comment]
Ping

**Comment by Crissman** [comment]
Thanks for the comment, Turian.

`sqlalchemy-s3sqlite` seems to be able to open and close files, which looks useable.
There are some concerns about moving this native, though, such as processes overwriting previous results, which we believe are better resolved with normal DB servers. Because of these restrictions, we think it's better to recommend users use `sqlalchemy-s3sqlite` than bring this into native Optuna.

Please close this issue if this addresses your concern.

Thanks!

**Comment by turian** [comment]
@Crissman I don't mind if this is native or not, just that there is a simple tutorial showing how to use SQLite3 with optuna
