### ISSUE TITLE
KeyError: 'Record does not exist.'

### ISSUE THREAD

**Issue by guangmingjian** [optuna/optuna#2527]
When I try to run the following code：

```

import optuna


def objective(trial):
    x = trial.suggest_float("x", -10, 10)
    return (x - 2) ** 2

if __name__ == "__main__":
    study = optuna.load_study(
        study_name="distributed-example", storage="mysql://root@localhost/example"
    )
    study.optimize(objective, n_trials=100)
```

And the error is as follows：
```
File "/home/mingjian/anaconda3/envs/python36/lib/python3.6/site-packages/optuna/study.py", line 1189, in load_study
return Study(study_name=study_name, storage=storage, sampler=sampler, pruner=pruner)
File "/home/mingjian/anaconda3/envs/python36/lib/python3.6/site-packages/optuna/study.py", line 231, in __init__
study_id = storage.get_study_id_from_name(study_name)
File "/home/mingjian/anaconda3/envs/python36/lib/python3.6/site-packages/optuna/storages/_cached_storage.py", line 124, in get_study_id_from_name
return self._backend.get_study_id_from_name(study_name)
File "/home/mingjian/anaconda3/envs/python36/lib/python3.6/site-packages/optuna/storages/_rdb/storage.py", line 316, in get_study_id_from_name
study = models.StudyModel.find_or_raise_by_name(study_name, session)
File "/home/mingjian/anaconda3/envs/python36/lib/python3.6/site-packages/optuna/storages/_rdb/models.py", line 71, in find_or_raise_by_name
raise KeyError(NOT_FOUND_MSG)
KeyError: 'Record does not exist.
```

Please help me, thanks!

**Comment by toshihikoyanase** [comment]
Hi @guangmingjian 
Could you check if you have `distributed-example` in `mysql://root@localhost/example`?
You can, for example, use `optuna studies` command to show all studies as follows:

```console
$ optuna studies --storage mysql://root@localhost/example
```

If you don't have the study, please create it in advance as follows:

```console
$ optuna create-study --storage mysql://root@localhost/example --study-name distributed-example
```

**Comment by guangmingjian** [comment]
Thanks！

**Comment by Stentaur** [comment]
Hello!

I'm getting the same KeyError - the .db file is definitely there, but it doesn't exist at the url (I fear I may have broken the connection by cutting+pasting the .db file...)

Does the .db file actually contain the information - can I open the study from there, somehow?

My code is like this:

```
study_name = "A2C_all_hyps"

storage_name = "sqlite:///{}.db".format(study_name)

study = optuna.create_study(study_name=study_name, storage=storage_name, direction="maximize", load_if_exists=True)

study.optimize(objective, n_trials=100)
```

(this ran for a looooong time)
I then tried:
`loaded_study = optuna.load_study(study_name=study_name, storage=storage_name)`
and got the KeyError

**Comment by Ademord** [comment]
I have the same error, any news on how to debug it ?

**Comment by nzw0301** [comment]
@Ademord Could you create a new post on https://github.com/optuna/optuna/discussions with your minimal reproducible script?

**Comment by Ademord** [comment]
@nzw0301 I dont think i can since its private.. but i think my problem lies in the sqlite breaking given read-write-locks in my dask setup (multiple nodes to which the client submits jobs to). As far as I have read the solution to my problem is to setup postgresql, but idk yet if its ok to use multiple studies then, or should i just encapsulate it all under one. i think i should create multiple studies since i am doing a backward greedy feature selection (2 loops) and then in the inner loop where a feature is being removed to analyze its performance, i am running a small set of trials w optuna, and then after i got the most valuable features, i then run a final optimization ... 

(another open question i got is that sometimes some trials have the same performances/values and idk why, it looks super odd to me)

**Comment by Ademord** [comment]
thank you! https://github.com/optuna/optuna/discussions/5427
