### ISSUE TITLE
Guidance on when to use TPESampler + CmaEsSampler

### ISSUE THREAD

**Issue by turian** [optuna/optuna#2537]
The original optuna paper uses TPESampler for the first half of the trials, and then switches to CmaEsSampler for the second half.

TPESampler now support [multivariate](https://medium.com/optuna/multivariate-tpe-makes-optuna-even-more-powerful-63c4bfbaebe2)

CmaEsSampler blog [recommends](https://medium.com/optuna/introduction-to-cma-es-sampler-ee68194c8f88) writes: "CMA-ES is particularly useful when the evaluation budget is moderate to large (> 100 x the number of hyperparameters)"

1) With multivariate TPESampler, what is the recommended number of evaluation budget versus the number of hyperparameters? Could this be documented?
2) Is the current best practice to use *multivariate* TPESampler followed by CmaEsSampler?
3) Could that information about budget from CmaEsSampler blog be added to the docs and maybe a code warning issued if that's not the case?

**Comment by turian** [comment]
Curious if there is any documentation or guidance on this>

We've been playing with high variance, big budget CMA-ES trials, and then evaluating the top-K using more precise estimates

**Comment by turian** [comment]
Related: https://github.com/optuna/optuna/issues/2622

**Comment by Crissman** [comment]
> 1. With multivariate TPESampler, what is the recommended number of evaluation budget versus the number of hyperparameters? Could this be documented?
This may vary significantly based on the data.

> 2. Is the current best practice to use multivariate TPESampler followed by CmaEsSampler?
Will vary on the data, and whether multivariate is appropriate.

> 3. Could that information about budget from CmaEsSampler blog be added to the docs and maybe a code warning issued if that's not the case?
Not sure the performance difference is strong enough to warrant a warning.

They're good questions, Turian. Unfortunately, we're haven't seen papers that provide recommendations on these, so it often comes down to having to try a few approaches and see which one works best.

If you have a paper or recommendation for this, please let me know. Otherwise, please close this issue for now.

Thanks!
