### ISSUE TITLE
Ask-and-Tell Many

### ISSUE THREAD

**Issue by parsiad** [optuna/optuna#2568]
## Motivation

Consider optimizing a function with the ask-and-tell interface:

```python
for _ in range(n_trials):
    trial = study.ask()
    f = func(trial)
    study.tell(trial, f)
```

Suppose that `func` is relatively cheap to compute and we have lots of resources available so that we can use many cores (100s or 1000s) to concurrently evaluate many trials. In this case, the **cost to query a networked database (e.g., Redis) on the `ask` and `tell` calls may greatly exceed the cost of evaluating the function**.

## Description

One possible solution is to introduce an API to "batch" `ask` and `tell` calls as follows:

```python
n_trials = n_batches * n_trials_per_batch
for _ in range(n_batches):
    trials = study.ask_many(n_trials_per_batch)
    fs = [func(trial) for trial in trials]
    study.tell_many(trials, fs)
```

## Alternatives (optional)

I have tried increasing the number of threads in Redis but the issue remains.

## Additional context (optional)

Some questions for Optuna developers and contributors:

1. Does such a feature already exist?
2. If not, is it feasible to implement? I am happy to implement it myself if someone more experienced with the codebase can comment on its feasibility.
3. Can you improve upon my API proposal of `ask_many` and `tell_many`?

**Comment by HideakiImamura** [comment]
Thanks for the interesting suggestion. Personally, I think it's a very interesting feature, but I'm wondering if it will actually contribute strongly to speed improvement. The proposed batch ask-and-tell implementation itself looks simple, so I think some speed benchmark results with use cases that you actually find useful would help the discussion for inclusion in Optuna itself. Can you do a quick prototype and have it benchmarked? (If you don't have time, I can make it contribution-welcome so that others can work on it.)

Also, FYI, the following is a PR we discussed earlier for including batch evaluation in the optimize loop rather than ask-and-tell: https://github.com/optuna/optuna/pull/1729

**Comment by parsiad** [comment]
Thank you for the detailed response.

Unfortunately, making a benchmark to capture this scenario is hard: running it on a single machine will probably not induce Redis bottleneck. When I encountered this, I had many machines on a cluster simultaneously contributing to the same study.

In the meantime, I came up with a hack that works in my context. Namely, I create a single process that has a "master study". This process spawns many child processes across a cluster. Each child process runs its own copy of the master study locally and only "merges" new trials back to the master study infrequently.

I'm not sure if I will have time to implement `ask_many` / `tell_many` in the near future, so please feel free to make it contribution-welcome (or close it, if you think it is not worthwhile). If I have time, I will try to revisit it at some point later this year.

**Comment by nickvazz** [comment]
Hello! I was curious if this has been implemented somewhere in a recent release. I have been using the `ask-tell` interface and find that eventually `ask` starts to become a bottleneck if I submit the params suggested. It starts taking 10-20 seconds per ask, is that expected for a study using a `TPESampler` parameter suggestion once the study has 5K+ trials?
