### ISSUE TITLE
Concurrency Support of CMA-ES Sampler

### ISSUE THREAD

**Issue by Turakar** [optuna/optuna#2574]
In the docs of the [CMA-ES Sampler](https://optuna.readthedocs.io/en/stable/reference/generated/optuna.samplers.CmaEsSampler.html#optuna.samplers.CmaEsSampler) one can find the following paragraph:

> Furthermore, there is room for performance improvements in parallel optimization settings. This sampler cannot use some trials for updating the parameters of multivariate normal distribution.

How severe is this "room for performance improvements"? I currently use TPESampler for tuning my VAE network, but I want to try CMA-ES because it looks very promising (esp. the restart mechanism to escape local minima). However, I use a GPU cluster with up to 4 parallel workers. Is this "too much parallelism"? When are trials not used for updating the multivariate normal distribution? Does this problem occur with a small amount of parallel workers or only with many parallel workers?

Thank you for your information :slightly_smiling_face: BTW: So far I really enjoyed your clean API design and the seamless parallelization support with just a single, easy to host RDB backend. The user attributes allowed for some really cool customization, too (e.g. storing the dataset identifier with each study). I :heart: your library!

**Comment by HideakiImamura** [comment]
Thanks for the question.

As far as I know, we haven't done any testing on parallelizing CmaEsSampler, so I can't say for sure. However, if the number of parallelisms is 4, as in your use case, then the performance degradation incurred by using the current implementation is not that significant. The performance degradation that the current implementation suffers is due to the fact that one process can only see trials that have already completed, and ignores information about trials that are running in other processes. If the number of parallelisms is 4, then there are only 3 trials that one trial will ignore, and this is not expected to have a significant impact in normal use cases where the number of trials is more than 100.

**Comment by Turakar** [comment]
Thank you for your helpful answer! Sounds like I should definitely try it out. So this means that there might be some redundancy in what the individual CMA-ES samplers explore concurrently? And this is not the case with the TPE sampler?

**Comment by Crissman** [comment]
All trials can see the history of completed trials in the common RDB, so the redundancy is only for the simultaneously running trials. TPE has the same structure for accessing processes as CMA-ES, so it has the same constraints around parallelism.

Please close this issue if that addresses your question.

Thanks,

**Comment by Turakar** [comment]
Thank you. I guess the limitations of TPE are partially lifted with the new constant liar feature.
