### ISSUE TITLE
Make `optuna.visualization.matplotlib.plot_contour` more beautiful

### ISSUE THREAD

**Issue by nzw0301** [optuna/optuna#2738]
## Motivation

`plot_contour` with Matplotlib backend looks different from one with Plotly backend. 

## Description

As shown in https://github.com/optuna/optuna/pull/2712#pullrequestreview-679629017, we can improve a plot generated by using `optuna.visualization.matplotlib.plot_contour` by following points:

- [ ] smoother contour lines
- [ ] fill blank area

**Comment by xadrianzetx** [comment]
Hi, I've found which algorithm is used in Plotly to interpolate `z` matrix.  This should cover

* blank areas
* smoother plotly-like contour areas (although it's only partially due to algorithm)

I will also tackle `xrange` and `yrange` problem mentioned in review.

I've ported this algorithm from JS to Python already, so please give me few days (hopefully) and i will open PR for this :^)

**Comment by nzw0301** [comment]
@xadrianzetx  Wow! Awesome! I'm looking forward to your pull request!
