### ISSUE TITLE
[RFC] Improve sampler test coverage

### ISSUE THREAD

**Issue by hvy** [optuna/optuna#2741]
## Motivation

Prevent future bugs such as https://github.com/optuna/optuna/pull/2739 by adding more unit tests for samplers.

## Description

Sort out all scenarios samplers should be able to handle, i.e. conditional parameters. Add tests.

**Comment by hvy** [comment]
Refactoring in general should not change the behavior or algorithms. It might be worth considering adding tests with fixed seeds that check/assert the values of `best_params`. That way, we could get rid of some of the tests that are testing private interfaces such as the current tests for the TPE sampler.

**Comment by toshihikoyanase** [comment]
I'm interested in this issue.

> Sort out all scenarios samplers should be able to handle, i.e. conditional parameters. Add tests.

I came up with the following scenarios:
- A single parameter
- Conditional parameters
- Combination of different types of parameters
- Changing the range of `suggest_int` or `suggest_float`

I'd like to add test cases corresponding to them. Maybe I can parametrize the objective functions.

> It might be worth considering adding tests with fixed seeds that check/assert the values of `best_params`.

I guess such test cases have both pros and cons, and I'd like to exclude this from my PR.
It will increase the maintenance cost of the test. Actually, we needed to change the test case when we updated the Optuna version from v2.4.0 to v2.5.0 or later (https://github.com/facebookresearch/hydra/pull/1726/files#r673470375). This is due to the introduction of  the search space transform (https://github.com/optuna/optuna/commit/5db7b5bc0b1442d5429b7ba816e4f4271ef94b94#diff-98431f6c0563769a069980db67d10bde2830661626057a8e69ba3e46f8e98ed4), and I think it may be costly to find the cause of the test failure.

Alternatively, we can check the change of `best_values` / `best_params` using benchmark suites like kurobako. It is not an easy task to automate benchmarking as we tried it in https://github.com/optuna/optuna/pull/2543, but I feel it is a straight forward way to check the performance using the benchmark.
