### ISSUE TITLE
The example code using visualization module.

### ISSUE THREAD

**Issue by take0212** [optuna/optuna#2765]
I made the example code to save all graphs to files using visualization module.
All slices and all contours are included in all graphs.
It may be useful for users who don't use dashboard.

https://github.com/take0212/optuna-example

**Comment by nzw0301** [comment]
Thank you for your feature request! I'm not sure why users cannot use the dashboard because it requires minimal dependency and doesn't depend on an external library such as MySQL. Could you elaborate a little bit more about it?

**Comment by take0212** [comment]
I agree that dashboard is very useful and the theory is to use dashboard.

As a rare need, users are sometimes happy to confirm graphs on file system without dashboard. This is the case when they have many .db files and want to confirm graphs immediately.

I wrote the sample code, so I shared it with other.
I chose 'feature', because there was no other suitable option.

**Comment by nzw0301** [comment]
Cool! Thank you for sharing it. I think this issue can be closed since it is not a feature request as you clarify.

As a side note, we already provide the [example codes for visualisation functions](https://github.com/optuna/optuna-examples/tree/main/visualization). In addition, saving plots is based on external backends API: plotly or matplotlib.

**Comment by take0212** [comment]
Thank you for your reply.

Your sample code is the main sample code.
I implemented a few improvements.

- Output each contour / slice graphs for combinations of all parameters.
- Specify plotly or matplotlib at once.
