### ISSUE TITLE
Is there any way to prune a trial with multi-objective study?

### ISSUE THREAD

**Issue by rsek147** [optuna/optuna#2792]
Not implemented: https://github.com/optuna/optuna/blob/master/optuna/trial/_trial.py#L569-L572

Do you have a plan to do this?

**Comment by nzw0301** [comment]
Hi, thank you for asking the question! Such functionality is definitely interesting but a well-known algorithm might not exist yet in the machine learning community as far as I know. Do you know any pruning algorithm for multi-objective?

**Comment by jeremycochoy** [comment]
Just ran into the `NotImplementedError` of `should_prune`. Even if there is no "pruning algorithm for multi-objective" in the literature, I would be really pleased by the possibility to prune according to a single objective (PercentilePruner) or even both objective (PercentilePruner condition met on all objectives).

Also, having an exception on the should prune is a bit disturbing, as I had to go to the source code of should_prune and simple guard my call with a copy past of the `len(optuna_trial.study.directions)` check... 😅 

I am really tempted by hacking a very naive implementation that could suit my simple usage, and I think it make more sense if I make it available for all optuna users. How would you write this? What about a pruner wrapper that would project on the `n` coordinate of the objective function so that it enable access to all existing pruners?

**Comment by rsek147** [comment]
I think if determining whether the trial is pareto front before the end of the trial, it is possible to prune it. But I don't know how to implement the algorithm...

**Comment by jeremycochoy** [comment]
You can say that if it is bellow (for the partial order on n-uplets) existing trials, then it is not pareto front (at the given iteration you are comparing scores, of course) and you could prune it.

**Comment by y0z** [comment]
The following paper proposes a pruning algorithm for multiobjective optimization.
https://ml.informatik.uni-freiburg.de/papers/21-ARXIV-BBMoNASHPO.pdf

**Comment by simpsus** [comment]
I also just ran into this error. In Single objective optimization, the trial.should_prune() is the main reason a lot of unnecessary trials are skipped. With multi-objective, that is simply not available.

Even something very trivial that would say for the median pruner:
If both values are below their respective median ==> prune
Would help a great deal

**Comment by PfeifferMicha** [comment]
I'd like to re-open this discussion. MO pruning seems like an important feature...

I'd also like to add another vote for any very simple pruning strategy ("all values meet the single-value pruning criterion individually" or "one of the values meets the pruning criterion").

**Comment by simpsus** [comment]
It would even be a start if trial.report would support multiple values. What I have resorted to is reimplementing the storing of trial values ...

**Comment by gitpeblo** [comment]
> Hi, thank you for asking the question! Such functionality is definitely interesting but a well-known algorithm might not exist yet in the machine learning community as far as I know. Do you know any pruning algorithm for multi-objective?

May this publication help?
https://www.sciencedirect.com/science/article/pii/S0360835222000924?casa_token=eXi9ztoLHFcAAAAA:pYpXMbWzTNoaw-etvWzLi1caxWwZEJlXU3bWfCwbhNCa8FnMsHMNZqcVq3kN6Ji0KZwFG0HdDQ

**Comment by kleag** [comment]
A lot older but maybe interesting too? Some papers from Sudeng et al. are cited in the paper referenced to by @gitpeblo but not this one:
https://ieeexplore.ieee.org/document/6567322
