### ISSUE TITLE
KerasPruningCallback gets depricated, then what?

### ISSUE THREAD

**Issue by flugenheimer** [optuna/optuna#2842]
I am using tf.keras to create my model, and from the examples I can see, I can use KerasPruningCallback (originally intended for keras standalone) 
https://github.com/optuna/optuna-examples/blob/main/keras/keras_integration.py

From the warning I get, and what I can read here, it gets deprecated at some point. However I am not able to find what the alternative is?

**Comment by nzw0301** [comment]
short answer: Please use [`TFKerasPruningCallback`](https://optuna.readthedocs.io/en/stable/reference/generated/optuna.integration.TFKerasPruningCallback.html) instead of `KerasPruningCallback`.

I certainly agree with the unclear deprecated message. it would be great to suggest using `TFKerasPruningCallback`.

**Comment by flugenheimer** [comment]
@nzw0301: Great! thank you for the quick reply. And I agree that having the suggestion of TFKerasPruningCallback in the warning message would be nice. Also updating the examples to tf.keras would have helped as well.
