### ISSUE TITLE
[Question] When is a run determined to be crashed for the purpose of future hyperparameter searches?

### ISSUE THREAD

**Issue by jkterry1** [optuna/optuna#2908]
Per a downstream [issue](https://github.com/DLR-RM/rl-baselines3-zoo/issues/160):

Right now I'm running 16 distributed optimization runs for on GCP. For whatever reason they've seized for 2 days and I have to reboot the systems. Will these searched hyperparameters count as a run that crashed due to instability (with None return), and in general what precisely will result in that state? I've been looking through the documentation to figure this out and can't,.

Could you please clarify (and possibly document) this behavior for us?

**Comment by nzw0301** [comment]
Sorry, could you explain a little bit more about the issue?

**Comment by fsmosca** [comment]
Trials that are started but crashed or interrupted will result in RUNNING state. Trial with RUNNING state is counted as trial run because that trial was started, the difference is now on the state, that is why there are [running, completed, pruned etc. states](https://optuna.readthedocs.io/en/stable/reference/structs.html#optuna.trial.TrialState).

Be aware of the FAIL state, I have never encountered this on my local tests and have never tried in GCP.

A trial is said to be [finished when the state is not running and not waiting](https://optuna.readthedocs.io/en/stable/_modules/optuna/trial/_state.html#TrialState). This would mean that completed, pruned and fail states are finished trials. But perhaps a trial with fail state is not a finished trial and the code can be revised to:

```python
    def is_finished(self) -> bool:

        return self != TrialState.RUNNING and self != TrialState.WAITING and self != TrialState.FAIL
```

**Comment by not522** [comment]
There are two cases where the trial state becomes `FAIL`.

1. The objective function returns a non-numerical value (e.g. `None`)
2. The objective function raises an exception other than `TrialPruned`

If the process immediately stops, the state remains `RUNNING`. When you restart optimization, the remaining trial has almost no effect on the optimization. (And you can restart the trial from the saved model. See this example. https://github.com/optuna/optuna-examples/blob/main/pytorch/pytorch_checkpoint.py)

----

The `FAIL` state is considered as finished because the trial will not be changed anymore. Actually, even after the process is stopped and the trial remains `RUNNING`, users can submit the objective value using the `tell` method.
