### ISSUE TITLE
[RFC] Drop Python 3.6 support

### ISSUE THREAD

**Issue by himkt** [optuna/optuna#3021]
We will gracefully stop the support for Python 3.6 after the EOL (23 Dec 2021).
https://devguide.python.org/#branchstatus

For now, we are not going to force users to upgrade Python (i.e. we currently don't have a plan to update `python_requires` to be `>=3.7` immediately after EOL). However, third-party libraries drop/will drop Python 3.6 before/after EOL and these may cause problems when using Optuna. We'll gradually stop dealing with such problems and will recommend users upgrade their Python.

**Comment by not522** [comment]
We decide to stop Python 3.6 support for integrations and optuna-examples but keep supporting it in pure Optuna uses. It means that we will remove Python 3.6 tests from the CI of the integrations and the examples but remain in the other CIs.

The maintenance cost of testing Python 3.6 with third-party libraries is increasing because some of them have stopped supporting Python 3.6. However, some Optuna users still use Python 3.6, and then we do not update `python_requires` to be `>=3.7` now.

**Comment by not522** [comment]
I think we have completed all tasks that need to be done now. When Python 3.6 will be the blocker to introduce new features or refactor codes, we will go back here and discuss dropping the Python 3.6 support.

**Comment by not522** [comment]
We decide Optuna v3.0.3 (the latest release) is the last version supporting Python 3.6. Working on #4150.
