### ISSUE TITLE
propose most promising points for next evaluation

### ISSUE THREAD

**Issue by nvelden** [optuna/optuna#3031]
Would it be possible with optuna to retrieve the sampling points before a trial starts? I would like to just retrieve  the best suggestions to find the minimum/maximum of a function without running the trial. Ideally, I would like  not only the best sampling point but for instance the top  5 or 10.
The reason I am asking is because in many applications (material design, pharmaceutical development) points need to be experimentally determined first before the function can be refitted.

**Comment by toshihikoyanase** [comment]
Hello @nvelden . Thank you for your question.

Optuna requires a trial to sample points by design, so it does not provide such APIs.

If you can accept the trial creation, [`Study.ask`](https://optuna.readthedocs.io/en/stable/reference/generated/optuna.study.Study.html#optuna.study.Study.ask) might help your task since you can get suggested parameters outside objective functions. The built-in samplers do not use the `RUNNING` trials without objective values, so you can simply ignore the not uninteresting trials.

In addition to that, you can keep the history clean using `optuna.copy_study`. Before calling `study.ask`, a copied study is created from the original study and the copied one is used to create trials. Note that this approach repeatedly copies all history, so please take care of the load of your storage (e.g., RDB queries).

```python
def get_suggestion(study, n_suggestions, search_space):
    copied_study = optuna.create_study()
    optuna.copy_study(from_storage=study._storage, to_storage=copied_study._storage, from_study_name=study.study_name)
    suggestions = []
    for i in range(n_suggestions):
        trial = copied_study.ask(search_space)
        suggestions.append(trial)
    return suggestions

candidates = get_suggestion(study, 5, search_space)
for t in candidates:
    print(t.params)
study.enqueue_trial(params=candidates[2].params)
study.optimize(objective, n_trials=1)
```

You can see a working example in [this notebook](https://colab.research.google.com/drive/1EwTwgg2SnIZK0sVQF55hbuN3JryFsUnD?usp=sharing).
