### ISSUE TITLE
Using constraints with ask/tell interface

### ISSUE THREAD

**Issue by alexis-intellegens** [optuna/optuna#3099]
Using the NSGAII sampler with the ask/tell interface I'm looking for a simple way to incorporate constraints.

I am currently using ask() to get trial IDs and suggestions, then computing the objective externally and using tell() to give them back. Where in this process should I compute and return the constraint evaluation?

Maybe I can do something like:

`optim.study.trials[0].set_user_attr("constraint", 2)`

Note: the above line of code doesn't seem to work at all. It doesn't throw an error but it also doesn't actually set user_attrs :(.

From the examples it seems I can set an attribute? Should this be done before tell? Should I ask the study to set the constraint attribute for trial N, then return trial Ns objective?

**Comment by alexis-intellegens** [comment]
Cheers, I forgot you could return the trial in study.tell, I'll do that.

**Comment by F18** [comment]
I have a follow-up question on this same topic. I am using the ask-and-tell interface to ask Optuna for a set of trial parameters (for a given batch size). I then store the trial parameters and numbers and pass them to the objective function to evaluate the entire batch of runs in one-shot (i.e. one call to `evaluation()`). This returns all the objectives and user attributes for the entire batch. 

After evaluation, I loop through the trial numbers to tell Optuna about the objective values associated with each trial number (using `int` values for the Trial, not `Trial` objects) . In this scenario, how can I also tell Optuna about the user attributes that were evaluated in the batch of runs?

```Python
study = optuna.create_study()

# generate all trials and suggest a hyperparameter
trial_list = []
trial_numbers = []
for _ in range (batch_size):
    trial = study.ask()
    param = trial.suggest(...)
    trial_list.append(trial.params)
    trial_numbers.append(trial.number)

# evaluate entire batch with a single call to evaluation()
val_metric, user_attr_1, user_attr2 = evaluation(trial_numbers, trial_list)

# report
for trial_number in trial_numbers:
    study.tell(trial_number, val_metric[trial_number])
```

When reporting, I do not know how to access the trial objects in order to set `user_attr_1` and `user_attr_2`. Any suggestions?
