### ISSUE TITLE
Optuna reproducibility between dockers with different Python versions

### ISSUE THREAD

**Issue by snassimr** [optuna/optuna#3202]
I have some code uses optuna and it runs on docker with Python 3.6 . I get same results for two subsequent runs for docker Python 3.6 and docker Python 3.8  but there are some differences between results come from two dockers.
If any seed can be set to ensure same results between two dockers ?

### Environment

- Optuna version: 2.5.0 for both dockers
- Python version: Python 3.6 and Python 3.8 as explained above
- OS: Centos 7 for both dockers
- numpy 1.19.5 for both dockers

**Comment by nzw0301** [comment]
Hi, could you share minimal reproducible codes with us?

**Comment by Blaizzy** [comment]
Hey @snassimr,

Yes, you can set the same seed value on the script that runs on both containers. That should do it, but it's a bit hard to know for sure what is your use case without looking at a minimal reproducible code.

**Comment by snassimr** [comment]
Hi , the difference has bean caused by different sklearn versions in two dockers . After I aligned two of those - I got same results as expected.

**Comment by Blaizzy** [comment]
Great!

Do you mind sharing what was your use case for the two containers? In order words, what kind of problem you are tackling(i.e. NLP, CV etc) and how?

**Comment by snassimr** [comment]
I am tackling classification task on tabular data . One container (Python 3.6) is old and doesn't allow its extension with latest packages that support >= Python 3.7. Python 3.8 has been created to allow such extensions.

**Comment by Blaizzy** [comment]
That's great! 
By the way, I found this article that might be useful to you in regards to tackling classification on tabular data: https://neptune.ai/blog/tabular-data-binary-classification-tips-and-tricks-from-5-kaggle-competitions

> One container (Python 3.6) is old and doesn't allow its extension with latest packages that support >= Python 3.7. Python 3.8 has been created to allow such extensions.

Just to make sure I understood you properly, do you mean that you are using packages whose latest versions are only supported in Python 3.7 and above? If so, which ones?

Finally, what made you want to have the same result in both containers? Is it because you wanted to later replace the old container(3.6) with the new container? keep both? or something else?
