### ISSUE TITLE
Are user_attrs used by the optimizers during optimization

### ISSUE THREAD

**Issue by eafpres** [optuna/optuna#3236]
### Environment

- Optuna version: 2.1.0
- Python version: 3.8
- OS: Linux (Ubuntu 20.04)
- (Optional) Other libraries and their versions:

Are values that are user_attrs used in the optimization or only the ones managed by trial.suggest()?

### Error messages, stack traces, or logs

```shell
None
```

### Steps to reproduce

None

**Comment by nzw0301** [comment]
I think `user_attrs` and `system_attrs` are not used for optimisation. Only 
[`optuna.integration.OptunaSearchCV`](https://optuna.readthedocs.io/en/stable/reference/generated/optuna.integration.OptunaSearchCV.html) uses a `user_attrs` internally to store optimisation results, so it might affect optimisation, but that will be fixed in the near future.

**Comment by eafpres** [comment]
@nzw0301 Thank you for the clarification.
