### ISSUE TITLE
Load older optuna dumped study 

### ISSUE THREAD

**Issue by MNFuad** [optuna/optuna#3243]
### Environment

- Optuna version: 2.10.0
- Python version:3.8.12
- OS:Linux (ubuntu)

### Error messages, stack traces, or logs

```shell
When trying to load a previously dumped study with optuna 2.10.0, it returns the following error:

ModuleNotFoundError: No module named 'optuna._study_direction'


I tried to downgrade the optuna to, 2.9.1, 2.9.0, 2.8.0, 2.7.0, and 2.6.0. However, I am still unable to load the saved pickle study. It shows a pickle CLS related error now,

TypeError: __new__() missing 1 required positional argument: 'multivariate'
```

### Steps to reproduce

To reproduce,
1. Try to create study with older optuna version, dump it to pickle file. 
2. Install a newer optuna version, and try to reload the dumped study. 

I believe this issue is well known with optuna,. What I want to know, is it possible to find the optuna version from the dumped study, so that I can reinstall the proper optuna version to read/load the old study? Is it a problem of optuna only or it also requires to downgrade other packages, such as pickle ... etc?

**Comment by himkt** [comment]
Hello @MNFuad, please use RDB to save/load a study.
https://optuna.readthedocs.io/en/stable/tutorial/20_recipes/001_rdb.html#sphx-glr-tutorial-20-recipes-001-rdb-py

We provide a migration script from older versions of Optuna to the latest:

```sh
optuna storage upgrade --storage <URL to the storage, e.g. sqlite:///example.db>
```

As far as I know, there is no easy way to identify the version of Optuna that created a study because study object doesn't contain a version information.

**Comment by MNFuad** [comment]
Thank you so much. 
True, I have solved the problem by downgrading the joblib to 1.0.1, then covert the .pkl files to RDB.

**Comment by himkt** [comment]
I'm happy to hear that. Let me close this issue but feel free to reopen if you need.
