### ISSUE TITLE
How is search space for group TPE sampler infered?

### ISSUE THREAD

**Issue by igrekun** [optuna/optuna#3325]
### Environment

- Optuna version: 2.10.0
- Python version: 3.8.12
- OS: Linux-5.16.10-arch1-1-x86_64-with-glibc2.2.5
- (Optional) Other libraries and their versions:

### Description

Suppose one has a search space where one parameter depends on the other. Minimal example is provided in "steps to reproduce".

Optuna 2.8.0 doesn't warn independent sampling but 2.10.0 does for this example.

What would be the best way to incorporate constraints / dependencies between parameters in Optuna while maintaining multivariate sampling? I suppose there could be a hack to select maximum covering space for myfloat2 but then how to enforce constraints?

### Error messages, stack traces, or logs

```shell
The parameter 'myfloat2' in trial#106 is sampled independently instead of being sampled by multivariate TPE sampler. (optimization performance may be degraded). You can suppress this warning by setting `warn_independent_sampling` to `False` in the constructor of `TPESampler`, if this independent sampling is intended behavior.
```

### Steps to reproduce

```python
tpe_sampler = optuna.samplers.TPESampler(multivariate=True, group=True)
study = optuna.create_study(sampler=tpe_sampler, direction='maximize')
for i in range(500):
    trial = study.ask()
    myfloat = trial.suggest_float("myfloat", 1.0, 2.0)
    myfloat2 = trial.suggest_float("myfloat2", myfloat, myfloat+5.)
    study.tell(trial.number, random.random())
```

**Comment by nzw0301** [comment]
@HideakiImamura  could you take a look at this PR?

**Comment by HideakiImamura** [comment]
@igrekun Thanks for the question. This is the expected behavior and this is not just a TPE problem.

In Optuna, the relative sampling is done when the trial is created, building the search space based on the past history. The search space that is constructed is determined by the Distribution given at the time the parameter was first sampled. Therefore, if the search space changes dynamically from trial to trial, as in the provided code, `[myfloat, myfloat+5]`, which is determined by the value of `myfloat` sampled in the first trial, is used as the domain for `myfloat2`. The search space used in this relative sampling will not be changed in subsequent trials. 

Based on this search space, relative sampling is performed when the trial is created, and the line `myfloat2 = trial.suggest_float("myfloat2", myfloat, myfloat+5.)` checks if the value sampled by relative sampling checks if the sampled value is in [myfloat, myfloat+5] for the value of `myfloat` sampled in this trial. If it is, the value determined by relative sampling will be used as is, otherwise independent sampling will be called to resample it.

This is why sometimes `myfloat2` is determined by independent sampling. This mechanism has been in place since the introduction of relative sampling in TPE (v2.2.0).

And as for why warnings were not sent in 2.8.0, this is because the logic for sending warnings has been fixed in v2.9.0. Specifically, until 2.8.0, the logic that sends out the warning was in the function that builds the search space, but since 2.9.0, it is at the beginning of the independent sampling. The reason why we made this modification to the logic is that we want to let users who are using dynamic search space (that's @igrekun  right now!) know that relative sampling is not always possible in that case.

Does this answer your question?

**Comment by HideakiImamura** [comment]
See https://github.com/optuna/optuna/blob/v2.8.0/optuna/samplers/_tpe/sampler.py#L296 for the logic for sending warnings until v2.8.0.
Also, see https://github.com/optuna/optuna/blob/master/optuna/samplers/_tpe/sampler.py#L413 for that of now.

**Comment by igrekun** [comment]
Thanks, that answers the issue!

Have you looked into implementing maximum covering search space at the time of trial? I quickly looked through the code and that looked not so complex. The unclear part is enforcing constraints so that value actually falls into required region and not the maximum covering space.
