### ISSUE TITLE
Simpler parallelism Idea

### ISSUE THREAD

**Issue by profPlum** [optuna/optuna#3328]
### Motivation

Current multiprocessing parallelism is overly & unnecessarily complicated IMO and due to extra complexity (reliance on sockets & non-python binaries) is more likely to fail (e.g. as it did for me) & harder to setup.

Also this issue has been [brought up](https://github.com/optuna/optuna/issues/1232) [several times](https://github.com/optuna/optuna/issues/1480#issuecomment-1048363584) [in the past](https://github.com/optuna/optuna/issues/2950) and has yet to get a simple solution.

### Description

We can _just keep the memory in main process_ then map() (e.g. like multiprocessing.Pool.map()) the parameter 'suggestions' to the worker processes for evaluation. I'm sure that for most people the evaluation process is extremely expensive, so IPC overhead will be trivial compared to evaluation cost (these are hyper-parameters after all, implication is long training/evaluation process for each trial). Also hyper-parameters supported by Optuna are all pickle-able.

This can leverage existing in-process-memory Optuna study and existing `joblib` pool as mentioned [here](https://github.com/optuna/optuna/issues/1480). **So in theory it should require very little effort to implement/maintain and then use.**

Only caveat is that user objective function will either need to not rely on global state (which is very common/best practice) or be ready to bootstrap any state initialization (e.g. global variables) from just pickle-able parameters passed to the objective function.

**Comment by himkt** [comment]
Hi @profPlum, thank you for the feature request! Are you interested in the contribution? It is difficult to work on it, but I'd love to review if you afford to (implementing a storage + testing it in a parallel situation).

**Comment by himkt** [comment]
Nice!

Currently, InMemoryStorage doesn't support multi-process execution. To support multi-process execution with InMemoryStorage, we will need share internal states across processes. For interprocess communication, we can use multiprocessing utilities (the existing PoC implementations seemingly use `multiprocessing.Manager`).

@hvy's PR: https://github.com/optuna/optuna/pull/2759
@sile's implementation: https://gist.github.com/sile/2c329d0cb38f35e25a8c7bab44edbb63 (it needs to some modification to work with the latest Optuna, but it is also the reference implementation)

I think we can implement a storage based on @hvy's PR (If PR is based on #2759, cherry-picking commits from the PR is good start point).

@hvy I'd like to hear tasks left in #2759. Are there some tasks that should be addressed in the PR? (The checkbox for `Test` is not checked, so we need to write tests for some cases?)

**Comment by hvy** [comment]
Thanks for mentioning, and the interesting discussion.

While I don't remember the exact details. let me leave some context around #2759, which I should've left as notes when closing the PR. 🙇 

One concern was really the design of the public API. How users would invoke the multi processing optimization. E.g. if the multi process storage would be instantiated by the user explicitly, or not. Also mentioned by @c-bata, adding an option to `Study.optimize` was controversial. `joblib` as also mentioned by the author here might be viable. If `joblib` indeed is viable, we can actually get rid of the `n_jobs` argument. On the other hand, we've noticed that this argument has been required by several users for its convenience.

Then, I recall that there was a discussion about serializability (pickling object for process forking). The `Study` is already designed to be serializable https://github.com/optuna/optuna/blob/release-v3.0.0-a2/optuna/study/study.py#L80-L90 but we also talked how the user provided objective functions must be (involving some complexity e.g. passing a lambda would fail since it cannot be pickled with the standard library pickle, etc.). This has to be communicated to the users in some pedagogic way, again depends on the design of the API. Python provides 3 different ways of multiprocessing with different defaults depending on platforms https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods.
If I remember correctly, not all of them involved object pickling and this lead to some additional concerns about the design and behavior. While most of this can be addressed via documentation, there were concerns to the overall introduced maintenance cost.

With that said, I'm curious how this can all be addressed. 
Especially the authors suggestion, how that differs from #2759, and how/if it can be implemented with "little effort".

**Comment by profPlum** [comment]
@hvy If it isn't obvious to you how simple my idea is to implement then I've failed in communicating it to you, let me provide pseudo code:
`
import multiprocessing as mp
import optuna as ot

def objective(cfg_dict):
    return cfg_dict['x']

# returns pickleable cfg dictionary
def suggest_trial_cfg(trial):
    return {'x': trial.suggest_int('x',0,1)}

if __name__ == "__main__":
    args = # ... 
    study = ot.create_study(*args) # create in memory study
    n = 8
    with mp.Pool(n) as p:
        for i in range(study.n_trials): # made up attribute
            trial_batch = study.get_batch_of_trials(n) # made up method
            pickleable_cfg_batch = [suggest_trial_cfg(trial) for trial in trial_batch]
            results_batch = list(p.map(objective, pickleable_cfg_batch))
            study.record_trial_batch(pickleable_cfg_batch, results_batch) # made up method
`

I don't think I can make the idea any more clear than that, and I'm not sure if this is the same as the other PR you linked but I'll let you be the judge now that you get the idea.

P.S. ignore the horrible design decisions in the psuedo code it is only to communicate an algorithm.

**Comment by profPlum** [comment]
@hvy  @himkt @divyanshugit So, what do you guys think?

P.S. @hvy is this similar to what you mentioned in your PR?

**Comment by himkt** [comment]
I really apologize that I'm inactive for a long time...

I think your proposal is related to batch optimization (https://github.com/optuna/optuna/issues/2660), samples multiple configurations at a time and evaluates an objective function for each config. It looks interesting and practical but I'm not sure if the idea will need to change the storage interface.

**Comment by profPlum** [comment]
@himkt The point isn't that it 'would require we change the storage interface'. The point is that if you implemented this _you could drop support for the current multiprocess storage system_ which relies on SQL (_not available on many HPC systems due to root requirements_), because it would become redundant. It would leave you with less dependencies, less complexity/code and the same functionality (assuming users where even able to get the previous multiprocess storage system working in the first place).

I think this idea could synergize with batch optimization. But they aren't very much related otherwise.

**Comment by himkt** [comment]
Thank you for the elaboration. I'm not confident I fully understand your idea but let me put another context.

> The point is that if you implemented this you could drop support for the current multiprocess storage system which relies on SQL

The benefit from RDB is also that we can optimize an objective function on multiple nodes that cannot communicate with each other. The current design enables us to run distributed optimization by exposing RDB to all workers (it's one kind of popular settings). I understand the HPC situation where it is difficult to install/operate RDB, but I don't think your suggestion replaces the all workloads of the scenarios.

If I misunderstand your idea and it's possible to use your proposed storage on multi-nodes (isolated each other) situation, please let me know. I want to discuss not only a 1:1:N (node:process:subprocess) parallelization but also a N:1:M (node:processes:subprocess) multi-workers parallelization.

**Comment by profPlum** [comment]
@himkt This should also be possible, just reasoning from first principles: you could use the disk to communicate across nodes. But there could be simpler solutions (e.g. if your job lib library supports IPC between nodes, or if you are using MPI).

**Comment by himkt** [comment]
> you could use the disk to communicate across nodes

Sharing a disk is not a good practice in the setting since we need to control exclusive locking (file locking doesn't work on NFS correctly 🔗 https://www.sqlite.org/faq.html#q5). I heard some NFS provides a locking mechanism but it depends on the system.

> your job lib library supports IPC between nodes
> you are using MPI

I think IPC/MPI is not possible when each worker (instance) cannot communicate each other and let me say again that it is one common scenario that you want to take care. It's important for us to provide a way of the distributed optimization for such scenario.

I really appreciate your passion and I understand SQL requirement doesn't fit on the HPC situation. But I still the improvement should be done for batch-optimization, not storage architecture.

@hvy @toshihikoyanase @g-votte @HideakiImamura Please add your thoughts if you have. I'm seemingly sticking my thought, but I don't want to stop exploring the possibility of the improvements.

**Comment by frobnitzem** [comment]
As an observer looking at the n_jobs situation while trying to get the SQL solution to work across multiple nodes on HPC - each with multiple GPUs running multiple trial evaluations concurrently, I have two comments.

1. `optuna/study/_optimize.py` implements a "bag of tasks" model that should be provided by some external utility that the user can interact with.  It's nice to know what trials are running and where, and ideally optuna wouldn't have to manage that functionality.

2. `optuna.Study` is the natural place for optuna to serialize things using a client/server model. Consider a parallel model where one process holds the authoritative "Study" and all other processes hold a "StudyProxy".  StudyProxy objects communicate with the Study to increment the trial number and update best objectives, etc.

As a user, I would like to be able to call `optuna.Study.ask()` from inside any parallel construct and trust that I will be given an `optuna.Trial` that is local and unique.  Then I can use external parallel methods.
