### ISSUE TITLE
bootstrap_count does not work in SuccessiveHalving 

### ISSUE THREAD

**Issue by filthysocks** [optuna/optuna#3330]
### Expected behavior

In SuccessiveHalving there is the bootstrap_count parameter which should:

>  bootstrap_count:
            Minimum number of trials that need to complete a rung before any trial
            is considered for promotion into the next rung.

If set to a value > 0 (default is 0), then it will prune every trail after the first epoch.

The problem is easy to fix (from the SuccessiveHalvingPruner.prune method):
``` python
            # 'competing' already includes the current trial
            # Therefore, we need to use the '<=' operator here
            if len(competing) <= self._bootstrap_count:
                return True
```
It should return False, not True. 

`len(competing)` is the number of current trial. So it is > 0. `_bootstrap_count` is 0 by default, if increased the expression evaluates True, which prunes the trial. The expected behavior would be to continue until `_bootstrap_count` many trials have a result in the rung.

### Environment

- Optuna version: 2.10.0
- Python version: 3.7.5
- OS: linx
- (Optional) Other libraries and their versions:

### Error messages, stack traces, or logs

```shell
Trial 0 pruned. Trial was pruned at epoch 1.
 Trial 1 pruned. Trial was pruned at epoch 1.
 Trial 2 pruned. Trial was pruned at epoch 1.
etc...
```

### Steps to reproduce

1. setup any objective
2. use SuccessiveHalvingPruner as pruner
3. outcome: every trial is pruned after first epoch
```python
study = optuna.create_study(
    pruner=SuccessiveHalvingPruner(bootstrap_count=1, min_resource=1),
)
study.optimize(objective, n_trials=10)
```

**Comment by rsnitsch** [comment]
I can confirm this bug.

**Comment by toshihikoyanase** [comment]
Thanks for your report! Let me check.

**Comment by toshihikoyanase** [comment]
I talked with @sile and @himkt and found that this was not a bug.

As the PR https://github.com/optuna/optuna/pull/1945 that introduced `bootstrap_count` mentioned, the option is used to prune (at least) `bootstrap_count` trials in each rung.

> This is particularly an issue in serial runs, as the initial run will just continue forever.
>  A new setting is introduced, which specifies a number of trials which must have terminated in a rung before any trial can be promoted into the next rung.

According to the description, `prune` is supposed to return `True` to terminate trials if the number of the current rung is not greater than `bootstrap_count`.

https://github.com/optuna/optuna/blob/8d78436c079493f96337d5b1c5af18ead1f84053/optuna/pruners/_successive_halving.py#L200-L203

In addition, I checked that trials are not pruned if the number of trials in a rung exceed `bootstrap_count` in [the notebook](https://colab.research.google.com/drive/1Y604KclQQ9PSnLVp8ffjE2zvmIWnV_kg?usp=sharing). Please take a look.

The objective values monotonically decrease when trial numbers increase. Which means that no trials should not be pruned since every trial updates the best.

```python
import optuna

def objective(trial):
    x = trial.suggest_float('x', 10 - trial.number, 10 - trial.number)
    for i in range(1, 10):
        trial.report(x / i, step=i)
        if trial.should_prune():
            raise optuna.TrialPruned()
    return x / 10

study = optuna.create_study(
    pruner=optuna.pruners.SuccessiveHalvingPruner(bootstrap_count=1, min_resource=1),
)
study.optimize(objective, n_trials=10)
optuna.visualization.plot_intermediate_values(study)
```

The intermediate values plot is as follows:

![image](https://user-images.githubusercontent.com/3255979/160839568-667e3d06-138b-4c22-bc6a-88530051f66b.png)

The 0th trial was pruned because it was the first trial of rung 0.
The 1st trial was pruned because it was the first trial of rung 1.
The 2nd trial and later were not pruned.

**Comment by himkt** [comment]
@toshihikoyanase answered the question. Let me close the issue.
