### ISSUE TITLE
Gotchas with the MaxTrialsCallback

### ISSUE THREAD

**Issue by ernestum** [optuna/optuna#3518]
### What is an issue?

The documented go-to solution to do distributed optimization for `n` trials independent of the number of workers is to use the [MaxTrialsCallback](https://optuna.readthedocs.io/en/stable/reference/generated/optuna.study.MaxTrialsCallback.html?highlight=MaxTrialsCallback). There are a number unexpected behaviors with this:

1. If you use the default `states` argument and run `m` workers on `n` trials, you will actually get `n + m` trials. This is because already running trials are not counted by default. This can be very confusing. Unfortunately just adding `TrialState.RUNNING` to the `states` list won't solve the issue for all cases: when you have stale trials you have to remove them by hand before adding more workers.

2. When you try to continue a study that already has the specified `n_trials`, each worker will add one more trial to the study even though it should not. This is due to the callback only being executed first _after_ the first trials has been executed.

3. If you enable pruning and don't include `TrialState.PRUNED` in the `states` argument, you might run into the issue that you workers keep running forever when all the new trials are being pruned. This should at least be documented.

**Comment by HideakiImamura** [comment]
Thanks for the raising this issue. It would be great if you give us a PR to fix this.

**Comment by nzw0301** [comment]
Hi in my understanding, actually a few problems in the issue description can be avoided by using Optuna's API or adding a few lines. Let me share them as follows.

> 1. If you use the default `states` argument and run `m` workers on `n` trials, you will actually get `n + m` trials. This is because already running trials are not counted by default. This can be very confusing. Unfortunately just adding `TrialState.RUNNING` to the `states` list won't solve the issue for all cases: when you have stale trials you have to remove them by hand before adding more workers.

By passing `None` as `states`, it would perform `m` trials in practice since this case callback cares all trial states including `RUNNING`. If we have stale trials in them, we can re-run them by using https://optuna.readthedocs.io/en/stable/reference/generated/optuna.storages.fail_stale_trials.html, which makes a trial state `FAIL` and https://optuna.readthedocs.io/en/stable/reference/generated/optuna.storages.RetryFailedTrialCallback.html, which retry the failed trial. So we don't need remove them by hand. 

> 2. When you try to continue a study that already has the specified `n_trials`, each worker will add one more trial to the study even though it should not. This is due to the callback only being executed first _after_ the first trials has been executed.

Yes, since this callback is called after the evaluation of the trial. Fortunately, this can be avoided by adding a few lines as follows:

```python
import optuna

study = optuna.create_study(storage="sqlite:///example.db", study_name="my_study", load_if_exists=True)

NUM_MAX_TRIALS = 100
num_current_valid_trials = len(study.get_trials(states=[optuna.trial.TrialState.COMPLETE, optuna.trial.TrialState.PRUNED]))
if num_current_valid_trials >= NUM_MAX_TRIALS:
    exit()
study.optimize(objective, n_trials=50, callbacks=[MaxTrialsCallback(NUM_MAX_TRIALS, states=None)])
```

Anyway, I agree to clarify the documentation as you suggested. Thanks!
