### ISSUE TITLE
PatientPruner incorrect operation with min_delta parameter

### ISSUE THREAD

**Issue by MBelniak** [optuna/optuna#3835]
### Expected behavior

Run should be pruned if performance is not improved in the last `patience` steps. min_delta determines improvement value treshold - if permormance did not improve this much, run should be pruned. 
Thus, for minimizing it should be:
```
maybe_prune = np.nanmin(scores_before_patience) - self._min_delta < np.nanmin(scores_after_patience)
```
and for maximizing:
```
maybe_prune = np.nanmax(scores_before_patience) + self._min_delta > np.nanmax(scores_after_patience)
```
But, it is implemented with +/- signs the other way round.

### Environment

- Optuna version: 2.10.0
- Python version: 3.8.2
- OS: Windows 10
- (Optional) Other libraries and their versions:

### Error messages, stack traces, or logs

```shell
N/A
```

### Steps to reproduce

For minimizing the objective, patience=2 and min_delta=0.05, run should be pruned for values e.g. 0.23, 0.22, 0.21, 0.2, 0.19 .
But:
```
min_delta = 0.05
should_prune = np.nanmin([0.23, 0.22, 0.21]) + min_delta < np.nanmin([0.2, 0.19])
print(should_prune)
```
prints `False`

Correct behaviour:
 ```
min_delta = 0.05
should_prune = np.nanmin([0.23, 0.22, 0.21]) - min_delta < np.nanmin([0.2, 0.19])
print(should_prune)
```
prints True.

### Additional context (optional)

I understand I might be wrong and min_delta means "how much performance can decrease until we prune", but it is confusing in my opinion.

**Comment by nzw0301** [comment]
As you said, this is not a bug. I think that another library uses the same word in the same way, e.g., https://keras.io/api/callbacks/early_stopping/. If you think the current explanation is not clear, please feel free to send a pull request to improve the part.

**Comment by MBelniak** [comment]
> As you said, this is not a bug. I think that another library uses the same word in the same way, e.g., https://keras.io/api/callbacks/early_stopping/. If you think the current explanation is not clear, please feel free to send a pull request to improve the part.
From Keras documentation:
"min_delta: Minimum change in the monitored quantity to qualify as an improvement, i.e. an absolute change of less than min_delta, will count as no improvement"
This supports my claim. My reproduction snippet shows exactly that as "Correct behaviour".

**Comment by nzw0301** [comment]
Hi, thank you for correcting my comment. You are right. The logic is not the same as keras.

**Comment by nzw0301** [comment]
Let me leave a background of this pruner. This pruner originally aimed to avoid aggressively pruning a trial as requested in https://github.com/optuna/optuna/issues/1447. So the current `min_detal` usage is supposed to be natural. 

At the same time, I understand that the current behaviour might mislead users since the `min_delta`'s usage is different from other popular libraries such as keras or pytorch ignite as an early stopping-ish pruner.

I'm not sure how to resolve this issue, but a possible solution might be to add a new boolean argument to decide the behaviour of `min_delta`?

**Comment by MBelniak** [comment]
How about allowing min_delta to be negative?

**Comment by nzw0301** [comment]
Sounds great! Such a change will not break the backward compatibility. One concern is that accepting both signs might confuse users too, so we carefully update the documentation.

**Comment by nzw0301** [comment]
I've changed my mind when I discussed this issue with other members. Even though this pruner might be equivalent to an early-stopping by-product when we introduced patient pruner, this pruner's original motivation differs from early-stopping. In addition, this pruner should not behave as an early-stopping because early stopping would be done by other libraries rather than the pruning mechanism in Optuna, since pruned trials are treated differently from complete trials as mentioned in https://github.com/optuna/optuna/issues/1647. Therefore I'd like to improve docs rather than change the behaviour of PatientPruner.
