### ISSUE TITLE
Please add some explaination on how to configure the TPE Solver

### ISSUE THREAD

**Issue by leo-hstone** [optuna/optuna#3907]
### What is an issue?

In my recent studies with optuna I have niticed that the solver focuses too much on a local minumum. I wonder how I can configure the TPE solver to focus more on exploration.

I am an engineer and not a scientist - as others I don't have the time to fully understand the TPE algorithm. 
A few words in the documentation on how to tune the solver in a desired direction would be very beneficial!

**Comment by FrankwaP** [comment]
Increasing `n_startup_trials` looks like what you're looking for.

> `n_startup_trials` – The random sampling is used instead of the TPE algorithm until the given number of trials finish in the same study.


You could use the [GridSampler](https://optuna.readthedocs.io/en/stable/reference/samplers/generated/optuna.samplers.GridSampler.html) first (be careful since the number of combinations can get high really fast!), then continue the study with the TPESampler.
