### ISSUE TITLE
"parameter in trial is sampled independently instead of being sampled by multivariate TPE sampler" warning coming too late

### ISSUE THREAD

**Issue by PhilipMay** [optuna/optuna#4191]
### Expected behavior

I am running this colab:
https://colab.research.google.com/drive/1WNCgGxCZ1cxuRpXBPk1CxX46mu091YjP?usp=sharing

In the code I cange the HP space from `x = trial.suggest_float("x", -10, 10)` to
`x = trial.suggest_float("x", -10, 11)`.

This should trigger the warning. But does not. It triggers the warning when I load and run the study a 3rd time.

This is very strange and might be the indicator or an underlying bug. 

### Environment

- Optuna version:3.0.3
- Python version:3.7.15
- OS:Linux-5.10.133+-x86_64-with-Ubuntu-18.04-bionic
- using Colab

### Error messages, stack traces, or logs

```shell
see colab
```

### Steps to reproduce

see colab

**Comment by amylase** [comment]
You don't get this warning in the second run because the startup trials had not finished yet.

We suppress this warning during startup trials because we intentionally sample independently in startup trials.
https://github.com/optuna/optuna/blob/master/optuna/samplers/_tpe/sampler.py#L453-L456
https://github.com/optuna/optuna/blob/master/optuna/samplers/_tpe/sampler.py#L351
