### ISSUE TITLE
Combinatorial Optimization

### ISSUE THREAD

**Issue by deadsoul44** [optuna/optuna#4350]
### Motivation

New cma-es has better support for mixed integer spaces but often these kind of optimization problems are combinatorial optimization problems, i.e. the value of the objective function does not change when the order of input array changes. It is a waste of time to explore the remaining combinations.

### Description

This can be handled using low level api. When a trial is completed, it can be told to the optimizer that all the combinations of the input array have the same objective value. A new high level api can better handle these kind of situations.

**Comment by HideakiImamura** [comment]
Thanks for the proposal. Sounds great to enhance the CMA-ES for combinatorial setting, but it is not obvious to use the information that all the combinations of the input array the same objective value. Do you know any reference or concrete algorithms of that?

**Comment by deadsoul44** [comment]
I could not find a paper but you can have a look at how Google Vizier handles it:
https://oss-vizier.readthedocs.io/en/latest/guides/user/search_spaces.html#combinatorial-reparamterization

**Comment by Alnusjaponica** [comment]
It appears that Google Vizier provides just an example of user code to re-parametrize combinatorial search space as independent int search space since it is difficult to suggest permutations as they are. Although it does not seem to reduce computational cost as you insist, it would be very useful to document this kind of typical re-parametrization techniques.
