### ISSUE TITLE
#4376 breaks compatibility with old `colorlog`

### ISSUE THREAD

**Issue by contramundum53** [optuna/optuna#4403]
### Expected behavior

`import optuna` should not fail.

### Environment

- Optuna version:
- Python version:
- OS:
- (Optional) Other libraries and their versions: **colorlog v4.8**

### Error messages, stack traces, or logs

```shell
File ~/optuna/optuna/logging.py:36, in create_default_formatter()
     31 def create_default_formatter() -> colorlog.ColoredFormatter:
     32     """Create a default formatter of log messages.
     33 
     34     This function is not supposed to be directly accessed by library users.
     35     """
---> 36     return colorlog.ColoredFormatter(
     37         "%(log_color)s[%(levelname)1.1s %(asctime)s]%(reset)s %(message)s",
     38         no_color=False if _color_supported() else True,
     39     )

TypeError: ColoredFormatter.__init__() got an unexpected keyword argument 'no_color'
```

### Steps to reproduce

1.
```
$ pip install colorlog==4.8.0
```
2.
```
import optuna
```

### Additional context (optional)
Updating to the latest `colorlog` fixes this.

**Comment by gen740** [comment]
It's weird but colorlog have own `NO_COLOR` [implementation](https://github.com/borntyping/python-colorlog/blob/main/colorlog/formatter.py#L151-L162) which seems not working.
I think the best way to resolve this issue is to use this implementation.

**Comment by gen740** [comment]
I investigated this problem, `no_color` has been supported since [this commit](https://github.com/borntyping/python-colorlog/commit/fbba5ec42ef813017f5af4b7a73c3cf86952d665) (v6.0.0-alpha.1-3-gfbba5ec).

`colorlog`'s `NO_COLOR` implementation would not use if the `stream` key of ColoredFormatter is not set. And the `stream` key was supported since [this commit](https://github.com/borntyping/python-colorlog/commit/7ae0fc38139d7caa09662105b87ce616a5596d82) (v5.0.1-11-g7ae0fc3).

I will create the PR.

**Comment by keisuke-umezawa** [comment]
@gen740 Thank you for working on it.

**Comment by toshihikoyanase** [comment]
How about using `logging.Formatter` instead of `colorlog.ColoredFormatter` if `_color_supported` is `False`? I'm not sure if we need to stick to the functionally of `colorlog` to disable color formatting.
The following is just an example code.

https://github.com/optuna/optuna/compare/master...toshihikoyanase:optuna:use-logging-formatter-if-no-color?expand=1

**Comment by gen740** [comment]
Thank you for your nice suggestion! TBH, I just came up with the same idea.
