### ISSUE TITLE
[Feature Request] debug mode

### ISSUE THREAD

**Issue by yonatanMedan** [optuna/optuna#478]
Hi! first of all i want to say what a great job i thing you have done!
it's by far the easiest hyper parameter optimization lib out there took me minutes to implement in my project!

I noticed there is some mechanism which ignores Errors, which is great but turns out i was optimizing for hours and no experiment was complete, so i had to change the `catch` in `optimize()` method to some random specific error like `BufferError` as a workaround so i could debug the reason my objective function failed. 

would be nicer to have `optimize(debug=True)`

what do you think?

thanks!!!

**Comment by toshihikoyanase** [comment]
Thank you for using Optuna!

I also think that adding some sort of debugging features of `Study.optimize` will be helpful for users.

For instance, we plan to add a feature to stop optimization if many trials fail consecutively.
And also, we have received feedback related to the `catch` argument of `Study.optimize()` in #386. In the issue, he proposed to add `reraise=True/False` argument to control the error handling, and I think it helps users debug their objective functions.

Do you think such features can satisfy your demand for debugging?

**Comment by yonatanMedan** [comment]
I think it would,
Thx!

**Comment by toshihikoyanase** [comment]
Let me share the updates about this issue.

The default behavior of exception handling during `study.optmize` has been changed since v0.18.0. Optuna does not catch any exceptions by default (#637) and records all error raising trials as failures properly (#638).

IMO, these changes can replace `debug` or `reraise` options, so let me close this issue.
If you have any comments or questions, please reopen it or create a new issue.
