### ISSUE TITLE
Implement "best_model" attribute in optuna.study.Study

### ISSUE THREAD

**Issue by abdullahmoosa** [optuna/optuna#4800]
### Motivation

While working with optuna. After creating a study using optuna.create_study() and optimizing it using study.optimize() , I realized we can get the best model parameters using study.best_params and then use the parameters to create a model.
Suppose, 

```
best_params = study.best_params
best_params
```
best_param returns -> 
{'classifier': 'RandomForest', 'rf_n_estimators': 60, 'rf_max_depth': 25}

`randomForest = RandomForestClassifier(n_estimators = best_params['rf_n_estimators'], max_depth = best_params['rf_max_depth'])`

I think it can be simplified in a way if an attribute existed which returns the best model by creating the model using the best parameters. 

### Description

If a feature 'best_model' is implemented then it will return the best model using the best parameters. So, it will not be necessary to retrain the model as shown above.

`best_model = study.best_model`
Then we can fit the best_model to the training data.

**Comment by nzw0301** [comment]
Hi, thank you for creating feature request. 

Optuna supports block box optimisation, where the model is not always available. In addition, you don't need retrain the model given the best param because we can save the best model easily as explained in https://optuna.readthedocs.io/en/stable/faq.html#how-to-save-machine-learning-models-trained-in-objective-functions. So I'm not sure this feature is necessary in practice.

**Comment by abdullahmoosa** [comment]
Thank you for the suggestion and clarification!
