### ISSUE TITLE
Add an API to query a study by trial number

### ISSUE THREAD

**Issue by simpsus** [optuna/optuna#4828]
### Motivation

I run a study and afterwards I view the results in optuna dashboard and finally I want to train a few of those trials for future use. What do I use to identify a trial? the number! Now I have to do

`trial = [t for t in study.trials if t.number==number][0]`

because there is no 

`study.get_trial(number)`

method. Is it possible to add this?

### Description

included in motivation

**Comment by toshihikoyanase** [comment]
Thank you for your feature request.
You are using a list comprehension to iterate over all trials and select the trial with the corresponding number.  While this works fine and safely, it can be made a bit simpler by directly indexing into study.trials. Here's how you can do that:

```python
trial = study.trials[number]
assert trial.number == number
```

This is possible because trial numbers in Optuna start from 0 and increase monotonically. Therefore, the trial number corresponds to the index of the trial in `study.trials`.

**Comment by simpsus** [comment]
Thank you for your response.
Do you know if the assert is necessary, i.e. if trials are ever removed from this list?

I have a few large and complex studies. Loading all of those trials takes a long time. I assume with your method only one trial has to be read from the storage?

Please feel free to close the issue if there are no plans to do a dedicated API call to retrieve a trial by number.
