### ISSUE TITLE
Imporve colormap of optuna.visualization.plot_parallel_coordinate()

### ISSUE THREAD

**Issue by LiShaoyu5** [optuna/optuna#4868]
### Motivation

When I use optuna for multi-objective optimization and draw plots with optuna.visualization.plot_parallel_coordinate(), I found that the larger the target value, the lighter the color of the corresponding line, which is oppsite with single-objective optimization. Then I looked for [documentation](https://optuna.readthedocs.io/en/stable/reference/visualization/generated/optuna.visualization.plot_parallel_coordinate.html#optuna.visualization.plot_parallel_coordinate) and found this:

> The colormap is reversed when the target argument isn’t [None](https://docs.python.org/3/library/constants.html#None) or direction of [Study](https://optuna.readthedocs.io/en/stable/reference/generated/optuna.study.Study.html#optuna.study.Study) is minimize.

It's confusing that the colormap rules vary by single and multiple objectives and are independent of the optimization direction.

Besides, current colormap makes some of the lines difficult to recognize even in the example image of documentation because the background color is also white, especially when numbers of trials become large:
![image](https://github.com/optuna/optuna/assets/37066594/952ac33d-0511-4dea-b827-cfe47beba2ad)

### Description

Suggest to use colormap similiar to the function plot_rank(), which uses red and blue to differentiate data instead of white and blue:
![image](https://github.com/optuna/optuna/assets/37066594/89348aa8-8a4c-4e4f-8253-abf6e72aefff)

**Comment by contramundum53** [comment]
Thank you for your suggestion!

You can change your plot to your favorite color scale by the following code:
```
fig = optuna.visualization.plot_parallel_coordinate(study)
fig.data[0].line["colorscale"] = "RdYlBu" # Reverse color scale by "RdYlBu_r"
fig.show()
```

If more people want this, we can consider making it the default color scale. 
Let's have a vote here, if you think the color scale of `plot_rank` is better than the current `plot_parallel_coordinate`, please react by ❤️ . If you feel the opposite, please react by ☹️ .

**Comment by contramundum53** [comment]
The story for the curent behavior of the color is a bit long:

When we only had single-objective optimization, we first wanted to show good lines in dark colors and bad ones in light colors. It is by design that some lines (bad ones) can be difficult to see, since most of the times we would like to know what kind of parameters are good. 

Then there came multi-objective optimization. For multi-objective study, we must specify a `target` parameter (in most cases we'd like to color the lines by one objective value, but in general we may want to specify any combinations of objective values or even by an entirely different function). In that case, the `plot_parallel_coordinate` function cannot determine whether small values are good or large values are good, so we can only assume either of them. (Currently we assume the former.) This can result in an undesirable behavior where the good lines are displayed in light color rather than the bad ones. This (the visualization functions cannot obtain the direction of target function) is indeed a design issue in Optuna, but it may take time to solve this entire problem.

**Comment by LiShaoyu5** [comment]
> Thank you for your suggestion!
> 
> You can change your plot to your favorite color scale by the following code:
> 
> ```
> fig = optuna.visualization.plot_parallel_coordinate(study)
> fig.data[0].line["colorscale"] = "RdYlBu" # Reverse color scale by "RdYlBu_r"
> fig.show()
> ```
> 
> If more people want this, we can consider making it the default color scale. Let's have a vote here, if you think the color scale of `plot_rank` is better than the current `plot_parallel_coordinate`, please react by ❤️ . If you feel the opposite, please react by ☹️ .

Thank you for your reply and code example! It works well and I think adding this into documentation(maybe a short section for customizing figures or link to corresponding plotly doc?) will be helpful if most people don't think it's necessary to change default colormap individually.
