### ISSUE TITLE
Support tuples for Categorical values

### ISSUE THREAD

**Issue by Guillaume227** [optuna/optuna#4893]
### Motivation

I have a categorical variable taking tuples of integers. For example:
```
trial.suggest_categorical(name='my_var',  choices=[(100, 10), (10, 1)])
```

To be fair optuna warns me about using a tuple type:
```
distributions.py:524: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (100, 10) which is of type tuple.
```
But the study runs through and I am getting good sensible results.

However when I tried to use optuna-dashboard, I hit an exception:
```optuna/distributions.py", line 98, in __hash__
    return hash((self.__class__,) + tuple(sorted(self.__dict__.items())))
Exception: unhashable type: 'list'
```
I am using the journal NFS storage and I figured that the tuple value I am passing gets serialized to json and then deserialized to a list (the json format has no notion of tuple vs list and so python `json` module chooses to use lists, not tuples).

### Suggestion

A tuple of ints should have no ambiguity/problem with persistent storage. 

- A first suggestion would be to relax the categorical type check (at least as a warning)
- A second suggestion would be to adapt the `json_to_distribution` logic (in `optuna/distributions.py`) to convert lists to tuples for categorical distributions. I cannot think of any downsides / backward compatibility issue with such a change.

I am happy to send a PR for either or both if there is no push back.

**Comment by nzw0301** [comment]
> However when I tried to use optuna-dashboard, 

So this sounds like a dashboard issue, right? If so, https://github.com/optuna/optuna-dashboard would be another channel to resolve this issue.

**Comment by Guillaume227** [comment]
I came across that issue in the dashboard yes but the issue is related to persistent storage and that logic lives in optuna/optuna, which is whyI opened the issue here. Do you think the fix should go somewhere else than `optuna/distributions.py` that I suggested?

**Comment by contramundum53** [comment]
Sorry, tuples are not supported officially as categorical choices precisely because of this problem.

> adapt the json_to_distribution logic (in optuna/distributions.py) to convert lists to tuples for categorical distributions.
We would not like to introduce this additional complexity unless there is sufficient reason.

You can work around this problem by having the choices as a list yourself (possibly saving it in `study.user_attr` in your favorite format) and `suggest_categorical` the index of the choice.

**Comment by contramundum53** [comment]
Another option I came up with is to allow all `JSONSerializable` type as categorical choices and remove all usages of hashes in `optuna` and `optuna_dashboard`. I haven't thought through how hard this is.

**Comment by Guillaume227** [comment]
Thanks for taking a look @contramundum53! Thanks for the suggestion to use list index.
Trying to be more articulate about my thoughts in the light of your answers:
- JSON doesn't support pythons list any more than python tuples - it has an array type that can be mapped to either - that's up to the parent library to decide (optuna in the present case).
- Lists are mutable in python so are not a good choice for JSON serialization / categorical data representation. So optuna might as well decide to map tuples to JSON arrays. That's a consistent API story, not a hack. You have a point about 'why tuples and not `np.ndarray()`?' I would argue that built-in types like tuples should have an edge in that case. 
- I don't see backward compatibility issues since neither list or tuples are supported right now. 
- What additional complexity in terms of maintenance do you see? Maybe I am missing some aspect but it seems to me that pushing the list index work-around on to the user increases the net entropy of optuna code-bases and leaves some pythonic API goodness on the table.

Happy to close this if the above doesn't move you ;)

**Comment by contramundum53** [comment]
Thank you for your suggestion!

Actually I agree that the current restriction in the categorical types is too restrictive.
I went over optuna codebase and confirmed that it's actually possible to support all `JSONSerializable` types by modifying 10-30 lines of code (I haven't looked in optuna dashboard yet), so maybe I'll make a PR for it when I have time. (Of course it'll be very appreciated if you could write a PR for us!).

**Comment by contramundum53** [comment]
However, even then, I think we won't be supporting tuples but instead lists. I think it's a valid argument that tuples are better than lists because they are immutable, but the dicision has been made by the (_de facto_ standard) `json` library; By the principle of least surprise, I think we would go for the same convension with it rather than inventing our own convension. (Another reason for not using tuples for deserializing json is that there is no built-in `frozendict` in python.)

**Comment by contramundum53** [comment]
The story behind: Actually the usage of hashes have been removed in `optuna` in around v3.1 or so, because it is kind of buggy when you have `nan`s as keys. As a result, the only thing we need to change when supporting all types of values is `_categorical_choice_equal` function. Yay!

**Comment by contramundum53** [comment]
On the second thought and after a discussion with other dev members, we concluded that it is _very_ dangerous to use mutable data structures as categorical choices. For example, users could modify the suggested choice and it could blow up every cache system in Optuna and Optuna dashboard. (The DB has the json-serialized old version and samplers may or may not have the new version modified by user in the memory cache. Nobody knows what happens the next time you call `suggest_categorical`.)

Seemingly innocent tuples could also be dangerous. After having tuples as categorical choices, the users will almost certainly want "nested tuples" as the categorical choice type (e.g. `choices=[("foo", (1, 2.0)), ...]`). However, when you have such a deeply nested object, it will be tough to ensure the immutability of it. We will have to check all the way down to every leaf of the object. And we will have to implement this by our own, since `json` library will silently pass through unwanted `dict`s and `list`s.

Considering this complexity, we decided to instead keep the interface simple and let users keep their own index table like https://github.com/optuna/optuna/issues/4893#issuecomment-1732889221. (of course you can use `dict`s if you want readability in Optuna Dashboard.)

**Comment by Guillaume227** [comment]
I ran again into a use-case requiring that feature. 
For the record, I got around it with the following few lines in distriutions.py at the top of json_to_distributions:

```
    json_dict = json.loads(json_str)
    if attributes := json_dict.get("attributes"):
        if choices := attributes.get("choices"):
            for choice_idx, choice in enumerate(choices):
                if isinstance(choice, list):
                    choices[choice_idx] = tuple(choice)
```
It doesn't address all the concerns mentioned above but it might be useful as a good-enough patch for people landing on this issue.
