### ISSUE TITLE
Issue size key with MySQL

### ISSUE THREAD

**Issue by lschneidpro** [optuna/optuna#501]
Hi there,

I'm running optuna on my uni cluster and in addition to a MySQL server provided by the uni.

Running:
```
study = optuna.create_study(direction='maximize',
                                    study_name=name,
                                    storage='mysql+mysqlconnector://user:#password@host/DB',
                                    load_if_exists=True)
```

The code crashed:

```
sqlalchemy.exc.ProgrammingError: (mysql.connector.errors.ProgrammingError) 1071 (42000): Specified key was too long; max key length is 1000 bytes
[SQL: 
CREATE TABLE study_user_attributes (
	study_user_attribute_id INTEGER NOT NULL AUTO_INCREMENT, 
	study_id INTEGER, 
	`key` VARCHAR(512), 
	value_json VARCHAR(2048), 
	PRIMARY KEY (study_user_attribute_id), 
	UNIQUE (study_id, `key`), 
	FOREIGN KEY(study_id) REFERENCES studies (study_id)
)

]
(Background on this error at: http://sqlalche.me/e/f405)
```

From PhpMyAdmin, i have the following info:

**Database Server:**

- Server: MySQL 1 (V5.7.27)
- Server connection collation: utf8mb4_unicode_ci
- Server charset: UTF-8 Unicode (utf8)

**My Database**

- Type: MyISAM

Is there a way to use such DB with optuna? Thanks for any input

**Comment by toshihikoyanase** [comment]
Thank you for your question.
I think the best solution is to change the storage engine from MyISAM to InnoDB if possible.

This is mainly because the maximum key length of MyISAM caused the error you mentioned. I think you can avoid it by changing the value of `MAX_INDEXED_STRING_LENGTH` in `optuna/storages/rdb/models.py` from `512` to `249` (or so). But still, you may have problems.

MyISAM does not support features such as transaction and foreign key constraints, and I'm not sure if Optuna works properly even if you change the key length.

**Comment by toshihikoyanase** [comment]
Closing this issue since there are no activities for several months. Feel free to reopen or create a new issue if you have any problems.
