### ISSUE TITLE
JournalStorage: Checkpoints / Compression

### ISSUE THREAD

**Issue by Turakar** [optuna/optuna#5013]
### Motivation

My JournalStorage has grown to 172 MB in size, also because I store training logs in the user attributes. In general, every JournalStorage will grow to a large size during longer operation. Transferring the JournalStorage from the HPC cluster to my laptop begins to be a nuisance due to this. Sever-based storage are no alternative for me, as I cannot start a central server on the HPC cluster. It might be good to consider checkpointing / switching to a faster or more compact message format to reduce the Journal size.

### Description

**Checkpointing** Currently, all operations are written to a single file. For checkpointing to work, one process should acquire an exclusive lock on this file, re-write its contents into a compressed format, and then release the lock. This would decrease file size and loading time. All other processes need to recognize this event and update their position in the file accordingly.

**Message format** Currently, all messages are stored in JSON arrays. We might consider adding something like [msgpack](https://github.com/msgpack/msgpack-python). I think that the [streaming unpacker](https://github.com/msgpack/msgpack-python#streaming-unpacking) might improve performance significantly (If the actual processing of the read  data is not dominating the runtime, that is. I did not profile it, yet.).

### Additional context (optional)

Further things to consider:

- How to handle past data which is not relevant anymore? Currently, a deleted study is not actually deleted from the JournalStorage, but it is only marked as deleted. In the compressed variant, one may choose to delete this data forever, or keep it somewhere. I prefer the former, as this mimics how the other storages work.
- When should we compress the storage? Maybe based on file size?

**Comment by c-bata** [comment]
Hi @Turakar, thanks for your suggestions!

We actually did contemplate using binary serialization formats like msgpack or protobuf when we first introduced JournalStorage. However, we chose to stick with JSON Lines for its easier maintenance and lesser dependencies.

That being said, your ideas for improving and enhancing the performance are very intriguing. Instead of integrating all these changes directly into Optuna, how about we make them available as a third-party library? The functionality sounds quite beneficial, and if it becomes a library, we could even feature it in our official documentation or blog posts.

Regarding your last question, it's worth noting that JournalStorage includes a Snapshot feature. Similar to JournalRedisStorage, we can implement save_snapshot() and load_snapshot() methods, which would mean we wouldn't have to review the logs from the start. Though the feature was introduced for speed-up rather than compression, it might be possible to discard past logs up to a certain point during the save_snapshot() method.

https://github.com/optuna/optuna/blob/c21fe6253343950f31d9ae0bc13be384236335e6/optuna/storages/_journal/redis.py#L92-L97

**Comment by Turakar** [comment]
It seems like snapshots are only implemented for Redis, which does require a central server.

I would be open to the idea of a library, as I generally think that there is still quite some potential for how we keep central storage in NFS HPC systems in Python. However, I currently do not have the capacity to implement it.
