### ISSUE TITLE
Remove `MOTOESampler` from documentation

### ISSUE THREAD

**Issue by HideakiImamura** [optuna/optuna#5072]
### What is an issue?

The `optuna.samplers.MOTPESampler` is deprecated from v2.9.0 since the `optuna.samplers.TPESampler` supports the same algorithm by default. I suggest to remove it from the documentation to avoid misunderstanding.

**Comment by Ashhar-24** [comment]
@nzw0301 Can you please check and revert back to me if I'm supposed to do it other way.
Is there any community of optuna available so that I can get my queries resolved as i'm totally a beginner and want to learn more about open source contributions.

**Comment by nzw0301** [comment]
> 
Is there any community of optuna available so that I can get my queries resolved as i'm totally a beginner and want to learn more about open source contributions.

In my understanding, we don't have such a community for Optuna development, but [github discussions](https://github.com/optuna/optuna/discussions) or StackOverflow is a good place to ask a question.

**Comment by Ashhar-24** [comment]
@HideakiImamura The changes that I'd made in the issue #5072, has been approved by Collaborator @nzw0301 .
Kindly merge the PR and if not please suggest edits, if needed I'll be happy to work on it.
Thanks

**Comment by not522** [comment]
This issue has been resolved by #5084.
