### ISSUE TITLE
 No exception when passing invalid data to .enqueue_trial

### ISSUE THREAD

**Issue by qnbhd** [optuna/optuna#5113]
### Expected behavior

It is expected that some exception will be raised when passing obviously incorrect data (not matching the `Dict[str, Any]` type) to `study.enqueue_trial`. 

### Environment

- Optuna version:3.4.0
- Python version:3.9.6
- OS:macOS-13.0.1-arm64-arm-64bit

### Error messages, stack traces, or logs

```shell
[I 2023-11-14 12:09:55,858] A new study created in memory with name: no-name-7cf052d2-a932-4b47-bdae-130b5491e38b
0 5
1 4
2 2
3 0
4 0
```

### Steps to reproduce

```python
import optuna

study = optuna.create_study(direction="maximize")
study.enqueue_trial({"foo": 5})  # OK
study.enqueue_trial([{"foo": 15}]) # Exception expected
study.enqueue_trial([1, 1, 3]) # Exception expected

for _ in range(5):
    trial = study.ask()
    foo = trial.suggest_int("foo", 0, 10)
    print(trial._trial_id, foo)  # noqa
    study.tell(trial, 0.1)
```

**Comment by nzw0301** [comment]
Thank for your your input. As we can see the example, `study` cannot know the parameter space defined in the objective when `enqueue_trial` is called. In addition, I do not expect `study.enqueue_trial([{"foo": 15}])` shows some warning message because Optuna supports dynamic search space, which contradicts with causing some exception.

I agree that showing some warning message for the third case `study.enqueue_trial([1, 1, 3])` seems useful.

Thus I remove `bug` label from this issue.
