### ISSUE TITLE
Document the link to the Terminator's example

### ISSUE THREAD

**Issue by HideakiImamura** [optuna/optuna#5204]
### What is an issue?

While there is [documentation](https://optuna.readthedocs.io/en/stable/reference/terminator.html) for the `optuna.terminator` module, there is no link anywhere in the documentation to the module's [example](https://github.com/optuna/optuna-examples/tree/main/terminator). Adding the link will make it easier for users to notice the function.

**Comment by HarshitNagpal29** [comment]
HI @HideakiImamura Sir, i created a pull request regarding this issue here (https://github.com/optuna/optuna/pull/5243). You can check it and tell me if any correction needed. Also sorry for not asking you to assign me as I thought it is a very small issue and didn't find any need to get assigned, I am new to open source world, sorry for any inconvenience caused unintentionally . THank you and have a great day.

**Comment by nzw0301** [comment]
@HideakiImamura Thank you for your review. We can close this issue thanks to @HarshitNagpal29's #5243.
