### ISSUE TITLE
make optuna as a service

### ISSUE THREAD

**Issue by ChenjunZou** [optuna/optuna#725]
Will Optuna provide a layer of rest API  to make sampler can be called as a service.  
As I know Google Vizier provides functionality "opt as a service"
APIs like 
HTTP POST  study/add/
HTTP POST trial/add  
HTTP POST trial/feedback

If rest API exists, other programming languages can use Optuna to do blackbox optimization as well.

**Comment by sile** [comment]
Thank you for proposing this feature.
I think that it could be helpful to provide the API as a service for users other than Python. Actually, some users have developed porting libraries of Optuna such as [goptuna](https://github.com/c-bata/goptuna) and [red-optuna](https://github.com/red-data-tools/red-optuna) for Golang and Ruby respectively.
However, IMO, to design and implement the service API is not an easy task. Besides, as Optuna is an actively developed library, so the maintenance and support cost of the API could be high.
For now, we’d like to concentrate on improving Optuna as a Python library.

**Comment by ljvmiranda921** [comment]
Hello, 

I am trying to create a simple Optuna service in this repository: https://github.com/ljvmiranda921/optserve

The main idea is to have a framework that serves and accepts Optuna studies in a Kubernetes cluster.

I am not yet sure how fast the progress of this library would be since I'm just building this during my free time. However, I'm happy to discuss my initial plans and roadmap and if this coincides with what users would love to have.

@sile @ChenjunZou

**Comment by g-votte** [comment]
@ljvmiranda921 
Cool! I've found it very interesting how Optuna can coordinate with practical infrastructure/pipeline systems like Kubernetes.

Do you have some working example of the library?

**Comment by sile** [comment]
Let me close this PR since it seems the original question from @ChenjunZou has already been answered, and there are no activities for about two months. Feel free to write comments or even reopen this issue if there are any updates.
