### ISSUE TITLE
Warn of too many trials in visualization features.

### ISSUE THREAD

**Issue by g-votte** [optuna/optuna#733]
The motivation is similar to #732. When the number of trials is too many, outputting some warning would be more user friendly.

**Comment by michiboo** [comment]
Hi can I have a go at this?

**Comment by g-votte** [comment]
@michiboo 
Sure! Please go for it.

**Comment by michiboo** [comment]
@g-votte Hi I created a PR for this issue https://github.com/optuna/optuna/pull/994

**Comment by hvy** [comment]
```python
import time
import optuna


def objective(trial, n_params):
    return sum(trial.suggest_float(f"{i}", 0, 1) for i in range(n_params))


def run_benchmark_plot_function(plot_func, study):
    start = time.time()
    fig = plot_func(study)
    end = time.time()
    print(f"{plot_func}: {end - start:.2f} s")
    fig.show()


if __name__ == "__main__":
    n_params = 32
    n_trials = 1000

    study = optuna.create_study(storage="sqlite:///994.db", study_name="994", load_if_exists=True)
    study.optimize(lambda trial: objective(trial, n_params=n_params), n_trials=n_trials)

    print(f"Trials {len(study.trials)}")

    # run_benchmark_plot_function(optuna.visualization.plot_contour, study)  # Too slow.
    run_benchmark_plot_function(optuna.visualization.plot_intermediate_values, study)
    run_benchmark_plot_function(optuna.visualization.plot_optimization_history, study)
    run_benchmark_plot_function(optuna.visualization.plot_parallel_coordinate, study)
    run_benchmark_plot_function(optuna.visualization.plot_param_importances, study)
    run_benchmark_plot_function(optuna.visualization.plot_slice, study)
```

Just leaving a record and some code for verifying this issue. (Took a quick look as the PR addressing this issue was being stale).
The problem seem to mostly derive from `plot_contour` which basically hangs (several minutes without returning). The other plot functions are more or less instantaneous, except for `plot_param_importance` which take a couple of seconds to finish.

I assume plotly is somewhat slow computing the contours. As for warnings, I believe we only need to raise one for this function. Maybe we can even improve the speed in some what by extracting a subset of trials, but I have not tried this yet.

**Comment by hvy** [comment]
I believe this is still an open issue as #994 unfortunately seems stale.

**Comment by blazespinnaker** [comment]
Can we reopen this?  Adding a parameter to sample randomly would be a good idea.  It bugs out quite easily.  At the very least a doc warning would be helpful
