### ISSUE TITLE
Where can find trial instantiated?

### ISSUE THREAD

**Issue by yuanjames** [optuna/optuna#755]
As the doc described, a trial is instantiated behind the optuna.study.Study.optimize(), but the beblow code does not invoke optimize(), it still works.

def objective(trial):
    x = trial.suggest_uniform('x', -10, 10)
    return x

**Comment by hvy** [comment]
Thanks for reaching out. I'd just like to ask some questions because the issue you're experiencing isn't entirely clear. Could you elaborate what you mean by "it still works" and what you're expecting to happen, maybe along with the whole script? The function definition of `objective` above seems fine and what you have to do is to additionally invoke `optimize` yourself as seen in for instance this example https://github.com/optuna/optuna/blob/master/examples/quadratic_simple.py#L33-L34 to actually have that objective function called.

It by the way seems like you're answering the question in the title, in your description. The trials are instantiated in `optimize` as you mentioned, here https://github.com/optuna/optuna/blob/master/optuna/study.py#L563.

**Comment by yuanjames** [comment]
Hi, really thanks for your reply, and sorry for the not clear description. 

The question I was trying to figure out is, which part of the code is used to instantiate 'trial'. As you replied, in the function of '_run_trial', I can see the 'trial' is instantiated by, optimise() -> _optimize_sequential() -> _run_trial_and_callbacks()-> _run_trial().

Anyway, Appreciation!

**Comment by hvy** [comment]
Great, let's consider it solved then, and thanks for your quick action in updating the issue. 🙂
