### ISSUE TITLE
Exit criterion threshold

### ISSUE THREAD

**Issue by gschwepp** [optuna/optuna#850]
I use optuna to find the minimum of some time consuming functions.

It would be very convenient to be able to define additionally to the number of trials an exit criterion threshold for the .optimize function. Once the threshold is reached the optimizer stops, if not the optimizer runs for the defined number of trials.
Thanks.

**Comment by toshihikoyanase** [comment]
Thank you for your feature request.
I think such a feature is useful, for example, when users do not have enough prior knowledge about objective functions to estimate appropriate computing resources for optimization.

## Design choices

I think we have some design choices. I personally prefer the second approach because we can keep `optimize` method clean. Please let me know if you have any questions or comments.

1) Add a new argument to `Study.optimize`

In this approach, we add a new argument like `threshold` to `Study.optimize` and check the criteria when a trial finished. I think this approach is intuitive for users, but careful discussion will be required not to make the interface messy.

Example of user code:
```python
study = optuna.create_study()
study.optimize(objective, threhold=0.1)
print(study.best_value)  # 0.09.
```

2) Provide an exception to handle threshold, and use callback functions.

In this approach, we add a new exception like `ThresholdExceeded` to notify a study that stop criteria have been satisfied. To check the threshold, users can use the callback feature of `Study.optimize`. This approach is not as simple as the first one, but it is more flexible.

```python
def check_threshold(study, trial):
    if study.best_value < 0.1:
        raise ThresholdExceeded()

study = optuna.create_study()
study.optimize(objective, callbacks=[check_threshold])
print(study.best_value)
```

## Workaround

We can implement the exit-criterion threshold using Optuna v1.0 based on the idea of the second approach. Please let me share a code example:

```python
import optuna

THRESHOLD = 0.1

class ThresholdExceeded(optuna.exceptions.OptunaError):
    pass

def check_threshold(study, trial):
    if study.best_value < THRESHOLD:
        raise ThresholdExceeded()
    return

def objective(trial):
    x = trial.suggest_uniform('x', 0, 1)
    y = trial.suggest_uniform('y', 0, 1)
    return x + y

study = optuna.create_study()
try:
    study.optimize(objective, n_trials=100, callbacks=[check_threshold])
except ThresholdExceeded:
    print('Threshold exceeded: {} < {}'.format(study.best_value, THRESHOLD))
best_trial = study.best_trial
print('params: {}'.format(best_trial.params))
print('value: {}'.format(best_trial.value))
```

You can execute it on Google Colab:
https://colab.research.google.com/drive/1iFb_gowpUJNfrgGTSr_1Jm1_SQmshWbD

**Comment by gschwepp** [comment]
Thank you very much for the detailed answer. 
I also prefer the second approach, as it can be used more versatile. I implemented it into my code and it works great!

**Comment by RaviThej0803** [comment]
What if the threshold varies everytime based on data, how do we fix that threshold then?

**Comment by toshihikoyanase** [comment]
Hi @RaviThej0803. Thank you for your question.
https://github.com/optuna/optuna/pull/1025 introduced a method to stop optimization (i.e., [`Study.stop`](https://optuna.readthedocs.io/en/latest/reference/study.html#optuna.study.Study.stop)). Now, we can change the threshold in objective functions flexibly.

Please call `trial.study.stop()` in your objective function if the threshold based on the data exceeds. The following is an example:

```python
def objective_with_stop(trial):
    data = load_data()
    x = trial.suggest_uniform('x', 0, 1)
    y = trial.suggest_uniform('y', 0, 1)
    value = x + y

    if check_threshold(data, value):
        trial.study.stop()

    return value

study = optuna.create_study()
study.optimize(objective_with_stop)
```

I also updated the [code example](https://colab.research.google.com/drive/1H-foFvi2X_0JehDgb2BJ1480asz8wxaN?usp=sharing), and please check it.

**Comment by RaviThej0803** [comment]
Not able to access that part of code, could you please accept my access request

**Comment by toshihikoyanase** [comment]
@RaviThej0803
I'm sorry for the delayed response. I changed the permission of the example. Could you try it again?

https://colab.research.google.com/drive/1H-foFvi2X_0JehDgb2BJ1480asz8wxaN?usp=sharing
