### ISSUE TITLE
PyMysql error not catched

### ISSUE THREAD

**Issue by erniejunior** [optuna/optuna#879]
During distributed optimization with five workers, one crashed with the following error:
```
sqlalchemy.exc.InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (pymysql.err.InternalError) (1205, 'Lock wait timeout exceeded; try restarting transaction')
[SQL: INSERT INTO trial_system_attributes (trial_id, `key`, value_json) VALUES (%(trial_id)s, %(key)s, %(value_json)s)]
[parameters: {'trial_id': 4530, 'key': '_number', 'value_json': '16'}]
(Background on this error at: http://sqlalche.me/e/2j85) (Background on this error at: http://sqlalche.me/e/7s2a)
```
Full log with all stack traced here: [failure.log](https://github.com/optuna/optuna/files/4133355/failure.log)

It looks like some problem with the pymysql driver which is of course not your fault. However it would be nice if such errors were caught and the trial dropped instead of crashing the entire worker.

Might be related to #386

## Expected behavior

No crashes of the entire application in spite of database errors. Rather repeated retries.

## Environment

- Optuna version: 1.0.0
- Python version: 3.6
- OS: ubuntu:18.04
- Other libraries and their versions: PyMySQL 0.9.3, sqlalchemy-1.3.13

## Error messages, stack traces, or logs

Too long. Look  [here](https://github.com/optuna/optuna/files/4133355/failure.log).

## Steps to reproduce

Unfortunately very hard to reproduce since the other workers are still running just fine.

**Comment by toshihikoyanase** [comment]
Thank you for reporting the issue. I have two comments on it.

## 1. Connection timeout

> (pymysql.err.InternalError) (1205, 'Lock wait timeout exceeded; try restarting transaction')

I think it is related to https://github.com/optuna/optuna/issues/622 because both of them are caused by the connection timeout.

Please try [the workaround](https://github.com/optuna/optuna/issues/622#issuecomment-566916494) shown in the issue. Or please update Optuna with the master branch of this repository because the issue was resolved by https://github.com/optuna/optuna/pull/806.

In addition, I submitted a PR (#873) which enables users to extend `wait_timeout` of MySQL session. Although it is not merged yet, please try it if you're interested in it.

## 2. Exception handling

> However it would be nice if such errors were caught and the trial dropped instead of crashing the entire worker.

You can use the `catch` argument of [`Study.optimize`](https://optuna.readthedocs.io/en/stable/reference/study.html#optuna.study.Study.optimize). In this case, `pymysql.err.InternalError` can be skipped as follows:

```
study.optimize(objective, catch=(pymysql.err.InternalError, ))
```

**Comment by erniejunior** [comment]
Thank you @toshihikoyanase for the hints! When do you plan the next release of optuna? I would rather use released software for my experiments for the sake of reproducability.

**Comment by toshihikoyanase** [comment]
Not decided yet, but I think we can release the next minor update soon (c.f., [milestone of v1.1.0](https://github.com/optuna/optuna/milestone/20)).
I'll let you know as soon as we release it.

**Comment by toshihikoyanase** [comment]
@erniejunior Optuna v1.1.0 was released today! You can try it with `pip install -U optuna`.
I hope `pool_pre_ping` (https://github.com/optuna/optuna/pull/806) can resolve your problem.

**Comment by toshihikoyanase** [comment]
@erniejunior 
Let me close this PR. If you have further problems, please feel free to re-open it.
